### ISSUE TITLE
Video Title (top bar) misplaced while using "Tablet Mini-player"

### ISSUE THREAD

**Issue by DymondZ** [revanced/revanced-patches#1077] opened 2022-11-20 05:46 UTC
### Type

Cosmetic

### Bug description

I tried changing different revanced settings in the patched YouTube App.

Wanted to watch a Video and noticed the title of the video was misplaced. Checked every setting and found that "Tablet Mini-player" toggled on causes the issue.

### Steps to reproduce

1. Play a video, UI elements should be fine.
2. Toggle "Tablet Mini-player" on in Revanced settings
3. Play a Video, title bar is offset to the middle of the Screen
4. Toggle "Tablet Mini-player" off, UI elements should be fine again.

### Relevant log output

```shell
Logcat is >1500 lines, not possible to paste here.
Pls tell me which log you want.
```

### Screenshots or videos

![Screenshot_20221120-062053_YouTube](https://user-images.githubusercontent.com/61392964/202887262-b8d39652-940c-466c-9ac1-d4c53cdfcbb3.png)

![Screenshot_20221120-062154_YouTube](https://user-images.githubusercontent.com/61392964/202887264-d0425bb0-52e4-4561-9d94-13d785fe1dce.png)

### Additional context

Thx for your help and contributions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-11-20 05:49
Dupe of #452.

**Closed by oSumAtrIX** 2022-11-20 05:49 UTC
Labels: bug
