### ISSUE TITLE
feat(patch): Default PlayBack speed Setting to be applied to all videos

### ISSUE THREAD

**Issue by sidillicitaf** [revanced/revanced-patches#536] opened 2022-09-19 06:49 UTC
### Application

Youtube , Revanced 

### Issue

Default Playback speed for all videos to be applied

### Patch

A playback speed can be set once in revanced patches and it should be applied to all the videos that are played, It was a feature available in vanced and is currently avaialble in revanced extended but not officially , it could be implemented and would be very useful as we won't need to setup the speed everytime

### Motivation

I guess there would be a number of users using 1.5x or 2x for default speed, set it once and stick to it would be a very useful feature for us.

**Comment by oSumAtrIX** [comment] 2022-09-19 14:09
Dupe of #518.

**Closed by oSumAtrIX** 2022-09-19 14:09 UTC
Labels: patch-request
