### ISSUE TITLE
feat(Spotify): Transparent status bar 

### ISSUE THREAD

**Issue by QYKLe** [ReVanced/revanced-patches#3013] opened 2023-09-23 06:41 UTC
### Application

Spotify

### Issue

After years the android version of Spotify still got a translucent status bar while iOS got the right version (transparent)

### Patch

From what I know, Android is already predisposed to and immersive mode that allows to make the status bar transparent or hidden so it should be relatively easy to implement!

### Motivation

Found online a quite consistent number of users who finds this decision really ugly

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Aunali321** [comment] 2023-09-23 19:45
Please add screenshots for more context

**Comment by QYKLe** [comment] 2023-09-24 07:32
![spotify-song-iphone~3](https://github.com/ReVanced/revanced-patches/assets/142775305/75d1ec58-d6da-4379-814c-ee51b666f538)
![Screenshot_20230924-092646_Spotify~3](https://github.com/ReVanced/revanced-patches/assets/142775305/746c97a5-db49-47c6-a86f-0e212d17a677)
![Screenshot_20230924-092036_Spotify~4](https://github.com/ReVanced/revanced-patches/assets/142775305/28a34bc3-4ce7-4200-a7e3-78ea87795b57)

**Comment by V9vek** [comment] 2023-10-11 18:56
Hey @oSumAtrIX @Aunali321 I would like to work on this. please assign it to me. 😊

**Comment by oSumAtrIX** [comment] 2023-10-11 19:18
Assigned, thank you!

A short contribution guide is present here: https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md
Introduction for patches are here: https://github.com/ReVanced/revanced-patches/tree/docs/docs
A general development environment setup for ReVanced can be found here: https://github.com/ReVanced/revanced-documentation/tree/main/docs/revanced-development

**Comment by V9vek** [comment] 2023-10-12 05:37
I thought it was just Android thing I have to fix.
But I came to know about Patches, but dont know how they are working.😅
how can I test things by checking the spotify app? I am little bit confused now.

**Comment by oSumAtrIX** [comment] 2023-10-12 11:58
Check the links I sent above.

**Comment by V9vek** [comment] 2023-10-12 12:15
yes I am reading and understanding things from these links.

**Comment by V9vek** [comment] 2023-10-13 17:29
@QYKLe I am not getting any translucent status bar in Android
I downloaded Spotify APK from APKPure version v8.8.76.667
 and patched with RevancedPatcher, the status bar is fine for me, I mean transparent in Android

**Comment by V9vek** [comment] 2023-10-13 17:29
@QYKLe can you tell me how I can reproduce this?

**Comment by V9vek** [comment] 2023-10-14 10:44
@QYKLe which version of apk you downloaded, can you tell please?

**Comment by oSumAtrIX** [comment] 2023-10-14 13:36
The account is inactive, and the issue stale, reopen if needed. Thanks @V9vek

**Closed by oSumAtrIX** 2023-10-14 13:36 UTC
Labels: Waiting on author, Feature request

**Comment by QYKLe** [comment] 2023-10-14 14:31
> @QYKLe I am not getting any translucent status bar in Android I downloaded Spotify APK from APKPure version v8.8.76.667 and patched with RevancedPatcher, the status bar is fine for me, I mean transparent in Android

Sorry I was busy
I got the official apk, same version. I also tried your method but still doesn't work. I got an Android 13 "pixel extended" custom ROM.

I don't really know if it's a problem of mine but I've also heard other people complaining about this so I don't think so.

**Comment by V9vek** [comment] 2023-10-14 16:50
okay but currently I am not getting any issue, and not able to reproduce this. if you can find me some way please ping me here only.

**Comment by QYKLe** [comment] 2023-10-14 20:47
@V9vek I've done some research and it looks like xiaomi devices are the only ones forcing apps to "edge to edge rendering". Other devices should be affected, but i have no solution for you in this moment
I'll keep searching
