### ISSUE TITLE
problem: control buttons stays on top

### ISSUE THREAD

**Issue by Smollejan** [revanced/revanced-patches#221] opened 2022-07-22 19:20 UTC
## 🐞 Issue

Controll buttons don't hide itself but stays on top.

## ⚙ Reproduce

I still haven't found a way to reproduce. It appears randomly after watching a few video's. See the video for more detail.

## ⚠ Additional context

[screen-20220722-210602.webm](https://user-images.githubusercontent.com/69522210/180508962-8fa72c53-3953-4a78-8d61-d515b3b43489.webm)

I've applied the latest patches to the build.
Running A12 Pixel Experience on a Xiaomi Mi-9T

**Comment by oSumAtrIX** [comment] 2022-07-22 19:24
Disable patches until the error is gone, and report back which patch causes it.

**Comment by memories169** [comment] 2022-07-22 20:02
Disable "disable-fullscreen-panels" patch. In my case this patch causes it

**Comment by TheJeterLP** [comment] 2022-07-22 20:34
> Disable "disable-fullscreen-panels" patch. In my case this patch causes it

I use revanced daily for minimum 2 hours and never experienced this. Cannot reproduce

**Comment by OxrxL** [comment] 2022-07-23 19:12
This is a stock bug. Happens to me too, without any patch.

And seems is related to the the speed with which you perform the fullscreen gesture, after playing the video.

**Comment by Smollejan** [comment] 2022-07-23 21:37
> Disable "disable-fullscreen-panels" patch. In my case this patch causes it

Disabling the ''disable-fullscreen'' patch seems to do the trick for me. I'm going to watch how it will perform in the coming days.

**Comment by Smollejan** [comment] 2022-07-24 06:38
I applied the latest build where ''swipe-controls'' is excluded by default. And now it seems to work perfectly, even with ''disable-fullscreen-panels'' enabled.

**Comment by TheJeterLP** [comment] 2022-07-24 06:47
I still cannot reproduce this behavior. I've included every patch.

**Comment by Smollejan** [comment] 2022-07-25 15:47
I'm closing this issue as the problem has not appeared the last days with the latest patches. I think is has something to do with the swipe-controls patch. Thanks for the help everyone!

**Comment by kkellogg378** [comment] 2022-08-17 18:00
On the latest (as of 3 days ago) patches and had this bug, disabling "disable fullscreen panels" in the settings fixed it

**Comment by kkellogg378** [comment] 2022-08-26 15:18
Seems to be fixed on 2.42.1

**Comment by MrMikeJJ** [comment] 2022-10-21 18:18
i occasionally still get this issue. Since reading here, i stopped using the "disable fullscreen panels" patch, but still get it.  Clearing the cache seems to resolve it. But admittedly it does seem to happen a lot less without that patch installed.

**Comment by sym0nd0** [comment] 2022-11-05 22:38
Manager 
```
Version: 0.0.39
Model: SM-S908B
Android Version: 13
Arch: arm64-v8a
```
Patches 
V2.102.1

YouTube
V17.43.36

Happening for me, not including the following sorted it for me.

```
- Disable Auto Player Popup Panels
- Disable Fullscreen Panels
```

**Comment by ILoveOpenSourceApplications** [comment] 2023-03-29 16:43
This issue is also present in the stock YouTube app and should be fixed by Google. Closing as it's not an issue related to ReVanced.

**Closed by ILoveOpenSourceApplications** 2023-03-29 16:43 UTC
Labels: bug

**Comment by ILoveOpenSourceApplications** [comment] 2023-03-29 17:02
I have seen a comment at some point saying that they had this issue on stock YouTube as well. If so then there's nothing we can do about it right?

**Comment by ILoveOpenSourceApplications** [comment] 2023-03-30 04:40
[#350](https://github.com/inotia00/ReVanced_Extended/issues/350#issuecomment-1446336969) (comment)
