### ISSUE TITLE
Live chat in full screen mode not working.

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#83] opened 2022-06-30 10:54 UTC
![image](https://user-images.githubusercontent.com/69076256/176658763-a46cfce6-ac82-4525-b398-fdfa531d8378.png)

Hehe

**Comment by oSumAtrIX** [comment] 2022-06-30 23:11
Disable patches and see when it is fixed.

**Comment by Itroublve** [comment] 2022-06-30 23:25
The issue is most likely due to the `disable-fullscreen-panels: Disable comments panel in fullscreen view.` patch.

**Comment by oSumAtrIX** [comment] 2022-06-30 23:30
@bogadana A fix for that would be to find the code which is respnsible to show() the view and return it. Iirc you were hiding the view.

**Comment by bogadana** [comment] 2022-06-30 23:30
this is intended behaviour imo

**Comment by bogadana** [comment] 2022-06-30 23:33
when settings exist i can probably make it customisable by type of panel

**Comment by oSumAtrIX** [comment] 2022-06-30 23:34
Should it not just be "hidden by default"? Would make more sense from UX perspective

**Comment by bogadana** [comment] 2022-06-30 23:36
how do you suggest to override the default

**Comment by oSumAtrIX** [comment] 2022-06-30 23:41
Somewhere, the pseude show() method is called, hence you can find references to it. If you find the correct method and remove the show() call it should not show() by default any more.

**Comment by bogadana** [comment] 2022-06-30 23:45
how do you want this to work ui wise though

**Comment by oSumAtrIX** [comment] 2022-06-30 23:48
The code will not show() the comments etc by default, if you press the buttons on the ui though, it is a different method you didn't touch. That calls show() and shows the comments view as expected

**Comment by bogadana** [comment] 2022-06-30 23:48
if you press the button it will just close the panel even if its not showing

**Comment by oSumAtrIX** [comment] 2022-06-30 23:50
What do you mean

**Comment by bogadana** [comment] 2022-06-30 23:51
when the panel is hidden its still 'open' so the button is lit up and will close it if you touch it

**Comment by oSumAtrIX** [comment] 2022-06-30 23:54
Instead of hiding the view you should block the call to the show() function for that view from the code which is responsible to auto show it.

**Comment by bogadana** [comment] 2022-06-30 23:56
then it will require 2 button presses and will reset the panel

**Comment by bogadana** [comment] 2022-06-30 23:58
actually looks like the state stays even after its closed. still the issue of 2 presses

**Comment by oSumAtrIX** [comment] 2022-07-01 00:00
The issue would be gone since you are just blocking the auto show() function. The auto show() function is also switching the state of the view to SHOWN. Since you remove that call, the state will simply stay the same, as if the auto show() function was never called.

**Comment by bogadana** [comment] 2022-07-01 00:01
the button doesnt care if the view is actually shown (as can be seen in the current patch)

**Comment by bogadana** [comment] 2022-07-01 00:02
![image](https://user-images.githubusercontent.com/30848157/176797562-f387e68b-b8a4-4fc5-94a9-95a38a770832.png)

view not shown but button still lit up

**Comment by oSumAtrIX** [comment] 2022-07-01 00:39
Is it caused by the patch?

**Comment by bogadana** [comment] 2022-07-01 00:41
yes its hidden by the patch

**Comment by bogadana** [comment] 2022-07-01 00:42
i think this is doable but the buttons will require modification

**Comment by oSumAtrIX** [comment] 2022-07-01 00:47
No, thats the point. It is highlighted because you just hide the view but don't block the show() function which enables that highlighting. If you block it to begin with, it would behave correctly.

**Comment by bogadana** [comment] 2022-07-01 01:19
i dont think the button is called in this way, its litho

**Comment by bogadana** [comment] 2022-07-01 01:24
the button itself is a litho component

**Comment by oSumAtrIX** [comment] 2022-07-01 01:28
The button is not responsible to auto show the view. Its some backend code as prevs said.

**Comment by bogadana** [comment] 2022-07-01 01:36
hard to find where exactly that happens

**Comment by TheJeterLP** [comment] 2022-07-01 03:33
Why all that hassle? Let this guy exclude the patch and problems gone. When we have settings we can let them choose in the settings which panels to shown and which to hide

**Comment by oSumAtrIX** [comment] 2022-07-01 08:23
> Why all that hassle?
It's not. The patch itself is faulty. It creates an issue, that being that it hides the view, but you can not open the live chat. Instead, what it should've been doing, is hiding the comments view by default. There is code, responsible for checking if the comments flyout is visible, if so, show() the fullscreen panel. This response code is not being blocked by the patch while it should. Because it is not, the problem OP has happened. Hence it is required for this patch to block that responsible code, instead of just hiding the view. The result would be, that the full screen panel view would now not be shown by default, __unless__ you click on the buttons to show them.

**Comment by TheJeterLP** [comment] 2022-07-01 08:28
> > Why all that hassle?
> 
> It's not. The patch itself is faulty. It creates an issue, that being that it hides the view, but you can not open the live chat. Instead, what it should've been doing, is hiding the comments view by default. There is code, responsible for checking if the comments flyout is visible, if so, show() the fullscreen panel. This response code is not being blocked by the patch while it should. Because it is not, the problem OP has happened. Hence it is required for this patch to block that responsible code, instead of just hiding the view. The result would be, that the full screen panel view would now not be shown by default, __unless__ you click on the buttons to show them.

Ahh okay now I understand the problem

**Comment by AMSAMSAMSAMS** [comment] 2023-01-13 02:22
And on normal tablet landscape view (not fullscreen), it just crashed after some minutes when the live chat column visible.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-14 15:39
I'm really sure this is fixed currently and doesn't exist anymore.  Closing it hence.

**Closed** 2023-02-14 15:40 UTC
Labels: bug
