### ISSUE TITLE
Pinch to Zoom (YouTube)

### ISSUE THREAD

**Issue by ankur-raikwar** [revanced/revanced-patches#1027] opened 2022-11-12 15:01 UTC
### Type

Error at runtime

### Bug description

**Bug :** 

- Pinch-to-Zoom does not work everytime after quitting and relaunching app.
- Tried with same video multiple times, but it works like 3 out of 10 times. 
- Tried with other videos as well, same result as above. 
- Clearly not anything related with 16:9 as it may stop working after quitting and relaunching app for any video as it was working before.

**Versions Affected :**
All

**Produced and Tested on Devices**

1. Xiaomi Redmi Note 6 Pro
2. Xiaomi Redmi Note 10 Pro Max
3. Realme 5 Pro

### Steps to reproduce

1. Launch YouTube and Play any Video
2. Go full Screen and Pinch for "Zoomed to fill"
3. If Zooming Works, Quit App and Repeat Step 1,2. 
4. Zoom Might not work again (even with same video as it was working before).

### Relevant log output

```shell
Zoomed to fill bug out
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-11-12 15:02
Dupe of #268.

**Closed by oSumAtrIX** 2022-11-12 15:02 UTC
Labels: bug

**Comment by trmdi** [comment] 2022-11-19 13:47
> Possible Solution to avoid this ?

See the other issue and confirm that?

**Comment by trmdi** [comment] 2022-11-20 12:14
> > See the other issue and confirm that?
> 
> Exclude : Disable Full Screen Panel Patch when building/patching.

Read my comment.
