### ISSUE TITLE
bug: custom-playback-speed and sponsorblock fails when building

### ISSUE THREAD

**Issue by ibrunops** [revanced/revanced-patches#592] opened 2022-09-23 06:49 UTC
### Type

Error while patching

### Bug description

When I tried to build reVanced, `custom-playback-speed` and `sponsorblock` patches failed.

### Steps to reproduce

Building reVanced.

### Relevant log output

```shell
$ java -jar cli.jar \
 --custom-aapt2-binary=/home/kali/Downloads/revanced/dist/arm64-v8a/aapt2 \
 -a youtube.apk \
 -c \
 -o revanced.apk \
 -b patches.jar \
 -m unsigned.apk \
 --exclude=hide-cast-button
INFO: Decoding resources 
INFO: Reading dex files 
INFO: Merging unsigned.apk 
WARNING: Skipping hide-premium-navbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music 
WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android 
WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage 
WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage 
WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a 
WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
INFO: Skipping compact-header, reason: excluded by default 
WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp 
WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
INFO: Skipping hide-cast-button, reason: manually excluded 
INFO: Skipping enable-debugging, reason: excluded by default 
INFO: swipe-controls succeeded 
INFO: downloads succeeded 
INFO: seekbar-tapping succeeded 
INFO: hide-create-button succeeded 
INFO: hide-shorts-button succeeded 
INFO: return-youtube-dislike succeeded 
INFO: hide-autoplay-button succeeded 
INFO: premium-heading succeeded 
INFO: custom-branding succeeded 
INFO: disable-fullscreen-panels succeeded 
INFO: old-quality-layout succeeded 
INFO: theme succeeded 
INFO: hide-watermark succeeded 
SEVERE: sponsorblock failed: 
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:329)
        at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:41)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
        ... 16 more
INFO: enable-wide-searchbar succeeded 
INFO: hide-time-and-seekbar succeeded 
INFO: disable-auto-player-popup-panels succeeded 
INFO: tablet-mini-player succeeded 
INFO: disable-auto-captions succeeded 
INFO: minimized-playback succeeded 
INFO: client-spoof succeeded 
INFO: custom-video-buffer succeeded 
INFO: always-autorepeat succeeded 
INFO: microg-support succeeded 
INFO: settings succeeded 
SEVERE: custom-playback-speed failed: 
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.youtube.misc.customplaybackspeed.patch.CustomPlaybackSpeedPatch.execute(CustomPlaybackSpeedPatch.kt:113)
        at app.revanced.patches.youtube.misc.customplaybackspeed.patch.CustomPlaybackSpeedPatch.execute(CustomPlaybackSpeedPatch.kt:27)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
        ... 16 more
INFO: hdr-auto-brightness succeeded 
INFO: remember-video-quality succeeded 
INFO: video-ads succeeded 
INFO: general-ads succeeded 
INFO: hide-infocard-suggestions succeeded 
INFO: Compiling resources 
WARNING: aapt2 W 09-23 05:55:15 24797 24797] Unknown chunk type '200'. 
INFO: Writing modified dex files 
INFO: Writing dex file classes.dex 
INFO: Writing dex file classes3.dex 
INFO: Writing dex file classes4.dex 
INFO: Writing dex file classes8.dex 
INFO: Writing dex file classes5.dex 
INFO: Writing dex file classes6.dex 
INFO: Writing dex file classes7.dex 
INFO: Writing resources... 
INFO: Aligning revanced_raw.apk to revanced_aligned.apk 
INFO: Signing revanced_aligned.apk to revanced_signed.apk 
INFO: Copying revanced_signed.apk to revanced.apk 
INFO: Cleaned up cache directory 
INFO: Finished
```

### Additional context

I used latests versions of CLI `(revanced-cli-2.11.2-all.jar)`, Patches `(revanced-patches-2.68.0.jar)` and Integrations `(v0.42.0)`.
Youtube version `17.36.37` (recommended).
I use a custom binary because I'm using Linux arm64 (Raspberry Pi).
I built reVanced a few weeks ago on this same system with no problems (with the same CLI instructions and binary), youtube version `17.32.35`. If I try to build again on this same version of youtube `(17.32.35)` but with latests CLI, Patches and Integrations, `hide-create-button`, `sponsorblock`, `custom-playback-speed` and `hdr-auto-brightness` patches fail.
In all cases, excluding or not `hide-cast-button` patch doesn't change the final result.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-09-23 07:02
Dupe of #567.

**Closed by oSumAtrIX** 2022-09-23 07:02 UTC
Labels: bug

**Comment by SebiAi** [comment] 2022-09-23 10:38
sponsorblock works now but custom-playback-speed still fails.
Patches: v2.68.1
CLI: v2.11.2
Integrations: v0.42.0
YT: v17.36.37
