### ISSUE TITLE
bug: patched Photos app refuses to install

### ISSUE THREAD

**Issue by twistedmacaroni** [ReVanced/revanced-patches#3754] opened 2024-10-09 08:04 UTC
### Bug description

Device: Pixel 7

Screen Recording: https://photos.app.goo.gl/WzdZyGegqYog4pyR8

The original photos app was disabled and this one was downloaded from apkmirror and patched without tampering with anything. 

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by twistedmacaroni** [comment] 2024-10-09 08:13
logs after a recent patch: (the installation kept cancelling on its own)

- Device Info
ReVanced Manager: 1.22.0
Model: Pixel 7
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v5.64.0.404595723 (Suggested: Any)
Patches version: v4.16.0
Patches added: Default
Patches removed: Restore hidden 'Back up while charging' toggle
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installation canceled
Installing patched app
Installation canceled

**Comment by oSumAtrIX** [comment] 2024-10-09 10:35
The issue is unrelated to the patches and may be fixed in ReVanced Manager in dev

**Closed by oSumAtrIX** 2024-10-09 10:35 UTC
Labels: Bug report
