### ISSUE TITLE
bug: SponsorBlock skipping a segment at the end of a video in playlist and doesnt autoplay the next video in playlist

### ISSUE THREAD

**Issue by Xycotic01** [ReVanced/revanced-patches#3524] opened 2024-08-11 03:29 UTC
### Bug description

This is the same issue I brought up many months ago in two separate bug reports (https://github.com/ReVanced/revanced-patches/issues/68) and (https://github.com/ReVanced/revanced-patches/issues/46). It was resolved, but I discovered a new video where SponsorBlock skipping a segment at the end of a video (the video is in a playlist) somehow disables the autoplay of the next video in a playlist. I was listening to my watch later playlist and found this example (https://www.youtube.com/watch?v=-cIHLgGZByY). Not sure if others may be able to replicate my issues. Just wanted to bring it up. And yes, of course the video works when I turn off SponsorBlock because there isnt any skipping of segments.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Xycotic01** [comment] 2024-08-11 03:42
I am using bluetooth headphones

**Comment by Xycotic01** [comment] 2024-08-11 03:42
But when i disconnect them, the problem still occurs.

**Comment by Xycotic01** [comment] 2024-08-11 04:19
Just tried turning off and restarting, but still the same issue. No autoplay

**Comment by oSumAtrIX** [comment] 2024-08-11 06:25
Dupe of https://github.com/ReVanced/revanced-patches/issues/3015

**Closed by oSumAtrIX** 2024-08-11 06:25 UTC
Labels: Bug report

**Comment by Xycotic01** [comment] 2024-08-11 06:29
But its not a duplicate. 3015 says that turning off bluetooth worked, but my issue isnt fixed by that.

**Comment by oSumAtrIX** [comment] 2024-08-11 07:11
The issue is the same
