### ISSUE TITLE
bug: ADs visible after changing DPI

### ISSUE THREAD

**Issue by Amby713** [revanced/revanced-patches#563] opened 2022-09-21 00:48 UTC
### Type

Other

### Bug description

I don't like the big and wide video on YouTube, so I change my youtube's DPI.

When at 300 DPI, i get no ads and get the horrible large videos.

When I change it to under 280 DPI, it looks nicer, but the ads on the home page and suggested videos appear.

### Steps to reproduce

Termux
su -c wm density 240

Ads appear

Termux
su -c wm density reset

No more ads

### Relevant log output

```shell
No logs
```

### Screenshots or videos

![Screenshot_20220920-193232_YouTube](https://user-images.githubusercontent.com/105613369/191389383-1817545e-6775-4c91-b9e9-e897c060e92a.png)

![Screenshot_20220920-193208_YouTube](https://user-images.githubusercontent.com/105613369/191389508-3e802a7d-d127-4c3e-b803-597f925088ca.png)
![Screenshot_20220920-193558_YouTube](https://user-images.githubusercontent.com/105613369/191389521-519ae969-3ada-43a8-a84e-3a28840050a2.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-09-21 00:56
Dupe of/Related to #206.

**Closed by oSumAtrIX** 2022-09-21 00:56 UTC
Labels: bug
