### ISSUE TITLE
bug(YouTube): Spoof app signature - various side effects

### ISSUE THREAD

**Issue by JUANHDA-CX** [ReVanced/revanced-patches#1752] opened 2023-03-14 22:30 UTC
### Type

Cosmetic

### Description

- [x] ~~Video is not added to the history properly~~ Fixed in latest patch
- [x] ~~Audio playback forced in feed~~ Fixed
- [x] ~~Subtitles sometimes don't appear in correct location~~ Fixed
- [x] ~~Playback issues with some videos: home feed autoplay, playlists, opening videos from push notifications, opening some external video links~~ Fixed 
- [x] ~~Endscreen cards are always hidden~~ Fixed
- [x] ~~Built in YouTube download feature does not work for long videos or downloading multiple videos at once~~ Fixed
- [x] ~~Download button is hidden in old layout~~ Fixed
- [x] ~~Ambient mode does not work~~ Fixed
- [x] ~~Shared clips do not playback from the clipped time region~~ Fixed
- [x] ~~Autoplayed videos from feed are added to history~~ Fixed
- [x] ~~Seekbar preview thumbnails are in low quality~~ Fixed
- [x] ~~Home feed autoplay does not show close caption text~~ Fixed
- [x] ~~Zoom to fill sometimes does not work~~ Fixed

**Comment by oSumAtrIX** [comment] 2023-03-14 22:41
Try with stock YouTube.

**Comment by joyskmathew** [comment] 2023-03-15 05:17
It was removed from the stock app also

But if somehow, revanced team can reproduce it, it would be great

**Comment by SodaWithoutSparkles** [comment] 2023-03-15 05:22
Cannot reproduce, I still have it in revanced. Maybe google is doing A/B testing?

![Screenshot_app.revanced.android.youtube-edit.jpg](https://user-images.githubusercontent.com/64138578/225214815-9a7b7b01-62f3-405f-ae1b-340d419afe7e.jpg)

**Comment by oSumAtrIX** [comment] 2023-03-15 14:42
No, if you include microg-support patch, the spoof-signature-verification also gets included.

**Comment by kazimmt** [comment] 2023-03-15 14:49
This issue arrived after this spoof-signature-verification patch
inotia00 also discussed about it on his group. He add a settings to toggle it on/off

**Comment by oSumAtrIX** [comment] 2023-03-15 14:52
Not really a good solution, ideally the patch works around the playback as cleanly as possible

**Comment by kazimmt** [comment] 2023-03-15 14:53
It works to fix buffer issue, 
But see already 3 issue arrived after this patch

Ya it's not a good solution. But maybe temporary

Settings for this patch, Refer to: 
https://github.com/inotia00/revanced-patches/commit/18747410769cd7723616d2155474e06850305024
https://github.com/inotia00/revanced-integrations/commit/781dd894571c2ded94e60b651cabb9fa35bd800a

**Comment by SodaWithoutSparkles** [comment] 2023-03-15 15:02
> It's also related to #1749 
> I mean when `spoof-signature-verification` patch selected
> - ambient mode doesn't work
> - auto play in homefeed, search feed with sound
> & few more bugs

I dont have the bugs you mentioned. I patched on v2.165.1 IIRC

**Comment by oSumAtrIX** [comment] 2023-03-15 16:27
YouTube builds a `VideoStartDescriptor` object, every time a video is played.  We modify a method, which gets that field and overwrites the value. I have seen closely related code to ads in relation to the `VideoStartDescriptor` object and since video playback issues always stop after a certain amount of time I assume it does when it tries to load an ad. If that is the case, the field of that object could be modified at the place where the descriptor is built for the ad and playback does not fail.

**Comment by kazimmt** [comment] 2023-03-15 16:27
Yes, no-one still mentioned it here

Seek preview Thumbnail also missing after this patch

**Comment by kazimmt** [comment] 2023-03-15 17:19
> 
> This gives no spoofing side effects unless spoofing is absolutely needed.

But this patch is specially designed for them who facing buffer issue. They have to deal with these bugs or infinity buffering.

**Comment by johnconner122** [comment] 2023-03-16 01:26
To enable ambient mode, just restart the app after toggling ambient mode, it works, at least, for me.

**Comment by senposage** [comment] 2023-03-17 21:53
other then some random app crashes it seems like the spoof patch has resolved the video not loading 

**a reminder to others that You must CLEAN INSTALL Revanced DO NOT UPDATE THE APP In-place or the patches may not work correctly**

**Comment by oSumAtrIX** [comment] 2023-04-14 02:22
Is this confirmed? I am able to automatically trigger the detection on some account. I have kept it in case someone disables it when it is required for them.

**Comment by oSumAtrIX** [comment] 2023-04-14 02:29
From my tests merely the video should be just restarted to fix the issue. A restart would be fine in that case.

**Comment by johnconner122** [comment] 2023-04-14 12:55
> It appears the automatic detection no longer works (YouTube is no longer returns 4xx status code, or the connection fails somewhere else and not during video playback).

It was automatically triggered for me. I guess it is still working.

**Comment by muchisx** [comment] 2023-04-15 02:07
How do it update the app to include the fixes marked as done? or are they not live yet? I'm still getting the infinite buffering after watching for a little while

**Comment by oSumAtrIX** [comment] 2023-04-15 02:07
You update by repatching

**Comment by oSumAtrIX** [comment] 2023-04-22 15:17
It is possible that offline downloads are not being spoofed correctly, as they fail to download completely, likely a case of the conditions present in integrations. Some people are able to reproduce.

**Comment by SodaWithoutSparkles** [comment] 2023-04-28 07:19
_Transfered from #2005_

I hereby suggest the description of signiture verification in revanced settings should mention all known side effects.

It could be something like a block under spoof signiture verification listing out all side effects.

**Comment by 0xrxL** [comment] 2023-04-28 12:50
> "Can't zoom to fill"
> 
> Any details on this? Pinch to zoom works ok for me.

Same:

https://user-images.githubusercontent.com/127248639/235152059-9c15e4df-8e71-4c55-9032-e0f4f0a1a98f.mp4

**Comment by SodaWithoutSparkles** [comment] 2023-04-29 02:25
![Screenshot_2023-04-29-10-24-56-229_app.revanced.android.youtube.jpg](https://user-images.githubusercontent.com/64138578/235279407-b2a15598-4f1c-4169-952a-3fc61713648f.jpg)

Pinch to zoom also work for me

**Comment by SodaWithoutSparkles** [comment] 2023-04-29 02:33
Ambient mode works. It is just bugged out by default. You just need to disable ambient mode, and enable it again, then it works consistently even after a force-stop and restart.

We could do sth similar to spoofing signatures and help the user dis-en-able ambient mode automatically. Or it could just be a tooltip in #2011: "ambient mode needs to be turned off and on again to work".

**Comment by castdrian** [comment] 2023-04-30 13:13
The subtitle issue still occurs with the latest version of the patches

**Comment by SodaWithoutSparkles** [comment] 2023-04-30 13:17
> The subtitle issue still occurs with the latest version of the patches

Known issue. It would be fixed automatically when you watch the second video.

https://github.com/SodaWithoutSparkles/revanced-troubleshooting-guide#311-captions-in-the-wrong-place

**Comment by SodaWithoutSparkles** [comment] 2023-05-01 18:35
Confirm fixed in 2.172.0

**Comment by SodaWithoutSparkles** [comment] 2023-05-02 01:29
It has been reported recently that spoof signature verification and/or client spoof might cause unintended consequences when playing videos in playlist. They would stop and buffer for no apparent reason even when the aforementioned patch are on and enabled

**Comment by oSumAtrIX** [comment] 2023-05-02 01:30
Please include a full recording, starting by restarting ReVanced Manager and ending the recording with showcasing the issue.

**Comment by SodaWithoutSparkles** [comment] 2023-05-02 01:35
Unfortunately it might not be easily reproduceable by everyone. This issue was reported by discord and reddit users separately. One of the recent threads in the support channel asked for help for this exact reason.

- [discord user 1](https://discord.com/channels/952946952348270622/1102765723123724309)
- [discord user 2](https://discord.com/channels/952946952348270622/1101883446537769050)

**Comment by oSumAtrIX** [comment] 2023-05-02 06:56
Probably a good thing for the future would be to add an announcement patch to the app. The way it would work is that on app start, it'll check a given API for an announcement and display it in a popup, so that on updates, they can be notified.

**Comment by AMSAMSAMSAMS** [comment] 2023-05-09 01:35
@oSumAtrIX how to disable this permanently?
Coz this always enabled by itself upon app restart....

**Comment by oSumAtrIX** [comment] 2023-05-09 01:51
Exclude the patch.

**Comment by AMSAMSAMSAMS** [comment] 2023-05-10 01:44
> Exclude the patch.

how? what switches so I need to put in the command line?

**Comment by n1cKz1** [comment] 2023-06-22 19:55
@oSumAtrIX thumbnail preview over the seekbar is broken again after yesterday's update

**Comment by n1cKz1** [comment] 2023-06-22 20:12
I'm one of the few fortunate ones to have never experienced the buffering issue (yet), so i don't need to turn it on, but the thing is when i disable it it usually just turns itself back on mid-video anyway

**Comment by n1cKz1** [comment] 2023-06-22 20:15
I doubt it, this behavior only started after yesterday's patches, i could disable it just fine before that

**Comment by n1cKz1** [comment] 2023-06-22 20:23
Welp looks like you are right. Seems like it auto enables in the forked version now as well, so i guess i officially joined the club.
Still a hell of a coincidence

**Comment by n1cKz1** [comment] 2023-06-24 01:19
I know the seekbar thumbnail issue is now listed as a side effect/limitation, that being said could a fix be possible in the future?

**Comment by Domiiniik** [comment] 2023-06-25 01:06
Will the seekbar issue recieve any kind of workaround fix or at least any attampt to fix it from the devs? This issue is sooo annoying now damn it. :( :(

**Comment by Domiiniik** [comment] 2023-06-25 01:13
One more thing: Download button in Old UI layouts shows up normally now and downloading videos seems to function propertly as well, so this side effect can now be crossed out or removed.

**Comment by oSumAtrIX** [comment] 2023-06-25 01:26
@Domiiniik I assume `Built in YouTube download feature sometimes does not work` will also work then?

**Comment by Domiiniik** [comment] 2023-06-25 01:35
I Have tested the download faature on my friends Premium account and it looks fine as of now. Hopefully seeking issue can be somehow more looked into by other devs as well, its the only huge problem right now and really noticable.

**Comment by Domiiniik** [comment] 2023-06-25 02:16
> It may or may not be possible to add seekbar thumbnails client side if the server does not specify to show thumbnails. I tried looking for the code that handles the seekbar thumbnails, but after an hour I could not find anything promising. YouTube is heavily obfuscate and finding any desired code can be very time consuming.
> 
> Can always pay for premium, and then spoofing is usually not required. If by chance someone lives in a cheap country like Turkey or India then premium is cheap. An unpopular opinion for broke users who want everything for free, but it is a solution.

Yeah sure but to be honest 50% out of 100% reVanced users are using it to get and enable most "Premium only" features features for free as they can't afford it or they don't have a credit card available.

**Comment by n1cKz1** [comment] 2023-06-25 21:00
Very nice, appreciate the effort

**Comment by oSumAtrIX** [comment] 2023-06-25 21:20
@LisoUseInAIKyrios Since we are spoofing the request to receive the video model that delivers both, the video stream as well as metadata such as the thumbnails, we would have to send two requests. One for playing the video and another for retrieving the metadata for the thumbnails. It may also be possible that both are retrieved separately. The response from our forget request might return data that is used to make another request to retrieve the thumbnails. This data might be able to be spoofed

**Comment by SodaWithoutSparkles** [comment] 2023-06-26 06:52
Would "sending 2 requests for a single video" be a detection method for spoofing signatures?

**Comment by SodaWithoutSparkles** [comment] 2023-06-26 10:12
I was refering to this part

> we would have to send two requests. One for playing the video and another for retrieving the metadata for the thumbnails. It may also be possible that both are retrieved separately.

**Comment by oSumAtrIX** [comment] 2023-06-26 10:17
Yes, sending the same request twice is not a viable solution. Instead the client should be spoofed properly.

**Comment by johnconner122** [comment] 2023-06-29 02:42
**Can't play Reels/Stories after latest update.**

![Screenshot_2023-06-29-07-39-46-482_app.revanced.android.youtube.jpg](https://github.com/revanced/revanced-patches/assets/107796137/e08a1f7d-8b6a-4b8a-bcab-c79081610175)

**Comment by Domiiniik** [comment] 2023-06-29 15:16
Any update on the seeking issue?

**Comment by alagga** [comment] 2023-07-06 10:22
Another issue I'm facing since 2-3 revanced updates:
Videos autoplayed in feed get automatically added to watch history.
Disabling signature spoofing resolved that.

**Comment by SodaWithoutSparkles** [comment] 2023-07-06 11:42
> Another issue I'm facing since 2-3 revanced updates:
> Videos autoplayed in feed get automatically added to watch history.
> Disabling signature spoofing resolved that.

I can reproduce the issue. I guess this is due to the way that the request was spoofed.

**Comment by xDARKxDEVILx** [comment] 2023-07-08 22:14
> @q1k the spoof was changed to fix playback issues (the old spoof method no longer works reliably)
> 
> (Is your profile picture a photo of yourself?)

Is it possible to bring back the old spoof as an option?as i didn't have any problem with it like many other users and now i regret updating ReVanced

**Comment by xDARKxDEVILx** [comment] 2023-07-08 22:19
> Yeah it could be a toggle to switch the prior spoof, with a default to use the latest more compatible mode (no seekbar preview)

Please do it if possible since it looks like this issue will last for quite some time like the others

**Comment by oSumAtrIX** [comment] 2023-07-08 22:27
An input box where the spoofed string can be entered would also work.

**Comment by n1cKz1** [comment] 2023-07-09 03:16
> Is it possible to bring back the old spoof as an option?

This would be great. I'm among those who have no playback issue with the old spoofing option, so not having to deal with the whole seekbar thumbnail not showing up thing would be nice. Also

> It may or may not be possible to force the client to fetch or locally generate the seekbar thumbnails. In usual YouTube fashion the responsible code involves many heavily obfuscated data objects with overly complex code control flow.
> At a minimum, fixing the chapter titles during seeking is possible.
More work is needed, but it looks halfway promising.

Any update on this?

**Comment by PalmDevs** [comment] 2023-07-17 05:00
> An input box where the spoofed string can be entered would also work.

How about a radio list option like the spoof version setting, but also have an option for a custom signature? That could be more friendly to users.

**Comment by oSumAtrIX** [comment] 2023-07-17 10:08
The text box solution allows for the maximum flexibility but is less straightforward than a list item that you can simply click. To prevent any mistakes, a reset button can be present

**Comment by SodaWithoutSparkles** [comment] 2023-07-17 12:06
I actually prefer a text field, because a hotfix could be issued to resolve any problems quickly by just telling users to replace the text. 

A good compromise would be 3 radio buttons: one for the old (v1) spoof, one for the new (v2) spoof, and one for a custom value. Then it would solve this once and for all. In case yet another spoof is needed, either add a new new (v3) spoof, or just use the custom value box.

**Comment by tusharsnn** [comment] 2023-07-17 12:17
Also it seems like a delay to on going problem. If there's any need to add a text box we can do it in follow up PR.

**Comment by SodaWithoutSparkles** [comment] 2023-07-17 22:06
The reason behind the text field (for me) are

1. revanced patches are slow to roll out
2. facilities a quicker debug process by asking volunteers with playback issues to test with the new value w/o repatch
3. dev branch is not (easily) available to normal users w/o cli
4. No need to repatch when spoof value changed, saving time

**Comment by trmdi** [comment] 2023-07-18 01:04
What about a textbox and some buttons below. Clicking on those buttons sets the textbox string and apply it ?

**Comment by oSumAtrIX** [comment] 2023-07-18 01:10
Tbf client spoof is still only a workaround yet to be patched by YouTube ASAP. There's no real benefit in using a textbox. Having a switch between "new" and "old" spoof should be good enough.

**Comment by oSumAtrIX** [comment] 2023-08-04 13:53
How about "Spoof client" matching the patch name? The description could give some more information, such as that it fixes playback. In case it is renamed, internal classes and identifiers should also be renamed accordingly.

**Comment by YT-Advanced** [comment] 2023-08-08 05:41
Today I have debugged and found a params. Can anyone test it ?
CA8wAg==

**Comment by YT-Advanced** [comment] 2023-08-08 08:25
> The spoofed value works and seekbar thumbnails show up (need to also remove the integration code that hides the seekbar thumbnail). But, my account does not have issues playing without spoofing. So I cannot verify if playback works correctly and someone else would need to try. (Or maybe this was already tried, which is why the comment is now deleted?)

Can you share the apk, my device have spoof error

**Comment by YT-Advanced** [comment] 2023-08-08 08:41
> If it's for reel_player, then it's another shorts spoof. Which means it may work for some users, but then fail for most others (video endlessly buffers around 1 minute mark)
> 
> You can try patching with [this](https://www.file.io/Agc2/download/i0toYRqtdRM4)

The file is deleted. I know about shorts spoof so I want to test this new parameter

**Comment by YT-Advanced** [comment] 2023-08-08 09:13
@LisoUseInAIKyrios Seem like it worked

**Comment by oSumAtrIX** [comment] 2023-08-08 09:15
The issue only appears after a couple of videos and minutes. Have you tested it extensively?

**Comment by YT-Advanced** [comment] 2023-08-08 09:16
> The issue only appears after a couple of videos and minutes. Have you tested it extensively?

Update, it not worked :))))

**Comment by YT-Advanced** [comment] 2023-08-16 07:47
I think Youtube have different encoder-decoder for thumbnail in incognito mode since the thumbnail can be used normally in Incognito mode. But now I have debugged and cannot found it lol

**Comment by inotia00** [comment] 2023-09-20 08:32
> While checking NewPipe's code, I found that NewPipe implemented a seekbar thumbnail preview

Some side effects may theoretically be fixable

I've organized it in the gist document and fork repo, anyone want to track the issue, please refer to it

https://gist.github.com/inotia00/e0dfd4c9682680821dbfb94668116afe
https://github.com/inotia00/revanced-patches/commit/6c5011ee24c277886aa680ddd9d44a9e4db3db3f
https://github.com/inotia00/revanced-integrations/commit/249f82c22fa9f763e940357d1ab80011ad322a5a

**Comment by oSumAtrIX** [comment] 2023-09-20 15:51
> In a test build that hooked the hard-coded StoryBoard URL

Which method was hooked?

**Comment by oSumAtrIX** [comment] 2023-09-20 17:55
I believe they extract it this way:

https://github.com/TeamNewPipe/NewPipeExtractor/blob/3be76a6406d59f1fd8eedf5fab6552e6c2a3da76/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L1057C13-L1057C56

**Comment by inotia00** [comment] 2023-09-20 22:57
> > In a test build that hooked the hard-coded StoryBoard URL
> 
> Which method was hooked?

refer this commit https://github.com/inotia00/revanced-patches/commit/ba9211ad739801c47928a47df3f8f217cc909c4c

**Comment by inotia00** [comment] 2023-09-25 06:42
fix for clip

https://github.com/inotia00/revanced-integrations/commit/6f36c858f96105461bd5ce881c40809b16497161

fix for ambient mode, filmstrip overlay, thumbnail preview in seekbar

https://github.com/inotia00/revanced-patches/commit/4eead50c70e1f254579877054dd86259872ad006

https://github.com/inotia00/revanced-integrations/commit/49d63c2dadda8eccf40342c895295b0c5d63aa75


I tried to leave as many comments as possible and made minimal modifications from the official source

since the fetch API is finished before the PlayerResponse is generated by YouTube, bottlenecks are not expected to occur, but limit it to volatile or synchronized if necessary

quality of the seekbar thumbnail preview is very low, so it seems to separate patch is needed for this in the class that handles the storyboards
(It would be nice to see who implemented the alternative thumbnail patch)

**Comment by oSumAtrIX** [comment] 2023-09-25 14:33
@LisoUseInAIKyrios See https://github.com/ReVanced/revanced-integrations/compare/bfae6b56ab0f...2cd1738d2494

**Comment by oSumAtrIX** [comment] 2023-09-25 19:49
I have locally implemented a way to display the thumbnail with the highest quality. I'll push it in some minutes, once I have refactored it.

**Comment by oSumAtrIX** [comment] 2023-09-25 21:51
Here is the fix https://github.com/ReVanced/revanced-patches/commit/5e8a2d3fe77a4a08ea32e7dc22f2c8e4048b7a6b

**Comment by xDARKxDEVILx** [comment] 2023-09-25 21:55
Damn, it feels so good seeing 11 out of 13 finally, thanks to everyone working on this 🙂

**Comment by oSumAtrIX** [comment] 2023-09-25 21:57
All should be fixed now

**Comment by johnconner122** [comment] 2023-09-28 13:03
> All should be fixed now

It fails to load thumbnail if video more than an `Hour` long. e.g; https://www.youtube.com/live/ZUXEviR5TmI?si=rq5VClc-05kwbvK1

**Comment by oSumAtrIX** [comment] 2023-09-28 13:26
Makes sense, I was specifically trying 1 hour long videos that were not live streams, so that worked for me.

**Comment by Qaz-6** [comment] 2023-09-28 13:39
Finally all the features will work normally, and there will be no video freezing problems?🤔

**Comment by GKid94** [comment] 2023-09-30 22:25
I have bad live stream quality when the spoof option is enabled
![Screenshot_2023-10-01-00-23-04-470_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/122dc943-f897-4f0c-9915-dc1607f935c9)
![Screenshot_2023-10-01-00-23-08-719_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/fa3adb58-f5f3-4c71-b5d2-e2a4676aa543)
![Screenshot_2023-10-01-00-23-28-071_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/fa12b8bf-0e48-49a1-826b-9165883f1988)

**Comment by GKid94** [comment] 2023-09-30 23:24
> @GKid94 you have the quality set to automatic, and YouTube will pick whatever quality it wants.
> 
> Set a default quality in `Settings -> ReVanced -> Video`

I have a good connection

**Comment by SodaWithoutSparkles** [comment] 2023-10-01 05:13
> I have a good connection 

Doesn't stop youtube being funky at times. Maybe they just wanna cheap out on bandwidth and hope that you did not notice.

**Comment by GKid94** [comment] 2023-10-01 12:53
> > I have a good connection
> 
> Doesn't stop youtube being funky at times. Maybe they just wanna cheap out on bandwidth and hope that you did not notice.

YouTube is getting worse and worse 😕

**Comment by johnconner122** [comment] 2023-10-04 10:38
I have been buffering issues for a few days now after playing a video after a minute or two. 
It started after or with following changes. 
> StoryboardRenderer error toast was fixed just a few minute ago. 

If I use previous releases code, before above mentioned fix, it works fine without any buffering issues.

**Comment by oSumAtrIX** [comment] 2023-10-04 12:27
@LisoUseInAIKyrios They were using dev patches which had a bug with the hooks not being properly added to the app. This was fixed a day after, so repatching will work around the playback issue once again as supposed

**Closed** 2023-10-04 23:37 UTC
Labels: Bug

**Comment by xDARKxDEVILx** [comment] 2023-10-04 23:46
It only took 6 months and 20 days to close this issue XD

**Comment by Qaz-6** [comment] 2023-10-05 12:23
![Screenshot_20231005-161802_YouTube](https://github.com/ReVanced/revanced-patches/assets/140435478/c53c4b74-8821-4a5b-8708-eca47a48178a)
Did you forget to delete it? Or is one still working and the other not working?

**Comment by oSumAtrIX** [comment] 2023-10-05 12:26
Not sure what you mean, but you disabled the patch.

**Comment by Qaz-6** [comment] 2023-10-05 12:30
Some features don't work when this patch is on. Video playback issues when it's off. What's a better solution to have both?

**Comment by Qaz-6** [comment] 2023-10-05 12:40
In this case, we should remove the side effects. People should not be confused

**Comment by xDARKxDEVILx** [comment] 2023-10-05 12:44
> In this case, we should remove the side effects. People should not be confused

What? Just read the side effects when it is enabled, we can't just remove them

**Comment by Qaz-6** [comment] 2023-10-05 13:01
Is YouTube's paid videos policy back?😏
Damn it
