### ISSUE TITLE
Youtube Music ReVanced doesn't start on Android Auto

### ISSUE THREAD

**Issue by Shir0a** [revanced/revanced-patches#328] opened 2022-08-11 02:17 UTC
### Type

Error at runtime

### Bug description

Attempting to open Youtube Music Revanced from Android Auto throws the error "Youtube ReVanced doesn't seem to be working right now". Also causes playback happening from the host Android device to stop.

### Steps to reproduce

Attempting to launch Youtube Music ReVanced from any Android Auto interface. Occurs both with physical devices as well as Android Auto Emulator Desktop Head Unit. 
Tested with versions: 5.17.51, 5.16.54
Patches applied:
Minimized Playback Music
TasteBuilder Remover
Upgrade Button Remover
Background Play
Music Video Ads
Codecs Unlock
Exclusive Audio Playback

### Relevant log output

```shell
08-10 20:56:50.315  2132  2214 D DisplayManagerService: Delivering display event: displayId=0, event=4
08-10 20:56:50.316 21790 21790 W YT.MDX.zlt: CastAppId for type 0 not found. Defaulting to mainCastAppId.
08-10 20:56:50.316  7514  7528 D AudioManagerExtImpl: getStreamVolume packageName=com.pandora.android, index=12, streamType=3
08-10 20:56:50.318 21790 21909 E DynamiteModule: Invalid GmsCore APK, remote loading disabled.
08-10 20:56:50.318 22822 22822 D AudioManagerExtImpl: getStreamVolume packageName=com.spotify.music, index=12, streamType=3
08-10 20:56:50.319  4505  4528 D OplusAtlasService: getAttributeByAppName module:oplus-getStreamMaxVolume packageName:com.spotify.music
08-10 20:56:50.319  2132  2982 D OplusBrightUtils: ---> setBrightnessNoAnimation false
08-10 20:56:50.320  1304  1467 I SmoothBrightness: setBrightness:1435(-1)
08-10 20:56:50.320 22822 22822 D AudioManagerExtImpl: getStreamVolume packageName=com.spotify.music, index=12, streamType=3
08-10 20:56:50.320  1160  1516 D IRIS_LOG_SERV: setDisplayBrightness ret=0
08-10 20:56:50.321  4505  4528 D OplusAtlasService: getAttributeByAppName module:oplus-getStreamMaxVolume packageName:com.spotify.music
08-10 20:56:50.321 21067 23520 D GmsServiceBroker: Service not supported: GetServiceRequest{serviceId=UNKNOWN(161), gmsVersion=222980000, packageName='app.revanced.android.apps.youtube.music', extras=Bundle[EMPTY_PARCEL]}
08-10 20:56:50.321  1160  1570 D IRIS_LOG_COLR: Use kPbGamut HwConfigPayload
08-10 20:56:50.321 21790 21877 W GmsClient: IGmsServiceBroker.getService failed
08-10 20:56:50.321 21790 21877 W GmsClient: java.lang.IllegalArgumentException: Service not supported: 161
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2445)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Parcel.createException(Parcel.java:2425)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Parcel.readException(Parcel.java:2408)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Parcel.readException(Parcel.java:2350)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at ody.D(PG:15)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at obi.run(PG:5)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Handler.handleCallback(Handler.java:938)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Looper.loopOnce(Looper.java:233)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.Looper.loop(Looper.java:344)
08-10 20:56:50.321 21790 21877 W GmsClient: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-10 20:56:50.322  1160  1570 D IRIS_LOG_SERV: send panel async brightness: 53
08-10 20:56:50.325  7514  7528 D AudioManagerExtImpl: getStreamVolume packageName=com.pandora.android, index=12, streamType=3
08-10 20:56:50.325  2132  2295 D OplusDisplayPowerControllerExtImpl: original brightness to dataBase:1379 final brightness:1009.0 scale:0.7321136 reason:4 darkLevel:2
08-10 20:56:50.325  2132  2295 D DisplayPowerController[0]: Animating brightness: target=1009.0, rate=104.0, source= 7
08-10 20:56:50.325 22822 22822 D AudioManagerExtImpl: getStreamVolume packageName=com.spotify.music, index=12, streamType=3
08-10 20:56:50.325  2132  2295 D VRR [OPlusRefreshRateService]: notifyBrightnessChange brightness: 1009.0
08-10 20:56:50.326  4505  4528 D OplusAtlasService: getAttributeByAppName module:oplus-getStreamMaxVolume packageName:com.spotify.music
08-10 20:56:50.326  2132  2214 D DisplayManagerService: Delivering display event: displayId=0, event=4
08-10 20:56:50.326  7514  7528 D AudioManagerExtImpl: getStreamVolume packageName=com.pandora.android, index=12, streamType=3
08-10 20:56:50.327 22822 22822 D AudioManagerExtImpl: getStreamVolume packageName=com.spotify.music, index=12, streamType=3
08-10 20:56:50.328  4505  4528 D OplusAtlasService: getAttributeByAppName module:oplus-getStreamMaxVolume packageName:com.spotify.music
08-10 20:56:50.329 21790 21909 W DynamiteModule: Local module descriptor class for com.google.android.gms.cast.framework.dynamite not found.
08-10 20:56:50.330 22822 22822 D AudioManagerExtImpl: getStreamVolume packageName=com.spotify.music, index=12, streamType=3
08-10 20:56:50.330  4505  4528 D OplusAtlasService: getAttributeByAppName module:oplus-getStreamMaxVolume packageName:com.spotify.music
08-10 20:56:50.331 22822 22822 D AudioManagerExtImpl: getStreamVolume packageName=com.spotify.music, index=12, streamType=3
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: Error fetching CastContext.
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: nnj: olq: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at noe.d(PG:7)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at nmd.<init>(PG:12)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at nmb.call(PG:2)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at qay.run(PG:1)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at akxe.run(PG:1)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at akxf.run(PG:4)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at qtu.run(PG:1)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at quf.run(PG:23)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at qsw.run(PG:2)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at qtg.run(PG:4)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: 	at java.lang.Thread.run(Thread.java:920)
08-10 20:56:50.331 21790 21790 E YT.MDX.CastSdkClient: Caused by: olq: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
```

### Screenshots or videos

![desktop-head-unit_amcgaIXSwh](https://user-images.githubusercontent.com/111030408/184053914-39894d77-0c3c-4663-aee7-19834497e290.png)

**Comment by cdamman** [comment] 2022-09-12 22:38
Same issue with version 5.22.54

**Comment by pacho2** [comment] 2022-09-24 12:25
This looks like a dupe of https://github.com/revanced/revanced-patches/issues/305

**Closed** 2022-09-24 12:26 UTC
Labels: bug
