### ISSUE TITLE
bug: you always get a notification while playing videos 

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-patches#2257] opened 2023-05-25 13:10 UTC
### Type

Error at runtime

### Bug description

While using the last recommended version and the one before it i get the player notification while watching videos not in background instead of only when in background like it used to be and should be, what is the point of controlling the video from the notification while you can control it from the video as normal 

### Steps to reproduce

Just correctly patch yt revanced 

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-05-25 13:42
Check on stock YouTube.

**Comment by EhabxAlaa** [comment] 2023-05-25 14:06
> Check on stock YouTube.

I don't have premium so i shouldn't get the player notification anyway but i will check

**Comment by EhabxAlaa** [comment] 2023-05-25 14:08
Yeah stock is fine

**Comment by oSumAtrIX** [comment] 2023-05-25 15:11
Please record the issue. Include showing that it works on YouTube and doesn't in the patched app

**Comment by EhabxAlaa** [comment] 2023-05-25 15:15
> Please record the issue. Include showing that it works on YouTube and doesn't in the patched app

How do i record it on YouTube? By just simply playing a video and having no notification and record YouTube Revanced while playing a video and having a notification, is that correct?

**Comment by EhabxAlaa** [comment] 2023-05-25 15:16
But as i said before I can't have the issue in stock as i don't have premium and i won't get the player notification in ReVanced if i don't turn on background play

**Comment by EhabxAlaa** [comment] 2023-05-25 15:33
https://github.com/revanced/revanced-patches/assets/120474122/ceef01cf-922a-4209-a3b1-80668bed1aad

This is the patched one i will record the unpatched one now

**Comment by EhabxAlaa** [comment] 2023-05-25 15:37
https://github.com/revanced/revanced-patches/assets/120474122/6dc2eef0-8997-4287-b073-44d1b14794e2

And here is the same video on unpatched YouTube

**Comment by oSumAtrIX** [comment] 2023-05-25 16:06
Did you enable PIP in unpatched app

**Comment by EhabxAlaa** [comment] 2023-05-25 17:09
> Did you enable PIP in unpatched app

No, you can't even do that without "PREMIUM"

**Comment by EhabxAlaa** [comment] 2023-05-25 21:26
> Did you enable PIP in unpatched app

Will you kindly reply? At least tell me if i should do anything or leave it to you guys

**Comment by oSumAtrIX** [comment] 2023-05-25 21:33
> > Did you enable PIP in unpatched app
> 
> No, you can't even do that without "PREMIUM"

This is why it does not appear on the unpatched app. You need premium to test it on the unpatched app. Closing until then because I am sure it is stock behavior, reopen if otherwise.

**Closed by oSumAtrIX** 2023-05-25 21:33 UTC
Labels: bug, waiting on author

**Comment by EhabxAlaa** [comment] 2023-05-25 21:35
> > > Did you enable PIP in unpatched app
> > 
> > 
> > No, you can't even do that without "PREMIUM"
> 
> This is why it does not appear on the unpatched app. You need premium to test it on the unpatched app. Closing until then because I am sure it is stock behavior, reopen if otherwise.

If it is stock do i try with an old version like 18.15.40?

**Comment by oSumAtrIX** [comment] 2023-05-25 21:39
You can do that but you need to test on unpatched app with same version too.

**Comment by EhabxAlaa** [comment] 2023-05-25 21:40
> You can do that but you need to test on unpatched app with same version too.

Sure but if were able to get it to work on the patched one, that will confirm it is stock issue

**Comment by EhabxAlaa** [comment] 2023-05-25 21:42
Soooo  18.15.40 isn't supported anyone, currently there is only two supported versions, but i will try it anyway with just minimum patches

**Comment by EhabxAlaa** [comment] 2023-05-25 21:44
Not even MicroG is supported for 18.15.40, i guess half the issues i post here are stock issues that never get fixed , thanks google

**Comment by EhabxAlaa** [comment] 2023-05-25 22:12
Can you test it on your side? It is pretty easy to test and you definitely have an account with premium

**Comment by EhabxAlaa** [comment] 2023-05-25 22:12
And sorry for the dumb question but can you fix YouTube  bugs or alter the code? Can you tell me what you can and can't do? such information will be helpful to me as i am studying this career

**Comment by oSumAtrIX** [comment] 2023-05-25 22:44
You can modify every single bit of an application.

**Comment by EhabxAlaa** [comment] 2023-05-25 22:49
> You can modify every single bit of an application.

So why don't you fix YouTube bugs when you figure out it is on their side? 
Is it because it is difficult to know where or/and how to fix it since you didn't write that code? 
If i am bothering you with questions please let me know and i will shut up 🙂

**Comment by oSumAtrIX** [comment] 2023-05-25 23:16
It is not a bug on YouTube's end; if it were, it is their responsibility to fix it. The same question can be asked: why don't you reverse-engineer the app and fix the bugs?
