### ISSUE TITLE
Crashed when tapping live chat button

### ISSUE THREAD

**Issue by Nonanne** [revanced/revanced-patches#957] opened 2022-11-02 22:48 UTC
### Type

Error at runtime

### Bug description

App crashed when I tapping live chat button in **Fullscreen display**

> working fine in live chat near like/dislike button (in half-screen mode)

Devices: Xiaomi (Android 10)
Version: 17.43.36

### Steps to reproduce

.

### Relevant log output

```shell
//don't know
```

### Screenshots or videos

![Screenshot_2022-11-03-05-40-42-681_app revanced android youtube_edit](https://user-images.githubusercontent.com/94383254/199616773-c87be2b5-aede-42e8-a37d-145a4dcca035.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-11-02 23:02
Disable patches until the error is gone, report back which one causes it.

**Comment by shion5425550** [comment] 2022-11-02 23:54
dupe of #904

**Closed** 2022-11-03 00:20 UTC
Labels: bug, question

**Comment by kyan5221** [comment] 2022-11-03 02:46
> Disable patches until the error is gone, report back which one causes it.

I've deselected 'Hide Autoplay Button' in patch list and it's OK when I tab Chat button in fullscreen.
but Chat panel is shown only when I enable 'Show fullscreen panels' in 'Layout' menu.
