### ISSUE TITLE
bug: phone strucks on youtube only.

### ISSUE THREAD

**Issue by darknoob786** [revanced/revanced-patches#323] opened 2022-08-09 11:55 UTC
### Type

Other

### Bug description

I tried all revanced versions by different people. There is one mazor bug in all of them. When I watch videos on full screen, and try to open wifi settings and after that i return to youtube, youtube works fine but all gesture navigations stop  working. I am unable to go to home screen, back, or recent apps or open any other app. Last option left is to reboot the phone.

### Steps to reproduce

Open YouTube. Watch any video. 
Switch to full screen.
Open notification panel. Hold on wifi icon and go to wifi settings.
Return to youtube. 
Bang! Your phone will just struck on youtube. You can't close or go back to home screen.
Last option to do reboot your device.
My phone - realme x7 5g
Android 12 RMUI 3.0

### Relevant log output

```shell
Cant capture
```

### Screenshots or videos

Video link-https://file2directlink.herokuapp.com/78606741586417058985700588/AgADEQUA/video_2022-08-09_11-47-49_.mp4

**Comment by oSumAtrIX** [comment] 2022-08-09 12:05
https://user-images.githubusercontent.com/13122796/183642710-effc4492-141b-4f93-a709-067a8591af5c.mp4

**Comment by oSumAtrIX** [comment] 2022-08-09 12:05
Reproduction steps do not work.

**Comment by darknoob786** [comment] 2022-08-09 12:13
May be, this issue occuring in realme UI 3.0 only.  But i tried so many revanced versions. And facing this common issue in all of them

**Comment by oSumAtrIX** [comment] 2022-08-09 12:34
Disable patches until the error is gone, report back which one of them causes the issue.

**Comment by darknoob786** [comment] 2022-08-09 12:58
I am not that pro😑

**Comment by oSumAtrIX** [comment] 2022-08-09 13:00
I'll leave this open for a considerate amount of time for someone else to report, reproduce and report the faulty patch until I close it.

**Comment by EatVanced** [comment] 2022-08-11 07:12
Seems like PIP issue, try it with stock Youtube app and try it.

**Comment by EatVanced** [comment] 2022-08-11 11:03
The video link is expired, can you turn off PIP and try again? @darknoob786

**Comment by darknoob786** [comment] 2022-08-12 02:25
Yes brother. It is PIP issue. When i turned off PIP, issue gone. But after turning on PIP again, issue occurs again.

https://www.dropbox.com/s/fk6myfyijljqurx/VID_20220812_075116_389.mp4?dl=0

**Comment by oSumAtrIX** [comment] 2022-08-12 02:27
Looks like a phone issue, have you tried on regular YouTube?

**Comment by darknoob786** [comment] 2022-08-12 03:07
Yes. In stock youtube, it's Functioning properly.

**Comment by oSumAtrIX** [comment] 2022-08-12 03:08
> Yes. In stock youtube, it's Functioning properly.

Can you record it?

**Comment by darknoob786** [comment] 2022-08-12 04:02
https://www.dropbox.com/s/bzuazu2yfin7lwr/Record_2022-08-12-09-26-30.mp4?dl=0

**Comment by EatVanced** [comment] 2022-08-12 05:06
> https://www.dropbox.com/s/bzuazu2yfin7lwr/Record_2022-08-12-09-26-30.mp4?dl=0

If you can, test it with PIP enabled on Stock Youtube. 
PIP is maintained by Youtube and your phone vendor.

**Comment by EatVanced** [comment] 2022-08-12 05:12
https://user-images.githubusercontent.com/100286130/184288810-d6c9089e-3da4-4f91-ad0a-9971da20b549.mp4

cannot reproduce with realme ui 3.0

**Comment by EatVanced** [comment] 2022-08-12 05:18
PIP issue cannot be fixed, you need to report it to Youtube or your phone vendor.
it's improbable for ReVanced to fix this

**Comment by oSumAtrIX** [comment] 2022-08-12 12:10
Try disabling all other patches except background playback and check if it still causes this issue.

**Comment by darknoob786** [comment] 2022-08-12 12:20
Brother PIP  is causing issue. Close this issue now. May be it's the problem of my phone.

**Comment by oSumAtrIX** [comment] 2022-08-12 12:22
If it were a problem with your phone then it should've not worked on YouTube too, disable all paches except PiP and check if the error still happens, if so please record it.

**Comment by darknoob786** [comment] 2022-08-12 12:27
Brother i don't know how to disable patches. I am noob.

**Comment by oSumAtrIX** [comment] 2022-08-12 12:28
So how did you disable PiP before to confirm it's a PiP issue?

**Comment by darknoob786** [comment] 2022-08-12 12:35
![IMG_20220812_180348](https://user-images.githubusercontent.com/52814742/184354979-f39df5ca-ca40-48bf-a952-dcc305ecf889.jpg)

**Comment by oSumAtrIX** [comment] 2022-08-12 12:37
Thos version of YouTube is not supported yet, try on the latest version supported by excluding all patches except background playback.

**Comment by darknoob786** [comment] 2022-08-12 12:41
This is the most stable version of revanced that i have tried so far. Can you pls share link of any stable version?

**Comment by oSumAtrIX** [comment] 2022-08-12 12:42
We don't provide prepatched applications. Follow the wiki on how to build it.

**Comment by darknoob786** [comment] 2022-08-12 17:47
Bro i patched without pip and it works but i am unable to play videos in background now.

**Comment by oSumAtrIX** [comment] 2022-08-12 18:10
Will havw to wait for someone else to also report this issue.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-13 07:22
Do we really have to though?

**Comment by oSumAtrIX** [comment] 2023-02-13 13:09
Nobody else is reporting any similar issue

**Closed by oSumAtrIX** 2023-02-13 13:09 UTC
Labels: bug, question
