### ISSUE TITLE
feat(patch): custom-branding patch for YouTube Music

### ISSUE THREAD

**Issue by jumbooopc** [revanced/revanced-patches#812] opened 2022-10-19 07:54 UTC
### Application

YouTube Msuic

### Issue

`custom-branding` patch for YouTube Music.

### Patch

Adds ability to _include_ or _exclude_ `custom-branding` patch when building YouTube Music ReVanced.

### Motivation

- Some users [most of them] don't like the name “YouTube Music ReVanced” because it's so long in the launcher.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment] 2022-10-19 07:57
> ### Application
> YouTube Msuic
> 
> ### Issue
> `custom-branding` patch for YouTube Music.
> 
> ### Patch
> Adds ability to _include_ or _exclude_ `custom-branding` patch when building YouTube Music ReVanced.
> 
> ### Motivation
> * Some users [most of them] don't like the name “YouTube Music ReVanced” because it's so long in the launcher.
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new and no duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I filled out all of the requested information in this issue properly.

This behaviour can be achieved by using "-e custom-branding" in ReVanced CLI or by simply not selecting the patch in ReVanced Manager

**Comment by jumbooopc** [comment] 2022-10-19 16:24
@vasile-coste And also **not available** in ReVanced CLI.
`java -jar revanced-cli-2.14.0-all.jar -a music.apk -c -m app-release-unsigned.apk -o music-revanced.apk -b revanced-patches-2.83.1.jar -e custom-branding`
After building process, the app name still “YouTube Music ReVanced”.

**Comment by jumbooopc** [comment] 2022-10-19 16:28
> This behaviour can be achieved by using "-e custom-branding" in ReVanced CLI or by simply not selecting the patch in ReVanced Manager

Yes, this patch is in YouTube patches, but not in YouTube Music ones.
So the issue is supposed to remain open...

**Comment by Ushie** [comment] 2022-10-19 20:04
> > This behaviour can be achieved by using "-e custom-branding" in ReVanced CLI or by simply not selecting the patch in ReVanced Manager
> 
> Yes, this patch is in YouTube patches, but not in YouTube Music ones. So the issue is supposed to remain open...

You're correct, that was my bad

this issue will stay open until a custom-branding patch has been made for YTM to separate it from the MicroG patch

**Comment by AMSAMSAMSAMS** [comment] 2022-10-20 01:45
This is duplicate of mine: #451

**Closed** 2022-10-20 04:23 UTC
Labels: patch-request
