### ISSUE TITLE
Critical bug: <App doesn't start>

### ISSUE THREAD

**Issue by Ansh4011** [revanced/revanced-patches#872] opened 2022-10-27 12:07 UTC
### Type

Error at runtime

### Bug description

The `Hide-Shorts-Button` patch doesn't let me launch the app for the latest version of the patches (`v2.92.1`). The app just crashes as soon as I try to launch it. Excluding the shorts patch while patching is the only solution for that. Also, I have this problem since patch `v2.83.2` so you know what commits might have some problem.
Have spent half of my day to find the problem, so I really expect a response :).
Thanks!

### Steps to reproduce

1. Patch yt v17.36.37 with the latest version of patches (v2.92.1)
2. Remember to select all patches (ofc. except enable debugging)
3. The app won't launch (atleast it doesn't launch for me).

### Relevant log output

```shell
-
```

### Screenshots or videos

-

### Solution

-

### Additional context

Android Version- Android 10
Rom- Miui 12
Youtube Version- 17.36.37

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-10-27 12:13
Dupe of #412.

**Closed by oSumAtrIX** 2022-10-27 12:13 UTC
Labels: bug

**Comment by Ansh4011** [comment] 2022-10-27 12:18
> Dupe of #412.

It's an error while runtime, no error while patching.

**Comment by oSumAtrIX** [comment] 2022-10-27 12:21
Please record patching the app.

**Comment by Ansh4011** [comment] 2022-10-27 12:23
> Please record patching the app.

![image](https://user-images.githubusercontent.com/84930340/198283214-1ea14138-c736-4490-985d-a360c5490e30.png)
There you go.

**Comment by Ansh4011** [comment] 2022-10-27 13:41
@oSumAtrIX Bro any update?

**Comment by Aldo97** [comment] 2022-10-27 14:14
I'm using revanced-builder on termux and I can confirm that including Hide-Shorts-Button cause a crash on launch.
YouTube version 17.36.37 (downloaded by revanced-builder) and latest patches (2.92.2)

**Comment by Ansh4011** [comment] 2022-10-27 14:15
Once I get back to home, I'll try the manager as well.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Aldo97** [comment] 2022-10-27 14:47
Built by the manager it works

**Comment by Ansh4011** [comment] 2022-10-27 21:58
Yeah it does for me too. Guess I need to post an issue for builder. Anyways, thx oSumAtrIX and Aldo97.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
