### ISSUE TITLE
feat: 'Search Bar' in the 'YouTube ReVanced Settings' menu to search for settings by title/description/patch

### ISSUE THREAD

**Issue by ChaliceChore** [ReVanced/revanced-patches#3227] opened 2024-05-24 09:14 UTC
### Feature description

A search bar (similar to the wide search bar of the YouTube) should be present at the top of the 'YouTube ReVanced Settings' menu in the settings section of the YouTube Revanced app to search for patches by name/description/keywords.

### Motivation

YouTube ReVanced app offers multitudes of settings/patches to exponentially enhance user experience.
However, it is becoming exceeedingly difficult to sift through the various pages of the ReVanced settings. I felt this for the first time when I was setting up ReVanced on my new phone and could not find the setting to turn off the New Launching splash/animation (why has it been turned On by default? So many hours worth of cumulative time is being wasted by this setting alone). I did eventually find the relevant setting. However, I faced this problem again while looking for some other setting.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Bceez** [comment] 2024-05-24 09:16
Duplicate of https://github.com/ReVanced/revanced-patches/issues/819

**Closed** 2024-05-24 09:18 UTC
Labels: Feature request
