### ISSUE TITLE
bug: pull down to refresh not working

### ISSUE THREAD

**Issue by UmRAtEJvgLtH** [revanced/revanced-patches#348] opened 2022-08-17 22:26 UTC
### Type

Other

### Bug description

When General layout ad removal is enabled, pull down to refresh no longer works on the home screen.

When Community post removal is enabled, pull down to refresh is no longer working on the subscriptions screen

### Steps to reproduce

1. Goto settings
2. Go to Revanced Settings
3. Go to AD settings
4. Toggle General layout removal and/or Community Post removal

### Relevant log output

```shell
.
```

**Comment by oSumAtrIX** [comment] 2022-08-17 22:27
Dupe of https://github.com/orgs/revanced/discussions/264.

**Closed by oSumAtrIX** 2022-08-17 22:27 UTC
Labels: bug
