### ISSUE TITLE
Bug: youtube ads after upgrade (2.81.7)

### ISSUE THREAD

**Issue by DaniAndTheWeb** [revanced/revanced-patches#756] opened 2022-10-10 18:50 UTC
## Type

Cosmetic

Bug description

After upgrading from 2.81.2 to version 2.81.7 youtube started showing some ads in the videos

## Steps to reproduce

Install 2.81.7 youtube patches coming from 2.81.2.

## Relevant log output

No logs

## Solution

No response

## Acknowledgements

- [x]   I have searched the existing issues and this is a new and no duplicate or related to another open issue.

- [x]   I have written a short but informative title.

- [x]   I filled out all of the requested information in this issue properly.

**Comment by udoxi** [comment] 2022-10-10 19:10
YouTube Video Ads are still there after latest patch.

**Comment by Enivex** [comment] 2022-10-10 19:25
I suspect the issue is that the option was inverted without changing the text

https://github.com/revanced/revanced-patches/commit/a32af951566a7187ae2618ef08f9298f78f8ea8c

Try turning the toggle off instead of on.

**Comment by oSumAtrIX** [comment] 2022-10-10 19:29
@Enivex That might be it. In that case, the commit will be reverted.

**Comment by DaniAndTheWeb** [comment] 2022-10-10 19:31
I did it and also cleared the app data.
There are just a few ads showing, not even close to the app without patches, but they are still there.

**Comment by oSumAtrIX** [comment] 2022-10-10 20:21
Fixed in commit e353ed0b0fe78feae65f1ad2f6567c1e9aa9c71d.

**Closed by oSumAtrIX** 2022-10-10 20:21 UTC
