### ISSUE TITLE
bug(YouTube): `spoof-client(iOS)` abnormal timestamps in a very small percentage of video

### ISSUE THREAD

**Issue by 7Grn** [ReVanced/revanced-patches#3500] opened 2024-08-03 10:50 UTC
### Bug description

the timestamps are broken(?) in this video.
<https://www.youtube.com/watch?v=Sqr-PdVYhY4>
when using the iOS spoof, the video is over 20 minutes long, but only seems to play for 50 sec.
As far as I know, this phenomenon seems to occur only in this video on this channel
![Screenshot_2024-08-03-02-14-10-757](https://github.com/user-attachments/assets/0d6c804f-134c-4237-83eb-e135d9feec43)
![Screenshot_2024-08-03-02-14-15-132](https://github.com/user-attachments/assets/be36fff4-0ddc-4391-b576-658688fd3b72)

### Solution

now timestamps are normal when using Android-VR spoof (or when the spoof-client option is disabled)
![_20240803_105234](https://github.com/user-attachments/assets/a79b802b-ec4a-409e-8316-bf389232b831)
i mean not a recommended workaround, but a report

### Additional context

https://discord.com/channels/952946952348270622/1135563848586379264/1269192139070509198 (ReVanced)
sorry, i'm not the one who discovered this phenomenon
i saw someone claiming it on Discord, tried it and was able to reproduce it

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2024-08-03 11:11
Stats for nerds shows a unusually long string for the audio format too

**Comment by 7Grn** [comment] 2024-08-03 12:09
![_20240803_120756](https://github.com/user-attachments/assets/0c3ec680-e920-4089-a74b-a7c40069d889)
![_20240803_120704](https://github.com/user-attachments/assets/5b9900b0-ed16-43a0-9ddd-d5eb61e6a3d1)

**Comment by 0xrxL** [comment] 2024-08-04 03:33
I can't reproduce the bug on the same video.

![Screenshot_20240804_053202](https://github.com/user-attachments/assets/be35ad77-be5c-40cb-976a-d7c7f0c3a41e)

Probably this problem has been fixed by user agent spoofing.

**Comment by oSumAtrIX** [comment] 2024-08-04 08:06
Same on my end

**Closed by oSumAtrIX** 2024-08-04 08:06 UTC
Labels: Bug report

**Comment by 7Grn** [comment] 2024-08-04 19:08
i have just tried it and it now plays with normal timestamps even during iOS spoof, even in my environment
![_20240805_000000](https://github.com/user-attachments/assets/b4d7546b-fc30-4527-8c35-b5cdaf929bbc)
[iOS.txt](https://github.com/user-attachments/files/16488647/iOS.txt)
thank you all very much
