### ISSUE TITLE
bug: 17.41.37 support bug,video ads patch doesn't work

### ISSUE THREAD

**Issue by Domiiniik** [revanced/revanced-patches#885] opened 2022-10-28 05:45 UTC
### Type

Other

### Bug description

Video ads still show up even through the video ads patch is included and enabled in settings (only in 17.41.37

### Steps to reproduce

Patch 17.41.37 with video ads patch and see if ads are still present, they should be and they are in my case.

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20221028-074455_YouTube](https://user-images.githubusercontent.com/30195961/198512070-fd66eb03-0a0c-4789-95c7-c8deaddb6193.png)

### Solution

-

### Additional context

-

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by shion5425550** [comment] 2022-10-28 06:03
dupe of #881

**Comment by Fosssil** [comment] 2022-10-28 06:38
I also got it

**Comment by Emilza07** [comment] 2022-10-28 06:48
Me too(

**Comment by introversialscalpel** [comment] 2022-10-28 07:05
Patched 17.36.361 with same patches as 17.41.37 and didn't get any bugs, so maybe some patches failed to work in 17.41.37.

**Comment by Ansh4011** [comment] 2022-10-28 08:10
Same pinch.

**Comment by OxrxL** [comment] 2022-10-28 08:19
You have to have some patience. I didn't fixed this patch because a particular fix (wich doesn't affect buffering) for video ads is being added by oSum.

if this doesn't happen soon, I will discuss it with him and fix the current fingerprint (as I already did yesterday).

**Comment by Ansh4011** [comment] 2022-10-28 08:32
No worries buddy, take your time!

**Comment by Fosssil** [comment] 2022-10-28 09:50
> You must have some patience. I didn't fixed this patch because a particular fix (wich doesn't affect buffering) for video ads is being added by oSum.
> 
> if this doesn't happen soon, I will discuss it with him and fix the current fingerprint (as I already did yesterday).

We will wait, mate ✌️

**Closed** 2022-10-28 10:04 UTC
Labels: bug
