### ISSUE TITLE
bug: Subscribe button missing

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3188] opened 2023-10-24 02:34 UTC
### Bug description

The subscribe button is not showing
![277513582-820c5238-d0ba-4f64-9a20-ecc4becb5dcb](https://github.com/ReVanced/revanced-patches/assets/18757054/9ca22ce0-7dd5-492d-86bb-240dfb8bd17d)
![Screenshot_2023-10-24-04-29-03-382_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/8e7c978f-de84-4e0b-a5a2-642e3f7865a4)
![Screenshot_2023-10-24-04-28-59-737_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/dbfb607d-b8e9-4a89-8526-9fe04abdf36a)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment] 2023-10-24 03:28
I believe this was already fixed after it was reported in https://github.com/ReVanced/revanced-patches/issues/3111

Please update with the latest patches and close this if the issue is no longer present.

**Closed** 2023-10-24 04:51 UTC
Labels: Bug report

**Comment by GKid94** [comment] 2023-10-25 02:30
> I believe this was already fixed after it was reported in #3111
> 
> Please update with the latest patches and close this if the issue is no longer present.

Can you show the button by default?

**Comment by oSumAtrIX** [comment] 2023-10-25 06:35
The button is not hidden
