### ISSUE TITLE
bug: YouTube patching fails: "'general-ads' depends on ... could not find method hook"

### ISSUE THREAD

**Issue by bigyihsuan** [revanced/revanced-patches#1809] opened 2023-03-26 23:41 UTC
### Type

Error while patching

### Bug description

Patching YouTube fails because it could not find a method hook.

### Steps to reproduce

1. Install YouTube 18.05.40
2. Install Revanced Manager 0.0.57
3. Attempt to patch YouTube with `general-ads`. Other selected patches don't matter.
4. The bug then occurs during patching.

### Relevant log output

```shell
'general-ads' depends on 'GeneralAdsResourcePatch' but the following error was raised: 'GeneralAdsResourcePatch' depends on 'LithoFilterPatch' but the following error was raised: Could not find the method to hook.
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/12767476/227812039-6a6b6087-a76a-4490-a668-ef426e51219f.png)

### Additional context

- YouTube v18.05.40
- Revanced Manager 0.0.57
- Android 11
- OnePlus 7, rooted (via Magisk)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-03-26 23:46
Unable to reproduce, leaving open for others to reproduce. In the meantime attach a recording of the following:

1. Uninstall any patched app
If you previously installed a patched app, make sure it is uninstalled.
2. Open and close ReVanced Manager
This makes sure ReVanced Manager starts up and is set up correctly. Optionally you can also uninstall and re-install ReVanced Manager.
3. Review the settings of ReVanced Manager
Go to the settings of ReVanced Manager and review them one by one, making sure to show everything you changed as well.
4. Patch the app
Patch your app the way you did previously, which leads to your error.

**Comment by bigyihsuan** [comment] 2023-03-27 00:00
@oSumAtrIX https://youtu.be/szzjuz4wmk4

**Comment by oSumAtrIX** [comment] 2023-03-27 00:02
Please investigate into this:

![image](https://user-images.githubusercontent.com/13122796/227813224-d4ff0003-e34e-4c83-82f4-169c495c346b.png)

**Comment by bigyihsuan** [comment] 2023-03-27 00:03
> Please investigate this:
> 
> ![image](https://user-images.githubusercontent.com/13122796/227813224-d4ff0003-e34e-4c83-82f4-169c495c346b.png)

Thing is, I don't know why that is. That's why this issue is here.

**Comment by oSumAtrIX** [comment] 2023-03-27 00:05
Likely an issue with your device blocking some connection

**Comment by bigyihsuan** [comment] 2023-03-27 00:08
> Likely an issue with your device blocking some connection

But is it related to the bug in the OP? If not then it should be its own issue; plus this is the latest release of Manager.

**Comment by oSumAtrIX** [comment] 2023-03-27 00:11
I don't know, which is why you should resolve it to check if it causes the issue.

**Comment by bigyihsuan** [comment] 2023-03-27 00:13
> I don't know, which is why you should resolve it to check if it causes the issue. Also, it is not an issue with the app, as your phone is likely blocking it.

I have nothing blocking any connections on my phone; I've explicitly checked for that.

**Comment by oSumAtrIX** [comment] 2023-03-27 00:19
The only time I have seen this happening was when someone was blocking the connection. Try applying the patches using the CLI to check if it is an issue with the app.

**Comment by bigyihsuan** [comment] 2023-03-27 00:58
Patching it manually via CLI worked. Though it is a workaround, it doesn't fix the problem.

**Comment by oSumAtrIX** [comment] 2023-03-27 01:21
First the source of "the problem" as you describe it has to be figured out. If the patch works on CLI but not on the app, then the environment affects the patching process which would make it an issue with the ReVanced Patcher. Can you reproduce in a debuggable environment?

**Comment by seangibbz** [comment] 2023-05-07 03:21
I've come across the same error when patching using Revanced-CLI using the following command:

```
java -jar revanced-cli-*.jar \
-b revanced-patches-*.jar \
-m revanced-integrations-*.apk \
-c \
--exclusive \
-a input/YouTube_*.apk \
-o output/youtube_patched.apk \
-i client-spoof \
-i copy-video-url \
-i disable-auto-captions \
-i disable-fullscreen-panels \
-i disable-player-popup-panels \
-i disable-shorts-on-startup \
-i downloads \
-i general-ads \
-i hdr-auto-brightness \
-i hide-breaking-news-shelf \
-i hide-crowdfunding-box \
-i hide-email-address \
-i hide-endscreen-cards \
-i hide-get-premium \
-i hide-watch-in-vr \
-i hide-watermark \
-i minimized-playback \
-i old-quality-layout \
-i open-links-externally \
-i return-youtube-dislike \
-i sponsorblock \
-i spoof-signature-verification \
-i video-ads \
-d REDACTED \
--mount
```

My current files used are as follows:
|      App     | File                                    |
|:------------:|-----------------------------------------|
|      CLI     | revanced-cli-2.21.1-all.jar             |
|    Patches   | revanced-patches-2.174.0-dev.4.jar      |
| Integrations | revanced-integrations-0.108.0-dev.2.apk |
|    YouTube   | YouTube_18.16.37_Apkpure.apk            |

Complete Error Output:
```
SEVERE: general-ads failed:
app.revanced.patcher.patch.PatchResultError: 'general-ads' depends on 'VerticalScrollPatch' but the following error was raised: java.lang.ClassCastException: class org.jf.dexlib2.builder.instruction.BuilderInstruction35c cannot be cast to class org.jf.dexlib2.iface.instruction.OneRegisterInstruction (org.jf.dexlib2.builder.instruction.BuilderInstruction35c and org.jf.dexlib2.iface.instruction.OneRegisterInstruction are in unnamed module of loader 'app')
        at app.revanced.patches.shared.misc.fix.verticalscroll.patch.VerticalScrollPatch.execute(VerticalScrollPatch.kt:26)
        at app.revanced.patches.shared.misc.fix.verticalscroll.patch.VerticalScrollPatch.execute(VerticalScrollPatch.kt:16)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

**Comment by oSumAtrIX** [comment] 2023-05-07 11:13
Do not use dev releases. Issue is outdated, closing therefor.

**Closed by oSumAtrIX** 2023-05-07 11:13 UTC
Labels: bug, waiting on author
