### ISSUE TITLE
feat(YouTube): Force VP9 codec

### ISSUE THREAD

**Issue by eldepor** [ReVanced/revanced-patches#3043] opened 2024-04-18 19:01 UTC
### Feature description

A patch that forced VP9 codec that was removed previously.

### Motivation

The whole issue is described in this thread (https://github.com/ReVanced/revanced-patches/issues/2986#issuecomment-2056562853, https://github.com/ReVanced/revanced-patches/issues/2986#issuecomment-2062865142, https://github.com/ReVanced/revanced-patches/issues/2986#issuecomment-2063484385, https://github.com/ReVanced/revanced-patches/issues/2986#issuecomment-2063623791, and following comments)
But basically to avoid the poor rendering and frame dropping problem of AV1 1080p60 shorts on some devices caused by Google's recent update with which they have pushed and forced the AV1 codec over VP9 which allowed to play shorts at 1080p60 with no frame dropping at all. 

Thank you.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by libreom** [comment] 2024-04-19 02:48
I aldo support this(because my device's default is avc,and is lower quality when it can play vp9 and av1 smoothly), but option should given to force different codecs like av1, h264 too

**Comment by SodaWithoutSparkles** [comment] 2024-04-19 03:07
possible duplicate of #1853

**Comment by oSumAtrIX** [comment] 2024-06-01 21:54
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Closed by oSumAtrIX** 2024-06-01 21:54 UTC
Labels: Feature request
