### ISSUE TITLE
bug: Hide video ads patch broken

### ISSUE THREAD

**Issue by Neophytae** [revanced/revanced-patches#595] opened 2022-09-23 12:14 UTC
### Type

Other

### Bug description

Me and many others are experiencing videos not loading and sitting in a continuous buffering loop.

### Steps to reproduce

Patch YouTube app with the "Hide video ads" patch. Try to load videos with the patch enabled and quite often they will not load. Turn off the patch in settings>ReVanced>Ads>Hide video ads and then try again. Videos all load fine but video ads appear as expected.

### Relevant log output

```shell
No logs available
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Neophytae** [comment] 2022-09-23 14:57
@oSumAtrIX  Does completed mean that this has been resolved?

**Comment by oSumAtrIX** [comment] 2022-09-23 15:43
Not necessary.

**Comment by Neophytae** [comment] 2022-09-23 15:44
Could you please elaborate?

**Comment by oSumAtrIX** [comment] 2022-09-23 15:49
It can be closed due to the acknowledgements not being followed properly. You are contradicting yourself in the issue by saying first the video buffers but later saying it loads fine.

**Comment by Neophytae** [comment] 2022-09-23 16:06
Exactly my point!? The issue with videos not loading clearly lies within the patch. Patch enabled=videos not loading, patch disabled=videos load fine but load with ads, obviously. There is no contradiction just a miscommunication

**Comment by oSumAtrIX** [comment] 2022-09-23 16:07
Please include a full recording of patching the app and showcasing the issue.

**Comment by Neophytae** [comment] 2022-09-23 16:26
I will do this for you later when I get home, thanks.

**Comment by Neophytae** [comment] 2022-09-24 06:15
Here is a clip, shows me updating the installer and then patching a freshly downloaded APK (recommended version). First playing videos with the patch enabled you can see a few just sit and buffer, but once the patch is disabled all videos load fine but obviously ads are displayed also. After reenabling the patch it seems to work until you force close the app and open it again and the we're back to mostly buffering videos. [Link to YouTube video of screen recording ](https://youtu.be/N74dP5vLAP8)

**Comment by oSumAtrIX** [comment] 2022-09-24 10:25
Disable all patches except the video ads patch and check again.

**Comment by Neophytae** [comment] 2022-09-24 11:42
Only patched with hide video ads, with patch enabled and then disabled 
[Link](https://youtu.be/qd0NjbqWKOw)

**Comment by dannyholyoake** [comment] 2022-09-24 18:30
Just to add I have exactly the same issue.

Could this be account-based on Google's end? Could it be to do with MicroG (I still have it from the Vanced days).

**Comment by oSumAtrIX** [comment] 2022-09-24 21:18
For anyone's information, I or anyone on our team do not get this type of ad, we need a volunteer's account to get rid of this ad on our end.

**Comment by duckboy** [comment] 2022-09-25 14:43
> For anyone's information, I or anyone on our team do not get this type of ad, we need a volunteer's account to get rid of this ad on our end.

He's not saying that the ad is the issue, it's the fact the video will endlessly buffer while the Remove Video Ads patch is enabled. For the record, I have this issue too and I believe it is account side. Removing General Ads and Video ads patch does help somewhat but the issue remains on one of my accounts no matter what I do (microg non root). My other account works perfectly regardless of any patches.

**Comment by dannyholyoake** [comment] 2022-09-25 15:04
Agreed. Did any other affected users have issue with Vanced before this? My Vanced stopped playing videos entirely (telling me to update my YouTube app). It was suggested online that this was account-side.

I wonder if Google has made some changes their end that makes MicroG less functional for certain users (I'm in the UK, FYI)

I've noticed that it affects monetised videos more than non-monetised ones. This suggests to me that ReVanced is attempting to bypass an ad and failing.

To the Devs - are there any logs we can generate that might help you identify this issue?

**Comment by duckboy** [comment] 2022-09-26 17:35
> Agreed. Did any other affected users have issue with Vanced before this? My Vanced stopped playing videos entirely (telling me to update my YouTube app). It was suggested online that this was account-side.
> 
> I wonder if Google has made some changes their end that makes MicroG less functional for certain users (I'm in the UK, FYI)
> 
> I've noticed that it affects monetised videos more than non-monetised ones. This suggests to me that ReVanced is attempting to bypass an ad and failing.
> 
> To the Devs - are there any logs we can generate that might help you identify this issue?

Yes fwiw i'm in the UK and my Vanced died the same death too

**Comment by Neophytae** [comment] 2022-09-26 17:52
UK here too. Weirdly, if I disable the patch, restart the app then reenable the patch and restart again more videos load properly but still the odd one loops where it appears an ad is trying to load. Also tried it with every version from the recommended up to the most recent with no change.

**Comment by oSumAtrIX** [comment] 2022-09-26 18:35
Dupe of #612.

**Closed by oSumAtrIX** 2022-09-26 18:35 UTC
Labels: bug, help wanted, question

**Comment by dannyholyoake** [comment] 2022-09-26 20:31
why have you closed this ticket @oSumAtrIX ? You've marked it as a duplicate to an issue that isn't identical, and that's also an issue you've marked as completed. That issue suggests ads are still playing. This issue is detailing that something is preventing the video to play at all.

Seems like huge miscommunications going on here? Can we please acknowledge and address this?

**Comment by oSumAtrIX** [comment] 2022-09-26 22:53
The issue is related and both are fixed the same way.

**Comment by dannyholyoake** [comment] 2022-09-27 05:06
Could you elaborate on how the issue is fixed? Is there a relevant pull request or update that addresses this issue?

**Comment by oSumAtrIX** [comment] 2022-09-27 05:13
Would be* fixed.

**Comment by oSumAtrIX** [comment] 2022-09-27 11:02
As i said previously, its related to the other issue, making this one a dupe.

**Comment by Neophytae** [comment] 2022-09-27 11:05
Related how? My issue is vids not loading and continuously buffering, the other is showing unskippable ads.

**Comment by oSumAtrIX** [comment] 2022-09-27 11:26
They are occuring from the same sourcey which is the removal of ads, for your issue, the removal causes playback issues, for the other, the removal doesn't work properly, hence why related. Both issues would be solved by the same fix.

**Comment by dannyholyoake** [comment] 2022-09-27 12:13
So what's the fix @oSumAtrIX ? Since both tickets are closed, is there a fix on the way?

**Comment by oSumAtrIX** [comment] 2022-09-27 12:28
No fix yet, the other issue is closed because it is a dupe of an existing issue.

**Comment by dannyholyoake** [comment] 2022-09-27 14:56
Can you link the existing issue that ISNT closed so we can follow for a fix, please? Because far as I can tell, you've closed all of them...

**Comment by oSumAtrIX** [comment] 2022-09-27 15:02
There's one open, but i won't search for you, please do it yourself if you want to track it.

**Comment by Neophytae** [comment] 2022-09-27 16:15
If you're talking about #40 it's nothing to do with that either. Appreciate your work but is there possibly another Dev we xan try and communicate this issue with

**Comment by oSumAtrIX** [comment] 2022-09-27 17:24
@Neophytae It is related: https://github.com/revanced/revanced-patches/issues/595#issuecomment-1259361043

**Comment by cwhytock** [comment] 2022-10-10 18:08
A fix for the infinite buffering is to skip to the end using the slider then hit reload in the centre, at which point it always plays normally so far, without ads. It should be possible to compare the http calls to see how it is behaving differently.

**Comment by Neophytae** [comment] 2022-10-10 18:36
You can also close the video and then immediately open the video again or skil forward and then back and it will also play normally with no ads
