### ISSUE TITLE
bug: Reddit hide ads fails

### ISSUE THREAD

**Issue by soccerboys2008** [revanced/revanced-patches#2405] opened 2023-06-12 08:56 UTC
### Type

Error while patching

### Bug description

"Hide ads" not being applied when trying to patch reddit version 2023.22.0

### Steps to reproduce

Step 1: download reddit from apkmirror: https://www.apkmirror.com/apk/redditinc/reddit/reddit-2023-22-0-release/reddit-2023-22-0-2-android-apk-download/

Step 2: try patching with hide ads, premium icon reddit, and sanitize sharing links

Step 3: attempt to patch and the error should occur

Android 13 (lineage os)
Oneplus 6t

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Failed to apply hide-ads: length=42; index=-1
Applied premium-icon-reddit
Applied sanitize-sharing-links
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

![Screenshot_20230612-034453_ReVanced Manager](https://github.com/revanced/revanced-patches/assets/29149297/9c6639e1-ba8e-4b99-9eae-d7d069afd2fa)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by HellManCyber** [comment] 2023-06-12 21:37
Having same issue on s22 ultra with Android 13.
![Screenshot_20230612_173551.jpg](https://github.com/revanced/revanced-patches/assets/71520258/bec1cc96-ea00-4f8b-b4cf-38cb5c88d820)



Tried 2023.21.0 and 2023.22.0 versions of reddit

**Comment by SodaWithoutSparkles** [comment] 2023-06-13 10:12
Cannot reproduce the issue.

- manager v1.3.5
- patches v2.177.0
- reddit v2023.22.0

Reddit APK checksums:
```
CRC32: 8c807779
MD5: 95316b4009078146c858ebad8d2c9017
SHA1: 282a6be2e5f8f3aa68d7b75232269fcefbaaf2e1
SHA256: 2efa0eedac0de3606149aae0bf784129c71e38f7ba2d140a999338d1c22c9c4a
SHA384: fc3e43b2d04d319098638091a225ad7422d54e54b004e611588bef7dd4748c35d1bb4ec2c64082297e60744a3b8ddad5
SHA512: d09d80658dc81c446dd4bcea81b355fb3f71a2e67265c1b46d40d308e91dd7f4cbfeeafafd1e766904dc79c14af60b093325143df30c85a9aff6a98f9ca0c16d
```

**Comment by oSumAtrIX** [comment] 2023-06-13 13:49
This was fixed in the latest release

**Closed by oSumAtrIX** 2023-06-13 13:49 UTC
Labels: bug

**Comment by soccerboys2008** [comment] 2023-06-13 17:52
yes it does work now, i think the reason is that i opened the issue at "Jun 12, 2023, 3:56AM" and the pre-release for the newest version was dropped at "Jun 12, 2023, 5:54 PM" (which fixed the issue) with the release following at "6:01 PM".

 so i opened an issue not knowing there was a fix in progress
