### ISSUE TITLE
bug: Youtube Patch cannot be successful.

### ISSUE THREAD

**Issue by Kustale** [revanced/revanced-patches#2344] opened 2023-06-02 15:11 UTC
### Type

Error while patching

### Bug description

An error occurred while patching.

### Steps to reproduce

1. Receive recent files revanced-cli, revanced-patches, revanced-integrations.
2. Get 18.19.35 nodpi apk from https://www.apkmirror.com/apk/google-inc/youtube/.
3. java.exe -jar revanced-cli-2.21.2-all.jar -a com.google.android.youtube_18.19.35-1537727936_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com .apk -c -o Youtube_Edited.apk -b revanced-patches-2.176.0-dev.2.jar -m revanced-integrations-0.110.0-dev.2.apk

(jdk : zulu20.30.11-ca-jdk20.0.1-win_x64)

### Relevant log output

```shell
java.exe -jar revanced-cli-2.21.2-all.jar -a com.google.android.youtube_18.19.35-1537727936_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk -c -o Youtube_Edited.apk -b revanced-patches-2.176.0-dev.2.jar -m revanced-integrations-0.110.0-dev.2.apk
정보: Reading dex files
정보: Decoding AndroidManifest.xml only, because resources are not needed
정보: Skipping change-package-name: Excluded by default
정보: Skipping custom-video-buffer: Excluded by default
정보: Skipping enable-android-debugging: Excluded by default
정보: Skipping export-all-activities: Excluded by default
정보: Skipping predictive-back-gesture: Excluded by default
정보: Skipping remove-player-controls-background: Excluded by default
정보: Skipping remove-screen-capture-restriction: Excluded by default
정보: Skipping remove-screenshot-restriction: Excluded by default
정보: Skipping spoof-wifi-connection: Excluded by default
정보: Merging revanced-integrations-0.110.0-dev.2.apk
정보: Deleting existing resource cache directory
심각: Failed to delete existing resource cache directory
정보: Decoding resources
정보: always-autorepeat succeeded
정보: client-spoof succeeded
정보: comments succeeded
정보: copy-video-url succeeded
정보: custom-branding succeeded
정보: disable-auto-captions succeeded
정보: disable-fullscreen-panels succeeded
정보: disable-player-popup-panels succeeded
정보: disable-shorts-on-startup succeeded
정보: disable-zoom-haptics succeeded
정보: enable-debugging succeeded
정보: external-downloads succeeded
정보: hdr-auto-brightness succeeded
정보: hide-ads succeeded
정보: hide-album-cards succeeded
정보: hide-artist-card succeeded
정보: hide-autoplay-button succeeded
정보: hide-breaking-news-shelf succeeded
정보: hide-captions-button succeeded
정보: hide-cast-button succeeded
정보: hide-crowdfunding-box succeeded
정보: hide-email-address succeeded
정보: hide-endscreen-cards succeeded
정보: hide-filter-bar succeeded
정보: hide-floating-microphone-button succeeded
정보: hide-info-cards succeeded
정보: hide-load-more-button succeeded
정보: hide-player-buttons succeeded
정보: hide-player-overlay succeeded
정보: hide-seekbar succeeded
정보: hide-shorts-components succeeded
정보: hide-timestamp succeeded
정보: hide-video-action-buttons succeeded
정보: hide-watch-in-vr succeeded
정보: hide-watermark succeeded
정보: minimized-playback succeeded
정보: navigation-buttons succeeded
정보: old-quality-layout succeeded
정보: open-links-externally succeeded
정보: premium-heading succeeded
정보: remember-video-quality succeeded
정보: return-youtube-dislike succeeded
정보: seekbar-tapping succeeded
정보: sponsorblock succeeded
정보: spoof-app-version succeeded
정보: swipe-controls succeeded
정보: tablet-mini-player succeeded
정보: theme succeeded
정보: vanced-microg-support succeeded
정보: video-ads succeeded
정보: video-speed succeeded
정보: wide-searchbar succeeded
정보: Compiling resources
경고: C:\Users\Kustale\Downloads\revanced-cache\res\values\strings.xml:3365: error: unescaped apostrophe in string
경고: "Don't save and restore brightness when exiting or entering fullscreen".
경고: C:\Users\Kustale\Downloads\revanced-cache\res\values\strings.xml:3365: error: not a valid string.
경고: C:\Users\Kustale\Downloads\revanced-cache\res\values\strings.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Kustale\AppData\Local\Temp\brut_util_Jar_1107312556056101022075753379499280561.tmp, compile, --dir, C:\Users\Kustale\Downloads\revanced-cache\res, --legacy, -o, C:\Users\Kustale\Downloads\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
        at app.revanced.patcher.Patcher.save(Patcher.kt:126)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Kustale\AppData\Local\Temp\brut_util_Jar_1107312556056101022075753379499280561.tmp, compile, --dir, C:\Users\Kustale\Downloads\revanced-cache\res, --legacy, -o, C:\Users\Kustale\Downloads\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
        ... 13 more
```

### Screenshots or videos

![0582390592](https://github.com/revanced/revanced-patches/assets/113628110/bb43d9a2-e44d-42e6-ac45-b6b5e3ef5ead)

### Solution

res\values\strings.xml:3365: error: unescaped apostrophe in string
"Don>[backslash]<'t save and restore brightness when exiting or entering fullscreen".

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-06-02 18:03
@LisoUseInAIKyrios Basically what's going in is, that I rebase commits & then force push. Since the latest commits from semantic release remain, GirHub does not trigger the workflow (correctly). This was intended, but if you want to trigger releases, either simply continue pushing commits normally, or delete the latest semantic release commits & tags. Then a force push will trigger the workflow again and semantic release will create a new release if I understood your issue correctly.

**Comment by oSumAtrIX** [comment] 2023-06-02 18:04
Anyways, this issue is from dev branch, closing therefor as a fix commit has been merged

**Closed by oSumAtrIX** 2023-06-02 18:04 UTC
Labels: bug
