### ISSUE TITLE
feat(Spotify): 

### ISSUE THREAD

**Issue by snilex1** [revanced/revanced-patches#504] opened 2022-09-16 14:43 UTC
### Application

Spotify

### Issue

Ads in spotify

### Patch

Ads in spotify

### Motivation

Good music

**Comment by sawankumarbundelkhandi** [comment] 2022-09-17 20:11
duplicate of https://github.com/revanced/revanced-patches/issues/450

**Closed** 2022-09-17 20:15 UTC
Labels: patch-request

**Comment by sawankumarbundelkhandi** [comment] 2022-09-21 12:07
@oSumAtrIX  one of the two https://github.com/revanced/revanced-patches/issues/450 or https://github.com/revanced/revanced-patches/issues/504 should be kept open as the request for new patches are now maintained in the here only instead of the org discussion.
