### ISSUE TITLE
Make `disable-cast-button` patch optional

### ISSUE THREAD

**Issue by krux3r** [revanced/revanced-patches#78] opened 2022-06-29 23:08 UTC
Casting works via the settings proving that casting should not cause any issue for the `microg-support` patch. For that reason, the `disable-cast-button` patch should be made optional.

**Comment by TheJeterLP** [comment] 2022-06-30 17:48
> Apparently it does not cause issues. The error is smaller than "its casting".

Remember a few days ago when you insisted to keep it deactivated? 😂

**Comment by Canny1913** [comment] 2022-06-30 17:49
> > Apparently it does not cause issues. The error is smaller than "its casting".
> 
> Remember a few days ago when you insisted to keep it deactivated? 😂

Well it **did** solve the issue though.

**Comment by oSumAtrIX** [comment] 2022-06-30 17:50
We haven't conducted any tests yet. It might be very well that enabling it can cause issues again.

**Comment by TheJeterLP** [comment] 2022-07-01 08:08
> > Microg depends on this patch. Unless you exclude that one as well, the cast button patch will be included as a depedency
> 
> I already did some tests and it continues to heat up when activating the cast button, what is causing this problem?
> I will try to go through all the code and see how to optimize or fix that problem 

The problem is that microg is not updated to the current casting version from google

**Comment by TheJeterLP** [comment] 2022-07-01 08:17
> > > > Microg depends on this patch. Unless you exclude that one as well, the cast button patch will be included as a depedency
> > > 
> > > 
> > > I already did some tests and it continues to heat up when activating the cast button, what is causing this problem?
> > > I will try to go through all the code and see how to optimize or fix that problem
> > 
> > The problem is that microg is not updated to the current casting version from google
> 
> great, I'll see how to achieve it, anything I'll let you know

You can't, microg devs have to fix the problem

**Comment by oSumAtrIX** [comment] 2022-07-01 08:24
@FirewallSH56 It is about "how" you enable the cast button. It could be the casting module v2 which we just have to disable to fight the heating issue, casting v1 would still work perfectly fine.

**Comment by Sacerdoss** [comment] 2022-07-01 18:21
Just my 2 cents: I once had a look at the current chromecast v2 support of microg. The boilerplate is there but development hasn´t started. There is probably a developer missing willing and capable to put time into this feature so there probably won`t be a v2 support any time soon. 
I don`t know of any app still using/supporting v1. So it`s basically no chromecast if using microg. At least for most of the Apps like Youtube/Netflix...

**Comment by oSumAtrIX** [comment] 2022-07-01 20:23
Technically speaking v1 should still work and I considered enabling that as some poeple don't have a problem using v1. Tests would need to be conducted for stability though.

**Comment by masterflitzer** [comment] 2022-08-09 08:59
I might have an idea, if the cast button causes issues because it cannot be enabled with only casting v1

we could disable it with microg like it is now, but optionally add another cast button which only serves as shortcut to the watch on tv menu (settings > watch on tv)

because watch on tv menu with manual linking is working without any problems for me, it's just annoying always have to take 3 steps to get into the menu

**Comment by oSumAtrIX** [comment] 2022-08-09 11:14
Closing in favour of #243.

**Closed by oSumAtrIX** 2022-08-09 11:14 UTC
Labels: change-required, testing-needed
