### ISSUE TITLE
End screens still showing

### ISSUE THREAD

**Issue by skypeias** [revanced/revanced-patches#364] opened 2022-08-20 17:04 UTC
### Type

Other

### Bug description

Even though I have the end screens toggle set to "End screens are hidden", they still show up at the end of videos.

### Steps to reproduce

Watch any video that would typically have end screens, like music videos

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20220820-123631](https://user-images.githubusercontent.com/109490992/185758428-6afb2f4e-9616-4ce4-bbfc-4bff59b9a4a7.jpg)

**Comment by oSumAtrIX** [comment] 2022-08-20 17:05
Dupe of #304.

**Closed by oSumAtrIX** 2022-08-20 17:05 UTC
Labels: bug
