### ISSUE TITLE
feat(patch): media download button for Twitter 

### ISSUE THREAD

**Issue by cyriotic3** [revanced/revanced-patches#538] opened 2022-09-19 16:56 UTC
### Application

twitter 

### Issue

currently can't download videos of twitter, you can only do that on photos 

### Patch

adds a download button for media

### Motivation

just wanted a very convenient way to do this without resorting to 3rd party apps, website and such

**Comment by oSumAtrIX** [comment] 2022-09-19 16:59
Dupe of #327.

**Closed by oSumAtrIX** 2022-09-19 16:59 UTC
Labels: patch-request
