### ISSUE TITLE
feat(patch):  Age restriction bypass

### ISSUE THREAD

**Issue by Protonosgit** [revanced/revanced-patches#555] opened 2022-09-20 16:32 UTC
### Application

Youtube

### Issue

Bypass age restriction

### Patch

A patch that removes the "verify your age" screen and instead just plays the video

### Motivation

Some videos are being flagged as 18+ content without containing anything the would justify this action and I would like to avoid sending a picture of my ID to Google.

*There are already options out there but it would be nice if there was an option within the YouTube app.

**Comment by oSumAtrIX** [comment] 2022-09-20 16:35
Dupe of #173.

**Closed by oSumAtrIX** 2022-09-20 16:35 UTC
Labels: patch-request
