### ISSUE TITLE
bug(TikTok): Advertisements in the Following Page 

### ISSUE THREAD

**Issue by DeannWinchesterr** [ReVanced/revanced-patches#430] opened 2023-08-21 09:46 UTC
### Type

Other

### Bug description

On Tiktok ReVanced when I open the following tab, i get an advertisement every 5-6 videos and they just keep coming. All with the sponsored tag. 

### Steps to reproduce

Looks like it's account specific but you can check to see if you have ads in the following page or not. 

### Relevant log output

```shell
No log for this since it's just a minor advertisement issue.
```

### Screenshots or videos

![Screenshot_20230821-150346_TikTok](https://github.com/ReVanced/revanced-patches/assets/131953486/26e1a3e8-0834-4631-b2a8-a9c36b06484c)
![Screenshot_20230821-150333_TikTok](https://github.com/ReVanced/revanced-patches/assets/131953486/8d48d90d-9ba3-4f54-a614-dd4c09750090)
![Screenshot_20230821-150319_TikTok](https://github.com/ReVanced/revanced-patches/assets/131953486/464dc1e6-5d45-4ee2-babc-cc8445269ba5)
![Screenshot_20230821-151216_TikTok](https://github.com/ReVanced/revanced-patches/assets/131953486/bc38cdec-a21c-46cb-b997-571dd1ed4305)

### Additional context

I'm getting advertisements in the Following Page. Tiktok 30.8.4 with latest ReVanced patches. But I've had this issue since the first ReVanced tiktok version. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2024-07-31 17:48
Closing as duplicate of https://github.com/ReVanced/revanced-patches/issues/3246

**Closed by oSumAtrIX** 2024-07-31 17:48 UTC
Labels: Bug report
