### ISSUE TITLE
problem: `video-ads`

### ISSUE THREAD

**Issue by RFLEpicGamer** [revanced/revanced-patches#218] opened 2022-07-21 21:14 UTC
## 🐞 Issue

Videos ads are still shown even though I applied the video-ads patch

## ⚙ Reproduce

I entered the Anonymous mode to watch a video but when I opened the video, it showed a video ad instead of a normal video

**Comment by oSumAtrIX** [comment] 2022-07-21 21:20
Dupe of #40.

**Closed by oSumAtrIX** 2022-07-21 21:20 UTC
Labels: bug
