### ISSUE TITLE
bug(YouTube - Spoof video streams): Android VR client side effects (Livestreams start from beginning, Videos end 1 second early)

### ISSUE THREAD

**Issue by MarcaDian** [ReVanced/revanced-patches#4081] opened 2024-12-09 12:44 UTC
### Bug description

If the `Spoof video streams` and `Android VR` client is enabled, livestreams start from the beginning and videos end 1 second earlier.
(Maybe other iOS side effects as well.)
ReVanced patches v5.3.0

![Image](https://github.com/user-attachments/assets/b53e1e6f-666a-4acc-95e9-eb9e18cdeddd)

https://github.com/user-attachments/assets/345d3b22-db2a-40f8-8139-745830700ff4

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by 0xrxL** [comment] 2024-12-09 20:29
@LisoUseInAIKyrios I recently tried to fix this lack by searching a way to restore the original flyout button, and I found a class where the visibility of this button change to true or false, if the size of a list field (that contains all the available audio) tracks is greater than 1.

Maybe you know a way to add more languages to that list, and restore the button visibility. 🤷‍♂️

**Comment by 0xrxL** [comment] 2024-12-09 22:02
> Does Android VR return more than one audio stream? If the menu entries are missing maybe it can be added as you said.

Nope, just return the system language. In fact, once I set the button visibility to true, I was only able to see my region language inside tracks flyout.

More languages can be added...maybe.

**Comment by 0xrxL** [comment] 2024-12-12 20:49
> > Are these completely fixable?
> 
> If someone can figure out a fix.

Thanks to a not-merged solution founded by @YT-Advanced, I added an improved check on my integrations, to detect if a video is live stream or not.

https://github.com/0xrxL/uDrop/blob/4935f75e5cb18be7b31128586b291d4d0b8a1794/Code/java/uTools/StreamSpoofing/uStreamingDataRequest.java#L112

If you know a way to automatically seek a video to a precise time, you can combine the two things to fix the "live stream from start" issue.

**Comment by oSumAtrIX** [comment] 2024-12-12 21:26
The reason playback starts at the beginning is because in the DASH manifest a parameter is different. It is assumed by others to be a bug in ExoPlayer.

**Comment by d3rpd3rpd3rp** [comment] 2024-12-12 23:49
Livestreams start at the beginning using Android VR for me as well. Using latest patches and suggested YT version on two different devices.

**Comment by inotia00** [comment] 2024-12-16 13:01
One of the side effects of iOS client - `Livestream starts from the beginning` - seems to have been fixed in https://github.com/inotia00/revanced-patches/commit/d1b2fe16dbf503e2f15f1dc12fb582f25fed884f.

I already checked all experimental flags a few months ago, and didn't find this flag then.

It seems to be an experimental flag that became available after the change to no longer set the `Authorization` header on iOS client a month ago: https://github.com/ReVanced/revanced-patches/pull/4000

**Closed** 2024-12-16 19:25 UTC
Labels: Bug report

**Comment by YT-Advanced** [comment] 2024-12-17 08:49
For more information, this problem is caused by the missing of `format` in `streamingData`
Check https://github.com/zerodytrash/YouTube-Internal-Clients

**Comment by 0xrxL** [comment] 2025-03-24 01:19
@LisoUseInAIKyrios Setting flag 45355374L to false, prevent the start from beginning playback for livestreams played with Android VR. 👍
