### ISSUE TITLE
feat(patch):1. Black Navigation Bar, 2. Color of Full Screen Player matches with minimised one, 3. App renamed to native "YT Music"

### ISSUE THREAD

**Issue by introversialscalpel** [revanced/revanced-patches#537] opened 2022-09-19 08:59 UTC
### Application

YouTube Music

### Issue

The name of app would be more in sync with that of Youtube app.

Black Navigation bar and Colored minimised player give an overall homogeneous look.

### Patch

![Screenshot_20220919-142520_YouTube Music](https://user-images.githubusercontent.com/102604664/190982754-f7ccb7d6-f37a-45b7-b770-c82add9745ab.jpg)
Should look like this after the patches feature are added.

### Motivation

Makes the app use more seamless.

**Comment by oSumAtrIX** [comment] 2022-09-19 14:09
Dupe of #476.
Make separate well explained issues about the rest.

**Closed by oSumAtrIX** 2022-09-19 14:09 UTC
Labels: patch-request
