### ISSUE TITLE
Sponsorblock settings acts strange

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-patches#1447] opened 2023-01-07 16:15 UTC
### Type

Error at runtime

### Bug description

Sponsorblock (SB) in revanced behaves strangely. Either one of the following happens: It does not show the private ID, OR, RV crashed when you attempt to open SB settings

### Steps to reproduce

1. Patch with latest version of anything as of 2022-01-07T1600 UTC+0
2. Import SB config
3. Click on private ID, the ID is missing even if you have imported a config that has it
4. Click to export config, notice that the private ID is missing
5. Notice that you can still submit segments after step 2, but I havent tested if step 3 is executed
6. Kill the RV and relaunch
7. Go to SB settings, RV crashed. Logs shown below are captured by MIUI and dumped

### Relevant log output

```shell
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.revanced.android.youtube/com.google.android.libraries.social.licenses.LicenseActivity}: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3948)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1023)
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
	at android.preference.Preference.getPersistedString(Preference.java:1681)
	at android.preference.EditTextPreference.onSetInitialValue(EditTextPreference.java:178)
	at android.preference.Preference.dispatchSetInitialValue(Preference.java:1591)
	at android.preference.Preference.onAttachedToHierarchy(Preference.java:1358)
	at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:171)
	at app.revanced.integrations.settingsmenu.SponsorBlockSettingsFragment.addGeneralCategory(SponsorBlockSettingsFragment.java:341)
	at app.revanced.integrations.settingsmenu.SponsorBlockSettingsFragment.onCreate(SponsorBlockSettingsFragment.java:232)
	at android.app.Fragment.performCreate(Fragment.java:2486)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
	at android.app.Activity.performCreate(Activity.java:8521)
	at android.app.Activity.performCreate(Activity.java:8472)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3783)
	... 12 more
```

### Screenshots or videos

https://user-images.githubusercontent.com/64138578/211160210-7ba31b2e-9b4e-49bc-ab6d-628d33b813d2.mp4

### Solution

Float cannot be casted to strings...?

### Additional context

#1444 and #1443 might be related to this

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-01-07 16:23
Can't reproduce, leaving open for anyone else.

**Comment by SodaWithoutSparkles** [comment] 2023-01-07 16:29
```
{"dontShowNotice":false,"barTypes":{"sponsor":{"color":"#00D400"},"intro":{"color":"#00FFFF"},"outro":{"color":"#0202ED"},"interaction":{"color":"#CC00FF"},"selfpromo":{"color":"#FFFF00"},"music_offtopic":{"color":"#FF9900"},"preview":{"color":"#008FD6"},"filler":{"color":"#7300FF"}},"showTimeWithSkips":true,"minDuration":0.20000000298023224,"trackViewCount":true,"categorySelections":[{"name":"sponsor","option":2},{"name":"intro","option":1},{"name":"outro","option":1},{"name":"interaction","option":2},{"name":"selfpromo","option":1},{"name":"music_offtopic","option":1},{"name":"preview","option":1}],"userID":"LyIgqoId1tjO0qzcVwcSiTRKynzxRMPKWSLAftWzCT4nmAeeYShYYlQbH4tgrOk18qw2SbmnMuLTYoU5oLzwwUv5dMlQqtbJN","isVip":false,"lastIsVipUpdate":1660819631232,"serverAddress":"https:\/\/sponsor.ajay.app"}
```
Try using this config. My SB settings are locked out...

The userID is a randomly generated 97 character string. Thats not my real one tho

**Comment by Lopolin-LP** [comment] 2023-01-07 22:24
Can Confirm: Patching YouTube ReVanced **Without** SponsorBlock makes my RV work again even after restarting to change settings.

**Comment by LisoUseInAIKyrios** [comment] 2023-01-21 21:16
The issue might be fixed with https://github.com/revanced/revanced-integrations/pull/298

**Comment by TheJeterLP** [comment] 2023-01-21 21:55
> The issue might be fixed with [revanced/revanced-integrations#298](https://github.com/revanced/revanced-integrations/pull/298)

Its not since SB settings are not in the SettingsEnum

**Comment by SodaWithoutSparkles** [comment] 2023-01-22 03:12
@LisoUseInAIKyrios I will check of this is fixed when it have a new release. By looking at the commits, I have quite a high confidence that this is the issue.

**Comment by LisoUseInAIKyrios** [comment] 2023-01-22 22:51
I tried importing settings from the browser extension and it did not work.  Worse, the app then started crashing when opening the SponsorBlock settings.

But, I found the problem and it now appears to be fixed:
https://github.com/revanced/revanced-integrations/pull/304

**Comment by SodaWithoutSparkles** [comment] 2023-01-25 06:18
@LisoUseInAIKyrios Any schedule?

**Comment by LisoUseInAIKyrios** [comment] 2023-01-25 07:23
@SodaWithoutSparkles The changes are done and verified working.  It should be pulled into the dev branch very soon.

**Comment by SodaWithoutSparkles** [comment] 2023-01-25 08:25
@LisoUseInAIKyrios Thanks! Cant wait to have it working again. Hopefully it wont be another soon™

**Closed** 2023-01-28 08:18 UTC
Labels: bug
