### ISSUE TITLE
bug(YouTube - Client Spoof): Watch history does not work when using a brand account

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#3200] opened 2024-05-21 01:17 UTC
### Bug description

When spoof client is enabled, no matter the client type it's spoofed to, watched videos aren't added to history if you are using a brand account.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2024-05-21 01:20
Can confirm working fine on my end.

**Comment by n1cKz1** [comment] 2024-05-21 01:21
The thing is it works fine when client spoof is off, and the necessary domain is whitelisted from my ad blocker

**Comment by oSumAtrIX** [comment] 2024-05-21 01:22
Please attach a recording of the following:

1. Open the patched app & enable spoofing the client
2. Show how history is not being recorded
3. Disable spoofing
4. Show how history is being recorded

**Comment by n1cKz1** [comment] 2024-05-21 01:31
https://github.com/ReVanced/revanced-patches/assets/107653639/61ed8828-3074-4fc5-80bd-8af223f18f77

**Comment by oSumAtrIX** [comment] 2024-05-21 01:32
Let the video play for a longer duration

**Comment by oSumAtrIX** [comment] 2024-05-21 01:38
I have an account that is affected and watch history works.

**Comment by oSumAtrIX** [comment] 2024-05-21 01:40
Can you please attach the recording?

**Comment by n1cKz1** [comment] 2024-05-21 02:02
Settings of account 1 in which vids fail to get added to history:
![image](https://github.com/ReVanced/revanced-patches/assets/107653639/b9edc705-8146-4221-9cda-70852d6b5965)

Settings of account 2 in which vids get added to history just fine:
![image](https://github.com/ReVanced/revanced-patches/assets/107653639/1c0223e9-df27-48da-9af2-0607d9a679ec)

Neither account seems to suffer from playback issues when spoofing is off as of now, so it might not be related after all.

Also, here's a recording of watching 2 entire videos and them not being added to history. The parts during video watching are sped up.


https://github.com/ReVanced/revanced-patches/assets/107653639/83d71b9d-3887-4db7-8810-c6ed8cc0f28b


The only thing I've found so far that might be related (even though I don't see why it would be as it's a separate setting from YT history), is Web & App Activity as that is enabled on on my 2nd account while on my 1st one it's not, but I just tried enabling it and nothing seems to have changed, unless it needs time to take effect.

**Comment by oSumAtrIX** [comment] 2024-05-21 02:03
I'd say we wait and see if anyone else reports it given that we can't reproduce the issue on our end, and so far only you can reproduce the issue on one of your accounts.

**Comment by n1cKz1** [comment] 2024-05-21 04:12
Apparently this issue only occurs on my brand channel of my account. Watch history works fine on my other non-brand channel in the same account. Not sure why that is. Specifically: https://sproutsocial.com/glossary/youtube-brand-account/

**Comment by n1cKz1** [comment] 2024-05-21 04:51
> Send example of Channel or Video link

You misunderstand, the channel I use on which this issue occurs is a brand account, And brand accounts are just that, extra channels you can create on top of your already existing one (plus some additional stuff like adding managers etc). I don't think there's anything distinctive about them

**Comment by Deskehs** [comment] 2024-05-21 05:52
Let me chime in - I can reproduce the issue as well. I think the brand account theory is correct. I have a bunch of brand accounts to separate my YouTube videos and also to have different recommendations on each account. I barely used my "main" one for watching YouTube videos. All the brand accounts doesn't save history, however, the "main" one did.

**Comment by gui-lherme** [comment] 2024-05-21 05:52
> Probably found out how to reproduce this. Apparently this issue only occurs on my brand channel of my account. Watch history works fine on my other non-brand channel on the same account. So if you try to use a brand channel you will likely experience the same thing. Not sure why that is. Specifically: https://sproutsocial.com/glossary/youtube-brand-account/
> 
> This would explain why I've only seen like 2-3 other people reporting this issue in total.

Can confirm. My watch history stops working when I activate the new Client Spoof patch and I use a brand account. When I deactivated the patch, history returned to normal.

**Comment by CoolCooler0** [comment] 2024-05-21 07:32
Watch history is also not working for me when I turn on the "Spoof Client" patch. When its off it records watch history.

**Comment by oSumAtrIX** [comment] 2024-05-21 10:02
Reproducing with a brand account. It may be possible to fix history the same way we did in the past

**Comment by oSumAtrIX** [comment] 2024-05-21 11:03
Moving to https://github.com/ReVanced/revanced-patches/issues/3208

**Closed by oSumAtrIX** 2024-05-21 11:03 UTC
Labels: Bug report
