### ISSUE TITLE
Video ads on shorts

### ISSUE THREAD

**Issue by tzuyu18** [revanced/revanced-patches#143] opened 2022-07-10 17:08 UTC
# 🐞 Issue

I know most users hate and removed shorts tab but I liked it and the problem is video ads still plays, you'll know it is an ad since it has no buttons and description. Please fix this thank you!

# ⚙ Reproduce

I'm using windows 11 with java with the latest July 10 updates.

**Comment by oSumAtrIX** [comment] 2022-07-10 17:09
Dupe of #51.

**Closed by oSumAtrIX** 2022-07-10 17:09 UTC
Labels: bug
