### ISSUE TITLE
YouTube crashes while playing videos

### ISSUE THREAD

**Issue by YouSummoner** [revanced/revanced-patches#1169] opened 2022-11-30 22:32 UTC
### Type

Error at runtime

### Bug description

Some videos Play fine, but some crash YouTube in rooted version.

### Steps to reproduce

1. Patch YouTube with root method.
2. Try to play some videos 

### Relevant log output

```shell
time: 1669847318153
msg: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
stacktrace: aslv: 2 exceptions occurred. 
	at atkn.b(PG:5)
	at atkn.tt(PG:5)
	at astw.d(PG:4)
	at astu.run(PG:3)
	at aewa.run(PG:3)
	at aslj.run(PG:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
  ComposedException 1 :
	java.lang.IllegalArgumentException: No Block implementation registered for block type 482854191. If this is a native implementation, did you register your `block.container` before attempting to create a Container instance? Otherwise, did you include an implementation in the `block.container` rule? See go/blocks-framework-containers#registering-containers for more info.
		at com.google.android.libraries.blocks.runtime.ClientCreatorProxy.nativeCreateBlock(Native Method)
		at com.google.android.libraries.blocks.runtime.ClientCreatorProxy.a(PG:1)
		at com.google.android.libraries.blocks.Container.d(PG:1)
		at ocg.l(PG:2)
		at aefs.U(PG:7)
		at acdr.d(PG:1)
		at com.google.android.apps.youtube.app.common.player.overlay.PlayerOverlayRenderersControllerImpl.l(PG:31)
		at fmq.a(PG:12)
		at atkn.tt(PG:2)
		at astw.d(PG:4)
		at astu.run(PG:3)
		at aewa.run(PG:3)
		at aslj.run(PG:1)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7872)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
		at android.util.Log.getStackTraceString(Log.java:359)
		at adkw.uncaughtException(PG:1)
		at fwg.uncaughtException(PG:3)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at aqvq.w(PG:12)
		at atkn.b(PG:5)
		at atkn.tt(PG:5)
		at astw.d(PG:4)
		at astu.run(PG:3)
		at aewa.run(PG:3)
		at aslj.run(PG:1)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7872)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
  ComposedException 2 :
	txc: java.lang.IllegalArgumentException: No Block implementation registered for block type 482854191. If this is a native implementation, did you register your `block.container` before attempting to create a Container instance? Otherwise, did you include an implementation in the `block.container` rule? See go/blocks-framework-containers#registering-containers for more info.
		at ume.L(PG:1)
		at ezt.a(PG:4)
		at atkn.b(PG:3)
		at atkn.tt(PG:5)
		at astw.d(PG:4)
		at astu.run(PG:3)
		at aewa.run(PG:3)
		at aslj.run(PG:1)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7872)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Caused by: java.lang.IllegalArgumentException: No Block implementation registered for block type 482854191. If this is a native implementation, did you register your `block.container` before attempting to create a Container instance? Otherwise, did you include an implementation in the `block.container` rule? See go/blocks-framework-containers#registering-containers for more info.
		at com.google.android.libraries.blocks.runtime.ClientCreatorProxy.nativeCreateBlock(Native Method)
		at com.google.android.libraries.blocks.runtime.ClientCreatorProxy.a(PG:1)
		at com.google.android.libraries.blocks.Container.d(PG:1)
		at ocg.l(PG:2)
		at aefs.U(PG:7)
		at acdr.d(PG:1)
		at com.google.android.apps.youtube.app.common.player.overlay.PlayerOverlayRenderersControllerImpl.l(PG:31)
		at fmq.a(PG:12)
		at atkn.tt(PG:2)
		at astw.d(PG:4)
		at astu.run(PG:3)
		at aewa.run(PG:3)
		at aslj.run(PG:1)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7872)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
		at android.util.Log.getStackTraceString(Log.java:359)
		at adkw.uncaughtException(PG:1)
		at fwg.uncaughtException(PG:3)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at aqvq.w(PG:12)
		at atkn.b(PG:5)
		at atkn.tt(PG:5)
		at astw.d(PG:4)
		at astu.run(PG:3)
		at aewa.run(PG:3)
		at aslj.run(PG:1)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7872)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
New Snippet  Fork 
 Memochō
```

### Screenshots or videos

.

### Solution

.

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-11-30 22:35
Exclude patches and check if the error dissappears.

**Comment by YouSummoner** [comment] 2022-11-30 22:37
What patches do yo think will need to be excluded?

**Comment by oSumAtrIX** [comment] 2022-11-30 22:41
Not sure, try with no patches first.

**Comment by YouSummoner** [comment] 2022-11-30 22:56
![Screenshot_20221201-042503_ReVanced Manager.png](https://user-images.githubusercontent.com/107224555/204925693-366a546a-1c80-44d7-8b9f-f03996592202.png)
Tried excluding some, it stills crashes. Here's the current patches selection...
The project is in dire need of some quality control...

**Comment by oSumAtrIX** [comment] 2022-12-01 00:01
I asked to try with no patches first.

**Comment by YouSummoner** [comment] 2022-12-01 00:06
I tried without patches, it works fine.
Also I tried the non root version, it's crashing too...

**Comment by oSumAtrIX** [comment] 2022-12-01 00:10
Non root requires the patch for MicroG. This issue is specific for root and not non root. Now comtinue to add patches until the error appears as originally suggested. Respond back with the patch causing the issue.

**Comment by YouSummoner** [comment] 2022-12-01 00:13
I said it's crashing on non root too with the MicroG patch included, the same way it did on root version.

**Comment by oSumAtrIX** [comment] 2022-12-01 00:16
Related/Dupe of #1091.

**Closed by oSumAtrIX** 2022-12-01 00:16 UTC
Labels: bug, question

**Comment by oSumAtrIX** [comment] 2022-12-01 00:18
If possible attach a full detailed recording of the following:

1. Uninstall the ReVanced Manager
2. Uninstall the patched YouTube app
3. Install the ReVanced Manager and patch it via the root variant, with any patch except for Microg

**Comment by YouSummoner** [comment] 2022-12-01 00:20
I'm giving updates properly, no need for recording, also don't have much data, sorry.

**Comment by oSumAtrIX** [comment] 2022-12-01 00:21
A recording is required, otherwise this issue can not be reopened.

**Comment by YouSummoner** [comment] 2022-12-01 01:03
> A recording is required, otherwise this issue can not be reopened.

Here, also, I found the culprit, it's the video-ads patch, do something please...😭

**Comment by oSumAtrIX** [comment] 2022-12-01 05:27
Did you try other patches as well?

**Comment by YouSummoner** [comment] 2022-12-01 08:04
Yes, but excluding video ads patch fixes the issue, other patches work fine.

**Comment by YouSummoner** [comment] 2022-12-01 08:24
Whaa, dunno how to, I'm on corvus OS 4.0 BTW, also heard that someone is having this issue on derpfest as well, if that helps...

**Comment by YouSummoner** [comment] 2022-12-01 08:38
I tried installing builds made using older version of patches, it's happening in those too, maybe it's a YouTube source side change, the video ads patch needs a urgent update please 🥺...

**Comment by oSumAtrIX** [comment] 2022-12-01 09:39
Unlikely, which version was the last which worked?

**Comment by YouSummoner** [comment] 2022-12-01 09:47
17.44.xx world before, but isn't working now

**Comment by oSumAtrIX** [comment] 2022-12-01 09:47
Please report back the exact version of the app and the patches which worked.

**Comment by YouSummoner** [comment] 2022-12-01 09:53
OMG, checked just now, I installed the official YouTube app without any patches, it plays ads and then crashes without playing the video, what fixes this behaviour is signing out of the account...

**Comment by YouSummoner** [comment] 2022-12-01 10:09
All patches except video-ads and sponsorblock are being applied successfully in YouTube v17.46.37 and the app isn't even crashing in this version, now all that's needed is to update those two patches for this new YouTube version and everything will work as intended...

**Comment by oSumAtrIX** [comment] 2022-12-01 10:16
Once again, please respond back with the exact version of the app and the patches which worked before. v17.46.37 was never supported.

**Comment by YouSummoner** [comment] 2022-12-01 10:19
v17.43.36 worked before, but now isn't, every version below v17.46.37 is having this issue right now when I checked. That's why I request to support v17.46.37 ASAP and get rid of all this headache... As I said only two patches video ads and sponsorblock are failing in this latest version.

**Comment by oSumAtrIX** [comment] 2022-12-01 10:20
You forgot to tell the version of the patches which v17.43.36 worked with.

**Comment by YouSummoner** [comment] 2022-12-01 10:21
I really don't remember that, but It was about a month ago, soooo

**Comment by oSumAtrIX** [comment] 2022-12-01 10:22
In that case do as suggested: https://github.com/revanced/revanced-patches/issues/1169#issuecomment-1333379398

**Comment by YouSummoner** [comment] 2022-12-01 10:30
Nah, YouTube base itself is causing the crashes, even without any patches on all older versions, I'd better just wait for revanced to support the newer version.

**Comment by oSumAtrIX** [comment] 2022-12-01 12:25
In any case, without the required information there will not be a fix for your issue.

**Comment by YouSummoner** [comment] 2022-12-01 13:33
The only fix is updating the patches for the latest YouTube version, cz it's not crashing or having any issues, forget about the previous versions of YouTube and their errors now.

**Comment by oSumAtrIX** [comment] 2022-12-01 14:56
This is not how it works, until we know which version worked last we wont know what change caused the error.
