### ISSUE TITLE
bug: can't swipe down to update homepage while 'remove general ads' is on

### ISSUE THREAD

**Issue by JimZiii** [revanced/revanced-patches#529] opened 2022-09-18 17:40 UTC
### Type

Other

### Bug description

I started getting this bug on the last few versions of the original youtube vanced, so I've had it for a while and I'm not sure what changed but it has carried over to revanced.

With 'remove general ads' on, I'm not able to swipe down to update the homepage.
When swiping down to update you'll get that circling arrow, indicating it'll update, but when I'm not able to update I'm not even getting that circling arrow at all.

I've had this issue on 2 different phones and both my brothers have the same problem so it's not just my phone.

### Steps to reproduce

Step 1. Activate 'remove generals ads'
Step 2. Go to home tab
Step 3. Swipe down to update

### Relevant log output

```shell
No logs
```

### Solution

If i deactivate 'remove general ads' I'm always able to update homepage by swiping down.

**Comment by oSumAtrIX** [comment] 2022-09-18 22:05
Dupe of #348.

**Closed by oSumAtrIX** 2022-09-18 22:05 UTC
Labels: bug
