### ISSUE TITLE
feat(patch): Possibility to turn off dimming on pause

### ISSUE THREAD

**Issue by xiaomist** [revanced/revanced-patches#547] opened 2022-09-20 11:59 UTC
### Application

Youtube

### Issue

Disable dimming on pause

### Patch

Please add the ability to turn off the dimming on pause

### Motivation

This feature is sorely lacking. Used it back in the days of Youtube Vanced

**Comment by oSumAtrIX** [comment] 2022-09-20 16:09
Dupe of #516.

**Closed by oSumAtrIX** 2022-09-20 16:09 UTC
Labels: patch-request
