### ISSUE TITLE
Twitter Patches

### ISSUE THREAD

**Issue by kbexit** [revanced/revanced-patches#2050] opened 2023-05-02 13:01 UTC
### Type

Error while patching

### Bug description

Failed to apply hide-ads: 'hide -ads' depends on 'json- hook' but the following error was raised: Unexpected integrations . Failed to apply hide-recommended-users: 'hide-recommended - Users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously

### Steps to reproduce

Just patching from start. Tried multiple versions, deleted manager, etc.

### Relevant log output

```shell
Failed to apply hide-ads: 'hide -ads' depends on 'json- hook' but the following error was raised: Unexpected integrations . Failed to apply hide-recommended-users: 'hide-recommended - Users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously
```

### Additional context

Revanced Manager (Latest Dev)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Vucko130** [comment] 2023-05-02 14:18
facing same problem

**Comment by kazimmt** [comment] 2023-05-02 19:39
Duplicate of #1981

**Closed** 2023-05-02 23:49 UTC
Labels: bug
