### ISSUE TITLE
feat(patch): improve search function

### ISSUE THREAD

**Issue by Orbitalstrike99** [revanced/revanced-patches#2211] opened 2023-05-20 21:36 UTC
### Application

patched youtube revanced android app

### Issue

it would be great if you guys able to improve search result by reducing unnecessary clutter and irrelevant result 

### Patch

a patch that allow you to hide multiple sections displayed when searching something and filter out the result, ie, for you section, previously watched section, people also watched section

### Motivation

those useless sections occupies at least half the search result if not more, offering either completely useless or irrelevant video suggestions that hinder the use of search function, probably easy to remove too if its defined by different section container

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-05-20 23:06
Can't find the issue but iirc it's a dupe of another, closing in favour of that.

**Closed by oSumAtrIX** 2023-05-20 23:06 UTC
Labels: patch-request
