### ISSUE TITLE
bug: ReVanced crashes when "Autoplay button" is enabled

### ISSUE THREAD

**Issue by DeNcHiK3713** [revanced/revanced-patches#344] opened 2022-08-16 13:17 UTC
### Type

Error at runtime

### Bug description

ReVanced crashes when "Autoplay button" is enabled.
YouTube version is 17.29.04
ReVanced cli version is 2.9.3
ReVanced patches version is 2.37.0
ReVanced integrations version is 0.33.1
cmd:
```bash
java -jar revanced-cli-all.jar \
 -a stock.apk \
 -c \
 -d device-name \
 -o revanced.apk \
 -b revanced-patches.jar \
 -m app-release-unsigned.apk \
 -e microg-support \
 --mount
```

### Steps to reproduce

1. Open YouTube ReVanced
2. Goto Settings - ReVanced settings - Layout settings
3. Enable "Autoplay button"
4. Open any video, then click on it to display controls

### Relevant log output

```shell
<<< log_count = 23 >>>
[08-16 15:41:17.046 8027:13354 D/StrictMode]
StrictMode policy violation: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
	at java.io.File.canRead(File.java:763)
	at com.xposed.XSupport.ʻ(XSupport.java:1222)
	at com.xposed.XSupport$15.beforeHookedMethod(XSupport.java:644)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.getApplicationInfo(Unknown Source:25)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7230)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7225)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSystemOrSameApp(NotificationManagerService.java:7167)
	at com.android.server.notification.NotificationManagerService.access$3200(NotificationManagerService.java:281)
	at com.android.server.notification.NotificationManagerService$10.enforceSystemOrSystemUIOrSamePackage(NotificationManagerService.java:3612)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabledForPackage(NotificationManagerService.java:2493)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabled(NotificationManagerService.java:2485)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1142)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
# via Binder call with stack:
	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2274)
	at android.os.Parcel.readExceptionCode(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1984)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabled(INotificationManager.java:2911)
	at android.app.NotificationManager.areNotificationsEnabled(NotificationManager.java:1072)
	at zc.g(PG:1)
	at xdb.X(PG:1)
	at fbr.d(PG:1)
	at yrc.b(PG:27)
	at cpx.Q(PG:6)
	at unr.t(PG:1)
	at uoo.H(PG:2)
	at uoo.rg(PG:2)
	at stb.a(PG:15)
	at stb.run(PG:21)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:17.047 8027:13354 D/StrictMode]
StrictMode policy violation: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at java.io.UnixFileSystem.getLastModifiedTime(UnixFileSystem.java:289)
	at java.io.File.lastModified(File.java:939)
	at com.xposed.XSupport.ʻ(XSupport.java:1225)
	at com.xposed.XSupport$15.beforeHookedMethod(XSupport.java:644)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.getApplicationInfo(Unknown Source:25)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7230)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7225)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSystemOrSameApp(NotificationManagerService.java:7167)
	at com.android.server.notification.NotificationManagerService.access$3200(NotificationManagerService.java:281)
	at com.android.server.notification.NotificationManagerService$10.enforceSystemOrSystemUIOrSamePackage(NotificationManagerService.java:3612)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabledForPackage(NotificationManagerService.java:2493)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabled(NotificationManagerService.java:2485)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1142)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
# via Binder call with stack:
	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2274)
	at android.os.Parcel.readExceptionCode(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1984)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabled(INotificationManager.java:2911)
	at android.app.NotificationManager.areNotificationsEnabled(NotificationManager.java:1072)
	at zc.g(PG:1)
	at xdb.X(PG:1)
	at fbr.d(PG:1)
	at yrc.b(PG:27)
	at cpx.Q(PG:6)
	at unr.t(PG:1)
	at uoo.H(PG:2)
	at uoo.rg(PG:2)
	at stb.a(PG:15)
	at stb.run(PG:21)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:17.324 8027:8027 W/YouTube]
Forcefully created overlay:hpn@4117f2a helper:Lazy@4ae211b view:null status: ....... {...}

[08-16 15:41:17.327 8027:8027 W/YouTube]
Forcefully created overlay:igq@f731264 helper:Lazy@f17ccd view:null status: ....... {✓..}

[08-16 15:41:17.942 8027:8027 E/YouTube]
Null interactionLoggingScreen found when removeInteractionLoggingScreen.

[08-16 15:41:18.930 8027:8027 W/YouTube]
Failed to set parent screen

[08-16 15:41:18.990 8027:8027 E/YouTube]
Null interactionLoggingScreen found when removeInteractionLoggingScreen.

[08-16 15:41:18.995 8027:8081 D/StrictMode]
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1545)
	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
	at java.io.FileInputStream.read(FileInputStream.java:310)
	at java.io.FileInputStream.read(FileInputStream.java:251)
	at stx.n(PG:1)
	at stx.h(PG:3)
	at stx.j(PG:1)
	at stx.a(PG:7)
	at achd.o(PG:5)
	at hnz.call(PG:29)
	at ardi.ai(PG:4)
	at aqpq.ah(PG:3)
	at aalx.run(PG:6)
	at adse.run(PG:2)
	at arpj.call(PG:2)
	at aetp.a(PG:1)
	at aesv.run(PG:4)
	at aetq.run(PG:1)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:18.999 8027:13354 D/StrictMode]
StrictMode policy violation: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
	at java.io.File.canRead(File.java:763)
	at com.xposed.XSupport.ʻ(XSupport.java:1222)
	at com.xposed.XSupport$15.beforeHookedMethod(XSupport.java:644)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.getApplicationInfo(Unknown Source:25)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7230)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7225)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSystemOrSameApp(NotificationManagerService.java:7167)
	at com.android.server.notification.NotificationManagerService.access$3200(NotificationManagerService.java:281)
	at com.android.server.notification.NotificationManagerService$10.enforceSystemOrSystemUIOrSamePackage(NotificationManagerService.java:3612)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabledForPackage(NotificationManagerService.java:2493)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabled(NotificationManagerService.java:2485)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1142)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
# via Binder call with stack:
	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2274)
	at android.os.Parcel.readExceptionCode(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1984)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabled(INotificationManager.java:2911)
	at android.app.NotificationManager.areNotificationsEnabled(NotificationManager.java:1072)
	at zc.g(PG:1)
	at xdb.X(PG:1)
	at fbr.d(PG:1)
	at yrc.b(PG:27)
	at cpx.Q(PG:6)
	at unr.t(PG:1)
	at uoo.H(PG:2)
	at uoo.rg(PG:2)
	at stb.a(PG:15)
	at stb.run(PG:21)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:19.000 8027:13354 D/StrictMode]
StrictMode policy violation: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at java.io.UnixFileSystem.getLastModifiedTime(UnixFileSystem.java:289)
	at java.io.File.lastModified(File.java:939)
	at com.xposed.XSupport.ʻ(XSupport.java:1225)
	at com.xposed.XSupport$15.beforeHookedMethod(XSupport.java:644)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.getApplicationInfo(Unknown Source:25)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7230)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSameApp(NotificationManagerService.java:7225)
	at com.android.server.notification.NotificationManagerService.checkCallerIsSystemOrSameApp(NotificationManagerService.java:7167)
	at com.android.server.notification.NotificationManagerService.access$3200(NotificationManagerService.java:281)
	at com.android.server.notification.NotificationManagerService$10.enforceSystemOrSystemUIOrSamePackage(NotificationManagerService.java:3612)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabledForPackage(NotificationManagerService.java:2493)
	at com.android.server.notification.NotificationManagerService$10.areNotificationsEnabled(NotificationManagerService.java:2485)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1142)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
# via Binder call with stack:
	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2274)
	at android.os.Parcel.readExceptionCode(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1984)
	at android.app.INotificationManager$Stub$Proxy.areNotificationsEnabled(INotificationManager.java:2911)
	at android.app.NotificationManager.areNotificationsEnabled(NotificationManager.java:1072)
	at zc.g(PG:1)
	at xdb.X(PG:1)
	at fbr.d(PG:1)
	at yrc.b(PG:27)
	at cpx.Q(PG:6)
	at unr.t(PG:1)
	at uoo.H(PG:2)
	at uoo.rg(PG:2)
	at stb.a(PG:15)
	at stb.run(PG:21)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:19.034 8027:8027 W/YouTube]
Failed to set parent screen

[08-16 15:41:19.040 8027:8027 W/YouTube]
Failed to set parent screen

[08-16 15:41:19.218 8027:8089 D/StrictMode]
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1545)
	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
	at java.io.FileInputStream.read(FileInputStream.java:310)
	at java.io.FileInputStream.read(FileInputStream.java:251)
	at stx.n(PG:1)
	at stx.h(PG:3)
	at stx.j(PG:1)
	at stx.a(PG:7)
	at stb.run(PG:10)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:19.233 8027:8089 D/StrictMode]
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1545)
	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
	at java.io.FileInputStream.read(FileInputStream.java:310)
	at java.io.FileInputStream.read(FileInputStream.java:251)
	at stx.n(PG:1)
	at stx.h(PG:3)
	at stx.j(PG:1)
	at stx.a(PG:7)
	at stb.run(PG:10)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:19.456 8027:8089 D/StrictMode]
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1545)
	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
	at java.io.FileInputStream.read(FileInputStream.java:310)
	at java.io.FileInputStream.read(FileInputStream.java:251)
	at stx.n(PG:1)
	at stx.h(PG:3)
	at stx.j(PG:1)
	at stx.a(PG:7)
	at stb.run(PG:10)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:20.302 8027:8027 W/YouTube]
Failed to set parent screen

[08-16 15:41:20.666 8027:8090 D/StrictMode]
StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1545)
	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
	at java.io.FileInputStream.read(FileInputStream.java:310)
	at java.io.FileInputStream.read(FileInputStream.java:251)
	at stx.n(PG:1)
	at stx.h(PG:3)
	at stx.j(PG:1)
	at stx.a(PG:7)
	at stb.run(PG:10)
	at npz.run(PG:5)
	at nqd.run(PG:23)
	at mzg.run(PG:6)
	at mzg.run(PG:33)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
	at java.lang.Thread.run(Thread.java:919)

[08-16 15:41:20.684 8027:8027 E/YouTube]
Null interactionLoggingScreen found when removeInteractionLoggingScreen.

[08-16 15:41:20.685 8027:8027 E/YouTube]
Null interactionLoggingScreen found when removeInteractionLoggingScreen.

[08-16 15:41:20.705 8027:8027 I/chatty]
uid=10583(com.google.android.youtube) identical 3 lines

[08-16 15:41:20.757 8027:8027 E/YouTube]
Media progress reported outside media playback: PLAYBACK_PENDING

[08-16 15:41:21.042 8027:8027 W/View]
requestLayout() improperly called by com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout{e07b30d V.E...... ......ID 0,0-1080,1800 #7f0b0a4a app:id/next_gen_watch_container_layout} during layout: running second layout pass

[08-16 15:41:21.667 8027:8027 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 8027
java.lang.IncompatibleClassChangeError: Found interface igm, but class was expected (declaration of 'igm' appears in /data/app/com.google.android.youtube-VelKqy64-G9Lz74WAfRJgw==/base.apk!classes4.dex)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.F(PG:52)
	at kow.a(PG:1)
	at dez.f(PG:1)
	at ike.y(PG:1)
	at ike.f(PG:1)
	at ike.x(PG:1)
	at ihp.a(PG:8)
	at aqtk.sX(PG:2)
	at arqr.e(PG:4)
	at arro.a(PG:1)
	at arro.b(PG:7)
	at arrp.sX(PG:6)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.Z(PG:12)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.P(PG:6)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.R(PG:2)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.U(PG:3)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.b(PG:4)
	at fff.b(PG:3)
	at sfn.run(PG:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by oSumAtrIX** [comment] 2022-08-16 13:29
Dupe of #263.

**Closed by oSumAtrIX** 2022-08-16 13:29 UTC
Labels: bug
