### ISSUE TITLE
feat: Disable swipe controls when 2 fingers are on the screen or when control menu is open, as well as removing the "ads in 1..." banner

### ISSUE THREAD

**Issue by kkellogg378** [revanced/revanced-patches#388] opened 2022-08-26 15:36 UTC
### Type

Functionality

### Issue

I've noticed when messing around with Swipe controls that sometimes vertical pinch-to-zoom gets conflicted with swipe controls and cant decide whether to zoom in/out or adjust the brightness. This isn't an issue when vertical pinch-to-zoom happens in the center of the screen.

Another thing I noticed is the volume/brightness slider still takes priority when the pause/skip buttons and the bottom cards for recommended videos are on the screen. Some users might want that (for some reason) but I would appreciate a toggle that disables that, as I often swipe up to see recommended videos and end up changing the brightness instead. 

Finally, the "ads in 3..." banner still shows up even when the ads are disabled. Ads dont play but the banner does

### Feature

Feature description: disabling swipe controls entirely when two fingers are on the screen (a method that Vanced used) and a toggle for disabling swipe controls when pause menu is open. This would make watching videos less frustrating and more practical. Removing the "ads in 3..." banner would make watching videos more immersive.

### Motivation

Currently would prefer to use Vanced over Revanced because Vanced's implementation of these three features make it feel a lot more robust. 

### Additional context

Tons of thanks to the devs who have fixed so many previous bugs! These were the last few I noticed

**Comment by oSumAtrIX** [comment] 2022-08-26 15:44
Dupe of #303.

**Closed by oSumAtrIX** 2022-08-26 15:44 UTC
Labels: feature-request
