### ISSUE TITLE
bug(youtube): Quick actions are hidden when the toggles are set to show

### ISSUE THREAD

**Issue by StefchoToqgata** [ReVanced/revanced-patches#2382] opened 2023-06-09 09:45 UTC
### Type

Other

### Bug description

YT ReVanced 18.19.35

Even after disabling the `Hide quick actions in fullscreen`, `Hide related videos in quick actions`, and the `Hide fullscreen panels` toggles, I am unable to see the buttons underneath the seekbar while watching a video in fullscreen. The seekbar is at the very bottom of the screen.

I am not spoofed to an older version.

### Steps to reproduce

1. Disable the following 3 toggles:

a) `Hide quick actions in fullscreen`

b) `Hide related videos in quick actions`

c)`Hide fullscreen panels`

2. Fully close and restart the app.

3. Open a video and tap to display the player controls and quick actions. Quick actions will not appear.

### Relevant log output

```shell
NA
```

### Screenshots or videos

https://mega.nz/file/I3ZCmIYI#T7k7Y55Ic9P9a9t0tly8wdFwfYHA4PrGQBecsYNSBf4

(video was too big to upload)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-06-09 09:56
I am unable to reproduce given the reproduction steps:

https://github.com/revanced/revanced-patches/assets/13122796/4c3bff78-0339-4a28-b0f7-289a0dc968d5

**Comment by StefchoToqgata** [comment] 2023-06-09 14:27
> I am unable to reproduce given the reproduction steps:
> 
>  Record_2023-06-09-11-54-54.mp4

Is there any other information I can provide you to fix it?

**Comment by oSumAtrIX** [comment] 2023-06-09 18:19
A complete and full recording of the entire process of patching the app and experiencing the issue

**Comment by johnconner122** [comment] 2023-06-18 15:46
If you have enabled `spoof-app-version`, then `quick-actions` will be hidden.

**Comment by cbizzle14** [comment] 2023-08-15 06:01
I have this issue on 18.23.35 When you first install revanced the settings are correct. You can see the quick actions in full screen. Once you restart revanced the buttons are gone. Doesn't matter if spoof version is on or off

**Comment by cbizzle14** [comment] 2023-08-15 06:11
@LisoUseInAIKyrios issue is still present

**Comment by johnconner122** [comment] 2023-08-15 06:13
I can reproduce this.
Steps:
1. Open a video, and pause it
2. Press back button to minimise the video
3. Press back button again to close the app
4. Open the app again, previous video will be in minimized state
5. Open that video and play it in fullscreen
6. Quick actions will be hidden.

**Comment by johnconner122** [comment] 2023-08-15 07:31
It's official YouTube bug, not revanced's.

**Closed** 2023-08-16 06:25 UTC
Labels: bug, waiting on author
