### ISSUE TITLE
feat(patch): youtube revanced swipe controls for playback speed

### ISSUE THREAD

**Issue by DovydasLatkauskas** [ReVanced/revanced-patches#1812] opened 2023-03-28 08:57 UTC
### Application

Revanced android app

### Issue

Currently switching playback speed takes 5 clicks/swipes, this way it would take 1

### Patch

Currently there is an option to swipe up or down on the side of the video to change video brightness or sound volume.

It would be nice if there was a setting for you to swipe up or down to alter video playback speed instead.

### Motivation

A lot of people are used to frequently switching playback speed on YouTube (ctrl + <, ctrl + > on desktop), this currently is pretty annoying to do on mobile.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-03-28 10:53
#1726

**Comment by KobeW50** [comment] 2023-08-17 21:01
> #1726

1726 is requesting custom playback speeds, but this request is asking to be able to change the video speed using the swipe controls

**Comment by YT-Advanced** [comment] 2023-08-18 02:48
But can u give an example position to swipe, because right and left have been used for brightness and volume swipe

**Comment by KobeW50** [comment] 2023-08-18 02:51
Either you can have the option to swap either one of the sides to use the speed controls instead of the volume/brightness controls.

Or you can swipe horizontally. Swiping left will lower the speed. Swiping right will raise the speed

**Comment by YT-Advanced** [comment] 2023-08-18 03:33
> Either you can have the option to swap either one of the sides to use the speed controls instead of the volume/brightness controls.
> 
> Or you can swipe horizontally. Swiping left will lower the speed. Swiping right will raise the speed

That sound nice

**Comment by KobeW50** [comment] 2023-08-18 18:29
Actually this issue is a dupe of https://github.com/ReVanced/revanced-patches/issues/1234

**Closed** 2023-08-19 13:32 UTC
Labels: patch-request
