### ISSUE TITLE
bug: The ads are still there on the tablet versions.

### ISSUE THREAD

**Issue by jhonnyn5** [revanced/revanced-patches#542] opened 2022-09-19 21:02 UTC
### Type

Error at runtime

### Bug description

The ads are still there on the tablet versions.  Even with the two patches to block ads applied

### Steps to reproduce

It happens more in playlists

### Relevant log output

```shell
Noone
```

**Comment by oSumAtrIX** [comment] 2022-09-19 21:19
Dupe of #206.

**Closed by oSumAtrIX** 2022-09-19 21:19 UTC
Labels: bug
