### ISSUE TITLE
feat: Option to set default start screen on YouTube

### ISSUE THREAD

**Issue by Jowat97** [ReVanced/revanced-patches#3361] opened 2023-12-03 15:39 UTC
### Feature description

There should be an option the set the default start screen for example to the subscription page. At the moment always the "home" screen will start, even if the button therefore was patched out. Unfortunately it is not a sufficient workaround to create a shortcut for your subscription page or making a long press on the YouTube App and click on "subscription". First, if a video is running in the background and you open the YouTube App, it will go back to the video. However, if you make a subscription shortcut and click on it, while a video is still playing in PIP mode, the video will not open, which should be the default behavior, instead the app will totally bug and open the subscription page in PIP mode.

With a patch to set the default start page, all named problems would be solved. It will always open the desired start page and if a video is running in the background or PIP mode, it will open the video. Also no additional shortcuts or long press are anymore necessary. 

@oSumAtrIX Please just don't close this issue as duplicate from #2273 #2139 #2305 
As already mentioned, there is at the moment no sufficient workaround, especially if you play a video in background or PIP mode. And with the amount as requests there is a clear demand for this patch. Extended already has this patch, which could be ported. I am also willing to help. But please just don't close this as a duplicate, people would really love this!

### Motivation

There is at the moment no other way to set the default screen. And even if you patch out the Home button, it will still open it always as default page. This is not a very elegant way. There is a high demand for this patch and extended already created one, which could be ported.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2023-12-03 15:45
Dupe of https://github.com/ReVanced/revanced-patches/issues/2888.

**Closed by oSumAtrIX** 2023-12-03 15:45 UTC
Labels: Feature request

**Comment by Jowat97** [comment] 2023-12-03 15:48
@oSumAtrIX As mentioned in the issue, there is no working workaround for it, especially with PIP mode. So why exactly do you don't want this patch to be included?

**Comment by oSumAtrIX** [comment] 2023-12-03 15:48
I closed this issue as a duplicate of another one. Please don't open duplicate issues and check the "I did not open a duplicate post" checkmark.
