### ISSUE TITLE
bug: Auto repeat stays on even after disabling 

### ISSUE THREAD

**Issue by Amby713** [revanced/revanced-patches#350] opened 2022-08-17 23:56 UTC
### Type

Error at runtime

### Bug description

The videos repeat automatically without the option not being enabled

I could exclude the auto repeat patch,  but there are times when I want them to and should be able to toggle it back on. 

### Steps to reproduce

Patch with the latest patches

Run YouTube

Watch a video to the end and it repeats

Go to settings > revanced settings  > miscellaneous  > cycle auto repeat toggle in and off

Watch new video,  at the end it repeats

### Relevant log output

```shell
N/a
```

**Comment by oSumAtrIX** [comment] 2022-08-18 00:39
Dupe of #146.

**Closed by oSumAtrIX** 2022-08-18 00:39 UTC
Labels: bug
