### ISSUE TITLE
feat: Youtube Landscape left and right rotation during locked rotation. 

### ISSUE THREAD

**Issue by UraniumDonut** [revanced/revanced-patches#470] opened 2022-09-12 16:28 UTC
### Type

Functionality

### Issue

On regular Youtube and Youtube Vanced the following behavior is observed: 
If auto-rotation is enabled, the app still rotates between ROTATION_90 and ROTATION_270.
Revanced is currently fixed to ROTATION_90. 

### Feature

Change behavior to respect landscape orientation during locked rotation or add a toggle to switch between the two rotations. 

### Motivation

Inconvenience to users, which have to use the phone in a certain landscape orientation. 
Example Reasons: 

- Charger is in an orientation that requires an other rotation
- Loudspeaker is in another orientation that requires an other rotation

**Comment by oSumAtrIX** [comment] 2022-09-12 16:32
Dupe of #426.

**Closed by oSumAtrIX** 2022-09-12 16:32 UTC
Labels: feature-request
