### ISSUE TITLE
bug: unexpected scroll to top on home screen

### ISSUE THREAD

**Issue by GDNoob320** [revanced/revanced-patches#1188] opened 2022-12-03 10:56 UTC
### Type

Error at runtime

### Bug description

YouTube recommendation scrolls to top after using pip mode. 

### Steps to reproduce

Step 1:Use Yt version 17.36.37
Step 2: use these patches{"com.vanced.android.youtube":["client-spoof"],"com.google.android.youtube":["always-autorepeat","client-spoof","comments","custom-branding","custom-video-buffer","custom-video-speed","debugging","disable-auto-captions","disable-auto-player-popup-panels","disable-fullscreen-panels","disable-startup-shorts-player","disable-zoom-haptics","downloads","enable-wide-searchbar","general-ads","hdr-auto-brightness","hide-album-cards","hide-artist-card","hide-autoplay-button","hide-captions-button","hide-create-button","hide-crowdfunding-box","hide-email-address","hide-endscreen-cards","hide-info-cards","hide-my-mix","hide-time-and-seekbar","hide-video-buttons","hide-watch-in-vr","hide-watermark","microg-support","minimized-playback","old-quality-layout","premium-heading","remember-video-quality","remove-player-button-background","return-youtube-dislike","seekbar-tapping","sponsorblock","swipe-controls","tablet-mini-player","video-ads","theme","hide-shorts-button"]}
Step 3: install using non root
Step 4: try scrolling a bit then open a video
Step 5: use pip mode
Step 6: open it again
Step 7: done the recommendation scrolls up top

### Relevant log output

```shell
--------- beginning of system
12-02 17:57:28.928 30870 30870 W Looper  : Slow Looper main: Long Msg: seq=229 plan=17:57:27.726  late=0ms wall=1202ms running=109ms runnable=4ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
12-02 17:57:58.088 30870 30870 W Looper  : Slow Looper main: Long Msg: seq=395 plan=17:57:56.553  late=8ms wall=1527ms running=175ms runnable=14ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
12-02 17:58:07.638 30870 30870 W Looper  : Slow Looper main: Long Msg: seq=401 plan=17:58:06.114  late=1ms wall=1523ms running=166ms runnable=15ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
12-02 18:03:05.973 30870 30870 I Timeline: Timeline: Activity_launch_request time:16834021
12-02 21:26:18.913 11775 11775 W Looper  : Slow Looper main: Long Msg: seq=85 plan=21:26:17.907  late=0ms wall=1006ms running=75ms runnable=3ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
12-03 16:12:41.873  8906  8906 W Looper  : Slow Looper main: Long Msg: seq=99 plan=16:12:40.663  late=39ms wall=1170ms running=100ms runnable=6ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
12-03 16:12:41.905  8906  8906 W Looper  : Slow Looper main: doFrame is 1201ms late because of 8 msg, msg 6 took 1170ms (seq=99 running=100ms runnable=6ms late=39ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
12-03 16:12:47.467  8906  8906 I Timeline: Timeline: Activity_launch_request time:52093227
12-03 16:19:06.214  8906  8906 I Timeline: Timeline: Activity_launch_request time:52471974
```

### Screenshots or videos

https://user-images.githubusercontent.com/89239362/205437383-9af33fde-ae88-4bd0-9345-205f20a55308.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment] 2022-12-05 12:26
Can confirm this behaviour exist. I have disabled OG YT so I cannot cross-check, even if I enabled it I dont have premium so no PiP for me.

**Comment by ILoveOpenSourceAppications** [comment] 2023-02-11 17:36
@SodaWithoutSparkles, do you still have this issue?

**Comment by SodaWithoutSparkles** [comment] 2023-02-11 17:39
Affirmative.

**Comment by oSumAtrIX** [comment] 2023-02-11 17:42
Please check with stock YouTube. If it does not happen there, exclude patches until the error is gone, report back which one caused it.

**Comment by SodaWithoutSparkles** [comment] 2023-02-11 17:57
The problem is, as mentioned in https://github.com/revanced/revanced-patches/issues/1188#issuecomment-1337259301, I dont have premium. Thats why I am here. I have therefore created a [reddit post](https://www.reddit.com/r/revancedapp/comments/10zti5w/anyone_that_have_revanced_and_premium_can_help_us/) asking for help.

**Comment by oSumAtrIX** [comment] 2023-02-11 18:00
Report back once you can answer the request please.

**Comment by oSumAtrIX** [comment] 2023-02-11 23:09
Closing due to https://www.reddit.com/r/revancedapp/comments/10zti5w/anyone_that_have_revanced_and_premium_can_help_us/j85kz2v/

**Closed by oSumAtrIX** 2023-02-11 23:09 UTC
Labels: bug, question
