### ISSUE TITLE
feat(patch): Patches for Facebook App

### ISSUE THREAD

**Issue by proxykingdev** [revanced/revanced-patches#894] opened 2022-10-29 06:10 UTC
### Application

Facebook Android

### Issue

Remove Ads 

### Patch

Around 2017 there was a modded ad free version of Facebook on XDA. it's no longer maintained. it would be great to have Revanced patches support for Facebook. 

### Motivation

Most Popular App. Filled with nasty ads. frustrating to use. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment] 2022-10-29 07:16
You didn't search the issues. Dupe of #702/#622.

**Closed** 2022-10-29 12:27 UTC
Labels: patch-request
