### ISSUE TITLE
bug(YouTube): Custom playback speed, old quality menu, and remember speed/quality patches do not work on tablet devices 

### ISSUE THREAD

**Issue by xDARKxDEVILx** [ReVanced/revanced-patches#2606] opened 2023-07-09 20:48 UTC
### Type

Error at runtime

### Bug description

I patched YouTube version 18.32.39 successfully on my phone and everything worked correctly
Then i shared the patched app to my tablet and had these issues:

1- return old video quality menu patch doesn't  dispite being selected and the new one appeared which you get in stock

2- more video speed menu didn't appear dispite being selected and only got the stock YouTube video speeds
Also, changing the speed in player doesn't work, and the only way to change it is through the settings

### Steps to reproduce

Patch yt version 18.32.39 on my phone successfully and got it working perfectly fine

Share it to my tablet 

Have issues 🙂

# Temporary fix:
### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by xDARKxDEVILx** [comment] 2023-07-09 21:54
> Did the custom speeds work on your tablet with prior versions of ReVanced? Or is this only with the latest release?

Speed and quality work on version 18.19.35 on my tablet and everything else

**Comment by xDARKxDEVILx** [comment] 2023-07-09 21:56
> Try patching 18.20.39 and see if anything is different.

Alright i will try that once i get to know how to use cli which seems good for now will reply when i test it

**Comment by oSumAtrIX** [comment] 2023-07-09 22:00
The issue is that Tablets use a different layout. Thus, the current patch locations aren't sufficient. A patch for tablets can be added.

**Comment by xDARKxDEVILx** [comment] 2023-07-09 22:05
> The issue is that Tablets use a different layout. Thus, the current patch locations aren't sufficient. A patch for tablets can be added.

Yeah i noticed that in the new version the quality and speed menu place changed from the previous one after pressing them so maybe that is it, but is what causes home page to have only 1 or 2 vidoes showen in  horizontal layout known as well?

**Comment by xDARKxDEVILx** [comment] 2023-07-10 13:38
Since you can't change package name now without crashing, i will just try version 18.20.39 now

**Comment by xDARKxDEVILx** [comment] 2023-07-10 14:24
> Try patching 18.20.39 and see if anything is different.

Tested 18.20.39 on my tablet and it is perfectly fine for now

**Comment by xDARKxDEVILx** [comment] 2023-07-10 14:36
Ok after further testing 3 of the mentioned issues was solved and the only one that didn't is having missing video cards in home page sometimes i have 1 or 2 videos instead of the normal 3

**Comment by xDARKxDEVILx** [comment] 2023-07-10 16:33
> The number of video cards is probably a change by YouTube. You can try unpatched 18.20.39 and if it's the same then it's a YouTube thing.

I tried stock YouTube and never had this issue but i will try like 10 other times to see as it doesn't always appear

**Comment by xDARKxDEVILx** [comment] 2023-07-10 16:48
> The number of video cards is probably a change by YouTube. You can try unpatched 18.20.39 and if it's the same then it's a YouTube thing.

Tested stock YouTube so many times and video cards were always 3 no matter what version i use, the video card issue only exists at patched versions after 18.19.35

**Comment by xDARKxDEVILx** [comment] 2023-07-11 00:33
> If the issue only happens to patched YouTube, then it must be caused by a patch or combination of patch settings.
> 
> Can try repatching and removing patches until the problem goes away. If you figure out what patch causes the issue, then create a new bug issue as this is off topic from this thread.

Alright will so that tomorrow

**Comment by xDARKxDEVILx** [comment] 2023-07-11 23:09
So i tried to see what patch caused video cards to be missing with the new patches version but I didn't have the problem so i guess it is solved with both versions

**Comment by xDARKxDEVILx** [comment] 2023-07-11 23:10
Now, what is missing  is a patch to support old vidoe quality menu and also more video speeds in version 18.23.35

**Comment by xDARKxDEVILx** [comment] 2023-07-25 19:48
> Just to be clear to others:
> 
> If you are using ReVanced on a tablet, then you should repatch YouTube 18.20.39 (which is a supported version), and then custom speed and old video quality menus will work correctly.

It would be nice if next time you guys upgrade the suggested version to consider tablet users as well 🙂

**Comment by xDARKxDEVILx** [comment] 2023-08-11 21:49
I removed content from my issue and also content that was either resloved my YouTube or was skill issue of mine

**Comment by xDARKxDEVILx** [comment] 2023-08-28 17:18
I updated this issue for the new version of YouTube ReVanced, hopefully someone actually spares the time to work on this

**Comment by xDARKxDEVILx** [comment] 2023-08-28 18:03
> `18.20.39` no longer supports all patches (ReturnYouTubeDislikes does not work, for example).
> 
> For now, a better work around is:
> 
> * Patch `18.32.39`
> * go to `ReVanced settings -> Misc -> import / export`
> * edit the existing spoof target (if this entry is not present, then paste this text as the first line of the settings):
>   `"spoof_app_version_target": "18.20.39",`
> * restart app
> * enable `ReVanced Settings -> Layout -> Spoof app version`
> * restart app
> * navigate to `ReVanced Settings -> Layout -> Spoof app target` and verify it says `18.20.39` in the summary (the custom version will not show up in the selection menu, but it is active)
> 
> Custom speed and old quality menu should now work correctly. This should only be used as temporary fix until the speed/quality patches are updated for tablets.
> 
> Alternatively you can spoof to any of the existing 17.x or 16.x targets and that will also fix this.

That worked, hopefully no other patch breaks with that change, i will update the solution in my issue later

**Comment by xDARKxDEVILx** [comment] 2023-08-28 20:26
Oops

**Comment by DH-Mustaang** [comment] 2023-09-05 09:19
> * navigate to `ReVanced Settings -> Layout -> Spoof app target` and verify it says `18.20.39` in the summary (the custom version will not show up in the selection menu, but it is active)
> 
> Custom speed and old quality menu should now work correctly. This should only be used as temporary fix until the speed/quality patches are updated for tablets.

For me it says spoofed to 18.20.39 but I can't use either the quality or the speed menu.
The quality menu is grayed out and the speed menu is not even present...

**Comment by inotia00** [comment] 2023-09-05 11:28
valid fix has been applied in my repo
https://github.com/inotia00/revanced-patches/commit/16c34b78f0d2a14fb73e6c330c7f702075ad77e3
https://github.com/inotia00/revanced-integrations/commit/98eeb1c92ec31fb090598104bebdf6d7d0644915

I hope this commit helps people who can edit the source code

**Comment by azsde** [comment] 2023-09-05 14:45
@inotia00 does your fix also apply to custom playback speeds ?

**Comment by inotia00** [comment] 2023-09-05 17:16
> @inotia00 does your fix also apply to custom playback speeds ?

![yep](https://github.com/ReVanced/revanced-patches/assets/108592928/4f1f0db4-4415-4d82-ad2a-f4703c501864)

yep

**Comment by xDARKxDEVILx** [comment] 2023-09-19 13:10
Thanks to @inotia00 and @LisoUseInAIKyrios for fixing this ❤️
I hope the mention doesn't bother any of you 😅

**Closed** 2023-10-04 23:37 UTC
Labels: Bug

**Comment by xDARKxDEVILx** [comment] 2023-10-19 22:15
@oSumAtrIX could this issue be reopened?
The patch didn't fix it and i updated the issue

**Comment by oSumAtrIX** [comment] 2023-10-19 22:16
Open a new issue with all necessary details

**Comment by xDARKxDEVILx** [comment] 2023-10-19 22:51
> @xDARKxDEVILx the issue in your screenshot was fixed on dev release.
> 
> Patch using dev release and CLI tools and a computer, or wait until the fix comes to regular release and for now turn on app version spoofing and use 18.20.39 spoof target.

Yeah, that is what i do now, thanks though ❤️
