### ISSUE TITLE
Relay version 12 support

### ISSUE THREAD

**Issue by Toiletmason** [ReVanced/revanced-patches#3360] opened 2024-06-21 02:20 UTC
### Feature description

Would like to be able to use the new version of Relay.

### Motivation

Would like to use the new interface, but also not pay reddit for the use of its api. Would like to be able to our personal keys like the other apps. Version 10 still works, but it won't forever. 

### Acknowledgements

- [ ] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Bceez** [comment] 2024-06-21 04:18
Duplicate of https://github.com/ReVanced/revanced-patches/issues/2532

**Closed** 2024-06-21 06:04 UTC
Labels: Feature request
