### ISSUE TITLE
bug: Youtube crash, when not using YouTube 

### ISSUE THREAD

**Issue by ammlr** [revanced/revanced-patches#418] opened 2022-09-01 04:47 UTC
### Type

Error at runtime

### Bug description

I'm not opening YouTube, suddenly pop up YouTube crash

### Steps to reproduce

I use AppErrorTracking https://github.com/KitsunePie/AppErrorsTracking

### Relevant log output

```shell
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: 2107113SG
[Display]: SKQ1.211006.001 test-keys
[Android Version]: 12
[API Version]: 31
[Package Name]: com.google.android.youtube
[Error Type]: Jvm
[Crash Time]: 1 Sep 2022 11.29.43
[Stack Trace]:
java.lang.ExceptionInInitializerError
	at xuy.<init>(PG:7)
	at xbk.c(PG:15)
	at xbk.a(PG:1)
	at aqim.a(PG:1)
	at aqil.a(PG:2)
	at aaxm.a(PG:1)
	at aqim.a(PG:1)
	at aqil.a(PG:2)
	at lei.p(PG:2)
	at zqz.d(PG:1)
	at lef.a(PG:1)
	at ldw.<init>(PG:10)
	at ldw.M(PG:1)
	at com.google.android.apps.youtube.embeddedplayer.service.service.jar.ApiPlayerService.<init>(PG:34)
	at com.google.android.apps.youtube.embeddedplayer.service.service.jar.ApiPlayerFactoryService$1.run(PG:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8118)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at app.revanced.integrations.settings.SettingsEnum.getBoolean(SettingsEnum.java:227)
	at app.revanced.integrations.utils.LogHelper.debug(LogHelper.java:12)
	at app.revanced.integrations.sponsorblock.PlayerController.setCurrentVideoTime(PlayerController.java:135)
	at app.revanced.integrations.sponsorblock.PlayerController.setCurrentVideoTimeHighPrecision(PlayerController.java:227)
	at xow.<init>(Unknown Source:0)
	at xow.a(PG:1)
	at xow.<clinit>(PG:2)
	... 23 more
```

### Screenshots or videos

![Screenshot_2022-09-01-11-47-29-403_com fankes apperrorstracking](https://user-images.githubusercontent.com/30746607/187833449-b8324357-33ed-497b-aa07-942a68dd11f0.jpg)

**Comment by oSumAtrIX** [comment] 2022-09-01 04:51
Please include proper reproduction steps.

**Comment by shekhawat2** [comment] 2022-09-01 15:24
> Please include proper reproduction steps.

It happens when trying to play a video from Play Store.

**Comment by oSumAtrIX** [comment] 2022-09-01 16:08
Related to/dupe of #368.

**Closed by oSumAtrIX** 2022-09-01 16:08 UTC
Labels: bug, question
