### ISSUE TITLE
'YT Music ReVanced/Tablet Mode' is possible??

### ISSUE THREAD

**Issue by arghya339** [revanced/revanced-patches#1054] opened 2022-11-16 11:17 UTC
### Type

Functionality

### Issue

![IMG_20221116_161803](https://user-images.githubusercontent.com/118043691/202166566-973c1839-72ee-4c7b-bb39-489a50514c1d.jpg)

Galaxy Fold, Galaxy Flip, Glaxy Tablet, DIY Raspberry Pi Android TV, ChromeBook, Android sub-system on Windows 11 has big screen it's help batter viewing experience!
![Screenshot_2022-11-16-16-15-03-046_com vanced android apps youtube music](https://user-images.githubusercontent.com/118043691/202166487-f0d1f18d-8042-4cbf-ad1b-40e5f1ee2620.jpg)
![Screenshot_2022-11-16-16-16-01-788_com vanced android apps youtube music](https://user-images.githubusercontent.com/118043691/202166503-7f421644-fbeb-4d39-9a2d-cc343a512b93.jpg)

### Feature

Tablet Mode: Unlocks Landscape Mode(YT Music) 

### Motivation

YT Music Vanced has 'Tablet Mode' integration. But ReVanced use Vanced integration.
![Screenshot_2022-11-16-16-34-20-087-edit_com kiwibrowser browser](https://user-images.githubusercontent.com/118043691/202165984-f1579e84-fa50-418f-9bc4-a5d240196bd6.jpg)
*So, is possible to use 'Tablet Mode' integration in TY Music ReVanced??

### Additional context

NA

**Comment by oSumAtrIX** [comment] 2022-11-16 11:28
Dupe of #580.

**Closed by oSumAtrIX** 2022-11-16 11:28 UTC
Labels: feature-request

**Comment by ILoveOpenSourceApplications** [comment] 2023-07-13 16:48
#580
