### ISSUE TITLE
bug: YouTube 17.36.37 crashes on launch with patches custom-playback-speed and custom-video-buffer applied

### ISSUE THREAD

**Issue by philklc** [revanced/revanced-patches#569] opened 2022-09-21 07:06 UTC
### Type

Error at runtime

### Bug description

Running a patched YouTube 17.36.37 with all default patches applied crashes immediately on launch.

### Steps to reproduce

Apply all applicable patches to YouTube 17.36.37.
ReVanced CLI 2.11.1
ReVanced Patches 2.64.1
ReVanced Integrations 0.40.0
Command line used:
`java -jar revanced-cli-2.11.1-all.jar -a youtube_17.36.37.apk -b revanced-patches-2.64.1.jar -c -m app-release-unsigned.apk -o revanced.apk`

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: app.revanced.android.youtube, PID: 2870
java.lang.NoClassDefFoundError: com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel
       at urn.b(PG:1)
       at xhw.O(PG:1)
       at ehv.c(PG:109)
       at ehv.a(PG:37)
       at aqkt.a(PG:1)
       at ehv.c(PG:110)
       at ehv.a(PG:37)
       at aqkt.a(PG:1)
       at ehv.c(PG:111)
       at ehv.a(PG:37)
       at aqkt.a(PG:1)
       at ehf.b(PG:90)
       at ehf.a(PG:34)
       at aqkt.a(PG:1)
       at ehg.r(PG:1)
       at zrq.d(PG:1)
       at ehw.bt(PG:1)
       at ehv.n(PG:93)
       at ehv.a(PG:31)
       at aqkt.a(PG:1)
       at ehv.m(PG:1)
       at ehv.a(PG:32)
       at aqkt.a(PG:1)
       at ehw.aK(PG:1)
       at ehw.aJ(Unknown Source:0)
       at ehv.m(PG:6)
       at ehv.a(PG:32)
       at aqla.a(PG:1)
       at ehf.b(PG:3)
       at ehf.a(PG:34)
       at aqkt.a(PG:1)
       at ehg.i(PG:1)
       at zrk.d(PG:1)
       at ehw.bi(PG:1)
       at ehw.bh(Unknown Source:0)
       at ehv.n(PG:19)
       at ehv.a(PG:31)
       at aqkt.a(PG:1)
       at ehw.dM(PG:1)
       at ehv.m(PG:37)
       at ehv.a(PG:32)
       at aqkt.a(PG:1)
       at ehv.m(PG:51)
       at ehv.a(PG:32)
       at aqkt.a(PG:1)
       at wld.a(PG:1)
       at uvz.g(PG:3)
       at hox.n(PG:6)
       at ejj.run(PG:22)
       at afat.execute(PG:1)
       at com.google.android.apps.youtube.app.application.Shell_HomeActivity.l(PG:6)
       at ejj.run(PG:25)
       at syy.run(PG:7)
       at sza.m(PG:9)
       at sza.n(PG:10)
       at emv.onCreate(PG:16)
       at com.google.android.apps.youtube.app.application.Shell_HomeActivity.onCreate(PG:6)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7669)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.VerifyError: Verifier rejected class com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel: int com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.r() failed to verify: int com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.r(): [0x12] instance field access on object that has non-reference type Conflict (declaration of 'com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel' appears in /data/app/~~FH0zPuoHvpfmMB02AfzxVA==/app.revanced.android.youtube-GokW_Ipnh8kIYO8u1q1Dcw==/base.apk!classes2.dex)
       at urn.b(PG:1)
       at xhw.O(PG:1)
       at ehv.c(PG:109)
       at ehv.a(PG:37)
       at aqkt.a(PG:1)
       at ehv.c(PG:110)
       at ehv.a(PG:37)
       at aqkt.a(PG:1)
       at ehv.j(PG:96)
       at ehv.a(PG:35)
       at aqkt.a(PG:1)
       at ejf.run(PG:1)
       at syy.run(PG:7)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at sci.run(PG:55)
       at java.lang.Thread.run(Thread.java:923)
```

### Solution

Exclude custom-playback-speed and custom-video-buffer patches when patching.
`java -jar revanced-cli-2.11.1-all.jar -a youtube_17.36.37.apk -b revanced-patches-2.64.1.jar -c -m app-release-unsigned.apk -o revanced.apk -e custom-playback-speed -e custom-video-buffer`

The patched YouTube client no longer crashed on launch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by koko115** [comment] 2022-09-21 07:21
Sponsorblock to no working

**Comment by DerivativeOfLog7** [comment] 2022-09-21 17:39
Fixed by latest release

**Closed** 2022-09-21 17:47 UTC
Labels: bug

**Comment by What-Zit-Tooya** [comment] 2022-09-23 00:23
CUstom playback speed error on patching:
[builder] INFO: Decoding resources
[builder] INFO: Reading dex files
[builder] INFO: Merging .\revanced\revanced-integrations-v0.41.2.apk
[builder] INFO: Skipping theme, reason: manually excluded
[builder] INFO: Skipping enable-debugging, reason: manually excluded
[builder] WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
[builder] WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] INFO: Skipping compact-header, reason: excluded by default
[builder] WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
[builder] WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
[builder] INFO: custom-branding succeeded
[builder] INFO: premium-heading succeeded
[builder] INFO: old-quality-layout succeeded
[builder] INFO: hide-autoplay-button succeeded
[builder] SEVERE: sponsorblock failed:
[builder] app.revanced.patcher.patch.PatchResultError
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
[builder] at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
[builder] at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
[builder] at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
[builder] at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161)
[builder] at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.NullPointerException
[builder] at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:329) at app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch.SponsorBlockBytecodePatch.execute(SponsorBlockBytecodePatch.kt:41) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326) ... 16 more
[builder] INFO: hide-watermark succeeded
[builder] INFO: disable-fullscreen-panels succeeded
[builder] INFO: hide-create-button succeeded
[builder] INFO: hide-shorts-button succeeded
[builder] INFO: tablet-mini-player succeeded
[builder] INFO: hide-time-and-seekbar succeeded
[builder] INFO: return-youtube-dislike succeeded
[builder] INFO: disable-auto-captions succeeded
[builder] INFO: disable-auto-player-popup-panels succeeded
[builder] INFO: enable-wide-searchbar succeeded
[builder] INFO: hide-cast-button succeeded
[builder] INFO: video-ads succeeded
[builder] INFO: general-ads succeeded
[builder] INFO: hide-infocard-suggestions succeeded
[builder] INFO: seekbar-tapping succeeded
[builder] INFO: downloads succeeded
[builder] INFO: swipe-controls succeeded
[builder] INFO: microg-support succeeded
[builder] INFO: settings succeeded
[builder] INFO: minimized-playback succeeded
[builder] INFO: custom-video-buffer succeeded
[builder] SEVERE: custom-playback-speed failed: app.revanced.patcher.patch.PatchResultError
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
[builder] at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
[builder] at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[builder] at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
[builder] at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.misc.customplaybackspeed.patch.CustomPlaybackSpeedPatch.execute(CustomPlaybackSpeedPatch.kt:113) at app.revanced.patches.youtube.misc.customplaybackspeed.patch.CustomPlaybackSpeedPatch.execute(CustomPlaybackSpeedPatch.kt:27) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326) ... 16 more
