### ISSUE TITLE
Can't search on TikTok with all the patches

### ISSUE THREAD

**Issue by r0xANDt0l** [revanced/revanced-patches#560] opened 2022-09-20 21:18 UTC
### Type

Error at runtime

### Bug description

When you try to search for something on TikTok, is spits out an error saying you need to log in to search, but even if you log in, you can't search

### Steps to reproduce

1) Go to the Friends tab
1) Click on the search button
1) Search for something
1) Error

### Relevant log output

```shell
idk where to find it ;-;
```

### Screenshots or videos

![Screenshot_2022-09-20-23-10-30-65_f69139cffc4d135a71392e13634f144a](https://user-images.githubusercontent.com/41841903/191365251-b5bd67d3-09c7-4b75-b296-0ddf30e4091f.jpg)

**Comment by oSumAtrIX** [comment] 2022-09-20 21:47
Dupe of #494.

**Closed by oSumAtrIX** 2022-09-20 21:47 UTC
Labels: bug
