### ISSUE TITLE
bug: [Action buttons patch] - The setting "Hide share button" has double functionality

### ISSUE THREAD

**Issue by quadraticfunction** [revanced/revanced-patches#1198] opened 2022-12-04 19:02 UTC
### Type

Other

### Bug description

While I was discovering the Revanced Settings, I noticed the setting "Hide action buttons". I tried out a few switches and saw that for premiered videos, the live chat button was disappearing when "Hide share button" was enabled, it also happened with live videos. Apart from that, the option does what it has to do.

Also, another thing that calls my attention is that the share button is not available in Live and Premiered videos, even if "Hide share button" setting is disabled, it only shows the live chat button.

Finally, there's kind of asymmetrical gaps between some action buttons, but there's already an issue for that (just mentioning because it's related to the action buttons)

### Steps to reproduce

Play previously premiered videos, look if the "Live chat" button is visible, go to Revanced settings > Layout > Hide action buttons > Enable "Hide share button", go back to the video, voila, button's gone.

Repeat the steps above with live videos and videos with the share button available (also notice that the share button is not shown in videos with live chat button, as I previously said)

### Relevant log output

```shell
This is marked as mandatory but:

1. I don't think a log would be useful for this kind of thing, plus it's very clear and easy to reproduce
2. Even if debugging logs are enabled, there's no info about the action buttons
```

### Screenshots or videos

https://user-images.githubusercontent.com/104278947/205509949-4d591541-c235-49d2-92be-6fcd84c8a2a7.mp4

https://user-images.githubusercontent.com/104278947/205509951-329eb658-5cca-4dfd-a42f-526bca72bdd5.mp4

### Solution

Removing this double functionality from the "Hide share button" and adding a new setting: "Hide live chat button", and also making the share button appear on Live/Premiered videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-12-04 19:04
Dupe of #1195, #767.

**Closed by oSumAtrIX** 2022-12-04 19:04 UTC
Labels: bug
