### ISSUE TITLE
bug: Pause/Play and Skip controls not disappearing when a youtube video is open

### ISSUE THREAD

**Issue by kkellogg378** [revanced/revanced-patches#338] opened 2022-08-15 01:41 UTC
### Type

Cosmetic

### Bug description

Basically the pause/skip video buttons that pop up when you tap on a playing video wont disappear. The only way to fix this problem is to close out of the video and reopen it. 

Also a feature request would be to disable swipe controls while these controls are on display and also in the "swipe up" menu where you can see recommended videos while in fullscreen

### Steps to reproduce

Step 1: Play a Video
Step 2: Tap the screen
Step 3: Tap Video title to go back to watching the video
Step 4: Tap the screen again

### Relevant log output

```shell
n/a
```

### Screenshots or videos

![Screenshot_20220814-213812_YouTube](https://user-images.githubusercontent.com/32850733/184564064-cbeaf756-7db8-4fb4-a239-7a33c8ce903b.jpg)

**Comment by oSumAtrIX** [comment] 2022-08-15 02:13
Dupe of #322.

**Closed by oSumAtrIX** 2022-08-15 02:13 UTC
Labels: bug
