### ISSUE TITLE
Antitracker from VPN stops history from saving, doesn't happen in 19.09 yt version

### ISSUE THREAD

**Issue by mockinbirdy** [ReVanced/revanced-patches#3520] opened 2024-08-09 06:32 UTC
### Bug description

The "recommended" 19.16. version is awful as it is, it freezes and crashes, but the fact is doesn't save history now with a quite frankly feeble antitracker from vpn is ridiculous. 

I have an old installation of 19.09 (april 2024) which works absolutely amazing, saves history (with the very same vpn being on) and doesn't freeze, but I didn't save a patched file and now if I try to patch 19.09 with the new revanced manager 1.20+ version, it saves a bugged apk. 

It all has something to do with the patches and the way the updated manager patches apks.

Why not let people use old apks if it's been proved over and over that they work just fine?

### Solution

Review the code, the patches, and add normal support for old apks without messing with them to the point they are unusable, a year ago even old apks could be patched perfectly fine with 0 issues. Review the issue with vpn.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2024-08-09 10:22
If your VPN blocks YouTube history, it's the VPNs fault. Otherwise dupe of #3208

**Closed by oSumAtrIX** 2024-08-09 10:22 UTC
Labels: Bug report
