### ISSUE TITLE
swipe-controls patch disables doubletap to skip

### ISSUE THREAD

**Issue by jonas-hurst** [revanced/revanced-patches#126] opened 2022-07-07 12:36 UTC
I have noticed that the fenster-swipe-controls patch makes it impossible to use double-tap-to-skip functionality.
I used patches release 2.9.4

**Reproduce:**
1. use fenster-swipe-controls patch
2. open a video
3. switch to full-screen view
4. double-tap on the right side of the screen

**Expected behaviour**
Video skips x seconds (number of seconds specified in settings)

**Actual behaviour**
Nothing happens

**Comment by jonas-hurst** [comment] 2022-07-07 12:38
Same applies when double-tapping on the left side of the screen to go back x seconds in the video.
Nothing happens here either.

**Comment by TheJeterLP** [comment] 2022-07-07 12:53
Dupe of #124

**Closed** 2022-07-07 12:53 UTC
