### ISSUE TITLE
Custom playback speed become toggleable

### ISSUE THREAD

**Issue by Mohammed1520** [revanced/revanced-patches#521] opened 2022-09-17 21:25 UTC
### Application

YouTube 

### Issue

Custom playback speed should be toggleable 

### Patch

This patch should allow users to change custom playback speed to on or off

### Motivation

It will rise the quality of revanced

**Comment by oSumAtrIX** [comment] 2022-09-17 21:28
Dupe of #395.

**Closed by oSumAtrIX** 2022-09-17 21:28 UTC
Labels: patch-request
