### ISSUE TITLE
RYD having problems with video loading page hangs and freezes

### ISSUE THREAD

**Issue by VICTOR-KENES** [revanced/revanced-patches#1228] opened 2022-12-08 16:55 UTC
### Type

Error at runtime

### Bug description

Fix Patch RYD , because there is a conflict with the video loading page is freezing crashing

### Steps to reproduce

RYD bug 

### Relevant log output

```shell
No
```

### Screenshots or videos

![Screenshot_20221208-102747_YouTube](https://user-images.githubusercontent.com/117227172/206514693-9bd8081e-e55a-43e1-b302-46fdd5be2f79.jpg)

### Solution

Fix the RYD Patch

### Additional context

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2022-12-08 17:00
Please record the following in one go:
1. Open the patched app
2. Play a video & show the issue
3. Disable RYD & show that the issue is gone by playing multiple other videos

**Comment by Lisouseinaikyrios** [comment] 2022-12-09 19:29
Is ReVanced actually crashing?  Or does the video start playing, the UI freezes, and then 4 seconds later the UI unfreezes?

If revanced is not crashing but only temporarily freezing, then the issue is the RYD api is taking an excessively long time to respond while the ReVanced UI is waiting for the response.

Currently, ReVanced adds the dislike count synchronously while creating the UI.  While the client waits for the RYD api to respond, the UI is frozen.  Once it gets the RYD response it finishes creating the UI and unfreezes.  Currently ReVanced waits up to 4 seconds before giving up and not including the dislike count.  Of note, the video start playing immediately and is not affected by this limitation -- it's only the player controls/comments/etc (everything except the video itself).    

The last few months the RYD api has been acting up sporadically.  During development I've seen API calls take minutes and the RYD backend never responds at all.  It has no rhyme or reason when it does this, sometimes the same call will fail (with no response for minutes on end), and then trying the same call again it responds in a few milliseconds.   Ideally the RYD api would fix whatever is going wrong, but that is outside the scope and possibly for anyone except RYD itself (the RYD backend code is closed source).


An improvement, is for ReVanced to show when an API call fails.  Such as where the dislike count would go, instead show a question mark or something, so the user can infer that something went wrong with RYD.


A temporary half fix for the UI freezing, is to reduce the client timeout from 4 seconds to 3 or 2 seconds.  Then when the RYD api is slow to respond, the client wont appear frozen for as long.  The downside is more often the dislike count will not be shown, as there are times when it takes 4 seconds for the API to successfully respond with the data.


The permanent fix, is for ReVanced to update the UI dislike count asynchronously.  Then the player UI would open immediately with no lag or delay, and the dislike count would be added to the UI whenever the RYD api responds (if it successfully responds).

This change would also allow fixing
https://github.com/revanced/revanced-patches/issues/1140
And also
https://github.com/revanced/revanced-patches/issues/1140

This solution needs the patch injection points changed.  I can help make any changes to integration, but I'd need some help figuring out the patch changes.

**Comment by oSumAtrIX** [comment] 2022-12-09 19:36
@Lisouseinaikyrios To create a full fledged fix, we would need to be able to text of the UI component after it has been created and added to the component tree. There is currently no known way of doing so and would require additional reverse engineering efforts to figure out. This would also also fix the issue when the text is redrawn the changes are lost. A "half fix" can be introduced which halfs the timeout everytime it fails, and resets after a specific time or condition, in addition to showing a toast on what happened.

**Comment by VICTOR-KENES** [comment] 2022-12-09 20:32
If there is a new RYD correction, can we follow it on GitHub?

**Comment by Lisouseinaikyrios** [comment] 2022-12-09 20:51
> If there is a new RYD correction, can we follow it on GitHub?

A new correction to the RYD api?  The API is closed source, and there is no way to track any changes or fixes made to it.

**Comment by VICTOR-KENES** [comment] 2022-12-09 21:05
So for me to understand better, RYD will not be fixed, will there always be this problem with the video page loads, will there always be this problem, will it not be fixed?

**Comment by Lisouseinaikyrios** [comment] 2022-12-09 21:17
I will try coding up the half fix suggested here --  that will improve things.  When loading a 
new video, occasionally the UI may still freeze for a few seconds but it will be less noticable and less annoying.

**Comment by VICTOR-KENES** [comment] 2022-12-09 21:29
Got it, thanks for trying to improve RYD as much as possible when uploading videos, I really appreciate your wisdom, it's a real shame that there's no way to make it 100% fast without disturbing video uploads

**Comment by cuynu** [comment] 2022-12-10 14:11
Oh, I just realized now that RYD's API is closed source. I thought it was open source before

**Comment by VICTOR-KENES** [comment] 2022-12-10 15:28
Wow, if it's closed code, can't you do anything, can't you move or fix this problem?

**Comment by VICTOR-KENES** [comment] 2022-12-12 14:16
My god, if it's closed source, is there anything you can do?

**Comment by VICTOR-KENES** [comment] 2022-12-13 20:57
if it's closed source, is there anything you can do? please try to fix

**Comment by LisoUseInAIKyrios** [comment] 2022-12-14 00:09
> if it's closed source, is there anything you can do? please try to fix
cuynu was only commenting to himself.  Some improvements to ReVanced RYD are still in progress.

**Comment by cuynu** [comment] 2022-12-14 03:43
> > if it's closed source, is there anything you can do? please try to fix
> 
> cuynu was only commenting to himself. Some improvements to ReVanced RYD are still in progress.

Yeah, I just think ryd api closed source only

**Comment by VICTOR-KENES** [comment] 2022-12-14 16:08
Got it , ok , it 's still in excellent correction , I 'll follow it here when it comes out , you 'll post the RYD correction

**Comment by cuynu** [comment] 2022-12-16 13:18
RYD on ReVanced should work the same way Vanced is doing, in Vanced, Layout UI appears first, then RYD starts connecting to the API. ReVanced is letting RYD connect to the API to get dislikes first then show Layout UI

**Comment by oSumAtrIX** [comment] 2022-12-16 13:20
Not possible because it is hooked when the component is created.

**Comment by VICTOR-KENES** [comment] 2022-12-16 13:37
Hello oSum, I understood correctly, so there will be a correction in a new update of this RYD?

**Comment by VICTOR-KENES** [comment] 2022-12-18 11:59
cuynu ok, is there no way to let the Layout load first immediately, then load the RYD API last

**Comment by VICTOR-KENES** [comment] 2022-12-19 20:54
17.49.37 still has that problem the RYD doesn't let the page load and crashes and freezes

**Comment by LisoUseInAIKyrios** [comment] 2022-12-19 21:06
A few changes to ReVanced will be released very soon and it might improve things.

**Comment by LisoUseInAIKyrios** [comment] 2022-12-21 22:42
> LisoUseinAIKyrios , Great news , I 'm waiting for these changes to compile in the manager , Will it still be this year?

Some performance changes were just released.  Try updating to v2.147.0, and use the app for a bit.

Load a few videos, then go to ReVanced settings -> misc -> debugging, and enable debugging.

Then look under ReVanced settings -> Return YouTube Dislike, and take a screen shot of the statistics information.  Post the screen shot here.  The screen shot will look something like [this](https://freeimage.host/i/HoDNhKB)

**Comment by LisoUseInAIKyrios** [comment] 2022-12-22 14:48
Some performance changes were just released.  Use ReVanced manager and update to v2.147.0, and see if that helps.

RYD performance statistics and now viewable.  Enable ReVanced debugging, and then RYD settings panel will show RYD API statistics (it will look similar to [this](https://freeimage.host/i/HoDNhKB))

**Comment by VICTOR-KENES** [comment] 2022-12-22 15:53
Yes , I already did the compilation using version 2.147.0 , I 'm testing it right now , but I did not put the debug Patch is it necessary to put the debug Patch ?

**Comment by LisoUseInAIKyrios** [comment] 2022-12-22 16:31
Debug is only needed if you want to view the statistics.

**Comment by VICTOR-KENES** [comment] 2022-12-22 17:40
I got it right about debugging , I 'm testing 2.147.0 , with RYD , I 'm hoping the page does not take too long to load or it crashes and freezes , I 'm testing several random videos , clicking 1 then the other quick video

**Comment by VICTOR-KENES** [comment] 2022-12-22 17:41
I understood about debugging , I 'm testing 2.147.0 , with RYD , I 'm hoping the page does not take too long to load or it crashes and freezes , I 'm testing several random videos , clicking 1 then the other quick video

**Comment by LisoUseInAIKyrios** [comment] 2022-12-22 18:09
Try patching with debugging, so you can view the RYD statistics (it would be useful to see).

**Comment by VICTOR-KENES** [comment] 2022-12-22 20:47
Yes

**Comment by cuynu** [comment] 2022-12-24 11:15
At this point, only ReVanced Extended (inotia00) has fixed the RYD issue

**Comment by TheGoldenSun** [comment] 2022-12-24 12:56
@LisoUseInAIKyrios 
![Screenshot_20221224_075333](https://user-images.githubusercontent.com/104534608/209437278-f33733e3-07ce-4e60-8d0d-80ac8bfc67a9.png)
![Screenshot_20221224_075400](https://user-images.githubusercontent.com/104534608/209437279-60bd11ae-d334-410e-aa6a-82d49eb411cd.png)

The ryd dislikes disappeared once more so here's the screenshot you wanted.

**Comment by LisoUseInAIKyrios** [comment] 2022-12-24 19:28
> The ryd dislikes disappeared once more so here's the screenshot you wanted.

There was no timeouts, and the statistics show RYD API was working correctly.

In your screen shot, the dislike count is not shown because a different issue (https://github.com/revanced/revanced-patches/issues/1133).  The temporary fix, is to scroll down the comment section (so the dislike count is not visible anymore), and then scroll back up.  Then the dislike count is visible again.

**Comment by TheGoldenSun** [comment] 2022-12-24 19:48
Thank you that did the trick although I'm using inotia00's updated version
of dislike feature he made for revanced extended users.


The ryd dislikes disappeared once more so here's the screenshot you wanted.

**Comment by VICTOR-KENES** [comment] 2022-12-24 20:20
inotia00 is he part of the revanced team? because I myself do not use easy to steindete I use the normal Rematch from the OSum team

**Comment by VICTOR-KENES** [comment] 2022-12-24 20:21
inotia00 is he part of the revanced team? because I myself do not use the revanced exentend, I use the normal Revanced from the OSum team

**Comment by oSumAtrIX** [comment] 2022-12-24 20:23
This is offtopic from #1228 and related to  #1133. Freezing is caused by slow internet connections which can be debugged with the latest patches.

**Comment by VICTOR-KENES** [comment] 2022-12-25 23:44
Osum I use 5G wi fi , 600 megs internet , and even then it freezes , so the problem is not on the internet

**Comment by VICTOR-KENES** [comment] 2022-12-25 23:46
Osum I use 5G wi fi , 600 megs internet , and even then it crashes and freezes , so the problem is not on the internet

**Comment by oSumAtrIX** [comment] 2022-12-26 03:45
@VICTOR-KENES Follow [this comment](https://github.com/revanced/revanced-patches/issues/1228#issuecomment-1362928136).

**Comment by VICTOR-KENES** [comment] 2022-12-26 11:37
@oSumAtrIX  ,  Yes I'm following everything general

**Comment by oSumAtrIX** [comment] 2022-12-26 16:06
Send a screenshot of the stats please.

**Comment by VICTOR-KENES** [comment] 2022-12-26 21:25
@oSumAtrIX , como que eu mando as estatísticas

**Comment by LisoUseInAIKyrios** [comment] 2023-01-08 08:15
With the recent changes made in the past few weeks, the issue seems to have been resolved.

For now, I'm calling this fixed.

**Comment by oSumAtrIX** [comment] 2023-01-08 08:16
Thank you for continuous contribution.

**Comment by VICTOR-KENES** [comment] 2023-01-08 19:37
Hello, so far the problem has been resolved, let's hope it doesn't happen again and that it remains excellent

**Closed** 2023-01-08 19:37 UTC
Labels: bug, question
