### ISSUE TITLE
feat: Allow ads on selected youtube channels (I saw the other thread)

### ISSUE THREAD

**Issue by alcatraz-zz** [ReVanced/revanced-patches#3135] opened 2023-10-12 02:22 UTC
### Feature description

Allow the complete disabling of ad blocking on SELECTED youtube channels. Thanks!

I saw the other closed thread from 2022 where you deem this feature to be implemented and done. I'm using the latest patches and the option isn't available, nor is it disabled in the revanced settings. I just spent 15min looking for it. If it does exist it must perhaps be individually enabled. Can you then tell me where it is and what it's called. Thanks!

### Motivation

It helps content creators we really like.

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2023-10-12 02:24
Dupe of https://github.com/ReVanced/revanced-patches/issues/651

**Closed by oSumAtrIX** 2023-10-12 02:24 UTC
Labels: Feature request

**Comment by alcatraz-zz** [comment] 2023-10-12 02:56
> Dupe of #651

Can you please help instead of just closing the thread. I saw the other thread and there are posters wondering where this feature is. They are getting no help. What other choice is there but ask again?

**Comment by oSumAtrIX** [comment] 2023-10-12 03:12
This is not a support channel and this issue is a duplicate of the other open issue, yet you knowingly opened another.

**Comment by alcatraz-zz** [comment] 2023-10-12 04:42
Thanks for taking the time to reply .. 

...but why not tick all the requests as done/closed then? Noone can ask where the featues actually are because that's a "support matter".

You don't see a problem? 

A guy is waiting 1 year for a reply in that thread. Obviously that's not the right place to post anything. Can you blame anyone for asking again?

Please.

**Comment by oSumAtrIX** [comment] 2023-10-12 04:46
> but why not tick all the requests as done/closed then

Because they are not done yet.

> Noone can ask where the featues actually are because that's a "support matter".

There is a dedicated tag for feature requests. Regardless this is not a place for support but a development environment. 

> A guy is waiting 1 year for a reply in that thread.

No-one is waiting for a reply in the other issue and even if, this does not mean to open a duplicate and tick that it is not

**Comment by alcatraz-zz** [comment] 2023-10-13 02:49
> Because they are not done yet.

This feature isn't done yet either. It was just marked closed.

Is there a reason for not doing it? I'm curious.

**Comment by oSumAtrIX** [comment] 2023-10-13 02:55
Read my initial reply and the first checkmark you ticked.
