### ISSUE TITLE
bug: Ads in YouTube Shorts

### ISSUE THREAD

**Issue by GeekCornerGH** [revanced/revanced-patches#415] opened 2022-08-31 16:29 UTC
### Type

Other

### Bug description

While scrolling through shorts tab, sometimes I see ads. Also ads ui is broken too

### Steps to reproduce

1. Launch ReVanced, with default patches
2. Go in Shorts tab
3. Scroll through shorts, and wait for an ad to appear

### Relevant log output

```shell
Didn't found anything useful in logs
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/45696571/187730341-38f2cfdf-0507-4783-b25f-5bbd351cca42.png)

### Additional context

I may help debugging if you need, I'm on Discord, GeekCornerD#8010

**Comment by oSumAtrIX** [comment] 2022-08-31 16:38
Dupe of #393.

**Comment by GeekCornerGH** [comment] 2022-08-31 16:39
Will there be shorts ad blocking?

**Closed by oSumAtrIX** 2022-08-31 16:38 UTC
Labels: bug
