### ISSUE TITLE
bug: Dark theme in settings

### ISSUE THREAD

**Issue by 3v01ut10n** [revanced/revanced-patches#269] opened 2022-08-01 08:30 UTC
### Type

Cosmetic

### Bug description

When the system dark theme is enabled, it is not applied in the "Return YouTube Dislike Settings", "SponsorBlock Settings", "ReVanced Settings"

### Steps to reproduce

1. Enable Dark theme in system
2. Open Youtube Settings
3. Open ReVanced Settings

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20220801-122918_YouTube_ReVanced](https://user-images.githubusercontent.com/20968560/182107084-e696e80c-fdbd-4456-8f9c-82b1980aadba.png)
![Screenshot_20220801-122922_YouTube_ReVanced](https://user-images.githubusercontent.com/20968560/182107106-5393847c-ffef-4630-a1f7-97c1172bd3e3.png)

### Solution

Add support dark theme in this menus

**Comment by reisxd** [comment] 2022-08-01 08:34
Dupe of #261

**Comment by Sculas** [comment] 2022-08-01 08:49
Duplicate of #261

**Closed by Sculas** 2022-08-01 08:49 UTC
Labels: bug
