### ISSUE TITLE
problem: Ad(s) in x pop up

### ISSUE THREAD

**Issue by bogadana** [revanced/revanced-patches#165] opened 2022-07-12 14:28 UTC
## 🐞 Issue

Ad warning pop up shows even though no ads follow

## ⚙ Reproduce

1. apply `video-ads` patch
2. watch video and wait

## 🛠 Solution

`video-ads` should remove this

## ⚠ Additional context

![image](https://user-images.githubusercontent.com/30848157/178513343-eeaba029-6f08-43b1-a6b2-b00e06dc37fe.png)

**Comment by TheJeterLP** [comment] 2022-07-12 14:32
cant reproduce this

**Comment by bogadana** [comment] 2022-07-12 14:35
obviously you cant in 2 seconds. only shows up sporadically, probably in places where ads are supposed to be

**Comment by bogadana** [comment] 2022-07-12 14:42
weird then cause it happens multiple times per video for me. might be related to the poland conspiracy

**Comment by CDzungx** [comment] 2022-07-28 21:05
> weird then cause it happens multiple times per video for me. might be related to the poland conspiracy

Happens for me also

**Comment by masterflitzer** [comment] 2022-08-11 11:59
happens to me (germany) too

i suspect it's because the same area is used for the skip segments button maybe it's shown when i have it enabled in sponsorblock, i disabled it now and will check in the coming days if i encounter another of those

if i don't it's likely a bug in the sponsorblock patch

**Comment by masterflitzer** [comment] 2022-08-12 10:10
i had disabled sponsorblock for a day now but just encountered a "ad in x" popup, so this is unrelated to sponsorblock also using skip segment button

**Comment by oSumAtrIX** [comment] 2022-10-07 21:21
Fixed in commit fbc83a22d37012394311a87d27202b7cc86e047d.

**Closed by oSumAtrIX** 2022-10-07 21:21 UTC
Labels: bug
