### ISSUE TITLE
feat(patch): Bypass "Viewer discretion is advised" warning

### ISSUE THREAD

**Issue by fuwa-fuwa-fapmachine** [ReVanced/revanced-patches#1388] opened 2023-01-30 16:15 UTC
### Application

YT Music

### Issue

Certain songs trigger a content warning dialog that must be accepted before the song can be played. The song does not play if you do not manually accept the warning. In playlists, these songs are skipped.

### Patch

These dialogs are bypassed/disabled.

### Motivation

You have to give confirmation manually every single time you play one of these songs. Very annoying because you have to confirm these over and over whenever you listen to these songs. Also can't listen to these in playlists, they get skipped. Would be nice to disable these.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bceez** [comment] 2024-01-05 20:23
Duplicate of https://github.com/ReVanced/revanced-patches/issues/2141

**Closed** 2024-01-05 20:24 UTC
Labels: Feature request
