### ISSUE TITLE
bug: No patched apps installed

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches#3187] opened 2023-10-24 00:37 UTC
### Bug description

Revanced Manager shows no installed patched apps and I have the patched YouTube installed
![Screenshot_2023-10-24-02-32-15-913_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/18757054/6ca5bc05-25ed-4c4d-af86-68d309c348a6)
![Screenshot_2023-10-24-02-32-45-887_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/4be248fc-3006-4395-bc53-71aaa50bf91e)
![Screenshot_2023-10-24-02-32-51-389_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/820c5238-d0ba-4f64-9a20-ecc4becb5dcb)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment] 2023-10-24 01:32
This issue belongs in the ReVanced Manager repository. However, it may be a duplicate of https://github.com/ReVanced/revanced-manager/issues/1391

**Comment by GKid94** [comment] 2023-10-24 02:31
> This issue belongs in the ReVanced Manager repository. However, it may be a duplicate of [ReVanced/revanced-manager#1391](https://github.com/ReVanced/revanced-manager/issues/1391)

Ok then close this

**Closed** 2023-10-24 04:50 UTC
Labels: Bug report
