### ISSUE TITLE
feat(YouTube): Hide Shorts and related videos under the video

### ISSUE THREAD

**Issue by DrSapling** [ReVanced/revanced-patches#2677] opened 2024-01-30 18:47 UTC
### Feature description

Hide Shorts and related videos under the YouTube videos' description's.

Related videos themselves can be hidden by entering a custom filter ```related_video``` but some say this may lead account getting banned, and it is inconvenient as it is not a regular Patch so not everybody can just easily enable it. Moveover, I was unable to find a filter that hides Shorts under a video.

### Motivation

Lower probability of getting distracted.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment] 2024-01-30 19:03
Shorts can already be hidden.

And hiding related videos is a dupe of https://github.com/ReVanced/revanced-patches/issues/886

**Closed** 2024-01-30 19:07 UTC
Labels: Feature request

**Comment by DrSapling** [comment] 2024-01-30 21:46
I still watch channels which post Shorts (like Vsauce, or Steve Mould). That would hide them from subscriptions tab.
