### ISSUE TITLE
bug: YouTube ReVanced randomly skips to the next short

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [ReVanced/revanced-patches#2851] opened 2024-03-07 00:59 UTC
### Bug description

YouTube ReVanced skips to the next short at a certain point in the video on some videos. The info (title, likes etc.) remains the same.
Steps to reproduce:
1. Open youtube shorts (not all shorts have this problem)
2. Wait for it to skip or scroll forward 

### Additional context

Some videos that have this problem (for me, I'm not sure if anyone else would be able to replicate this): 
https://youtube.com/shorts/K-9x9Ax5LLA
https://youtube.com/shorts/2TSCfJNgNY4

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2024-03-07 01:12
Can you record the issue?

**Comment by B4NT3R** [comment] 2024-03-07 05:29
Happening to me too

https://github.com/ReVanced/revanced-patches/assets/108476601/c23b52b3-1391-4ce6-affb-38ff1753a72a

**Comment by oSumAtrIX** [comment] 2024-03-07 05:30
Follow this:

![image](https://github.com/ReVanced/revanced-patches/assets/13122796/8f98ea7a-4119-4e25-b3b8-62fc45a90d5f)

**Comment by QuangBuiCP** [comment] 2024-03-07 16:15
Since this issue has been reported, I may contribute another issue to it.
One thing to note is that this issue **only occurred when you have spoofed the app version down to v17**.

On my end, the short I clicked on did not play at all and prompted with `This video is not available`, then it skipped and played the next short.

<details>
  <summary>The screenshot:</summary>

  ![Screenshot_2024-03-07-18-51-01-46](https://github.com/ReVanced/revanced-patches/assets/61906801/f9c9dc7c-af8b-4d42-a657-66d7ecfd19b6)

</details>

Of course, maybe the issue relied on the spoofed version setting (it only occurred in v17), but after seeing this issue, I highly doubt it since I think it was something about Short's handling code)

I will try to help with all I have, cheers!
-QuangBuiCP

**Comment by Andrei-Iosifescu123** [comment] 2024-03-07 21:24
> Can you record the issue?

https://imgur.com/a/d16QssA

**Comment by oSumAtrIX** [comment] 2024-03-07 21:37
> One thing to note is that this issue only occurred when you have spoofed the app version down to v17.

As far as I am concerned, spoofing older versions will come with side effects, which is why you were shown the warning when you toggled the patch.

Please follow [this](https://github.com/ReVanced/revanced-patches/issues/2851#issuecomment-1982392638) comment. Once it is clear, its caused by any other patch, it may be worth looking into it, until then I'll be closing the issue.

**Closed by oSumAtrIX** 2024-03-07 21:37 UTC
Labels: Bug report, Waiting on author
