### ISSUE TITLE
Controversial warning before opening video

### ISSUE THREAD

**Issue by Jakenevada** [revanced/revanced-patches#2493] opened 2023-06-25 17:54 UTC
### Application

Youtube:ReVanced

### Issue

Annoying warning about something that is most likely obvious from title or thumbmail of video

### Patch

Add option/patch to remove this warning

### Motivation

In issue tab
![1](https://github.com/revanced/revanced-patches/assets/132659424/e727dc0f-e97e-4bef-acc5-6ccd8494eac8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-06-25 17:55
Dupe of some other issue i cant find right now

**Closed by oSumAtrIX** 2023-06-25 17:55 UTC
Labels: patch-request

**Comment by Jakenevada** [comment] 2023-06-25 18:07
I couldnt find this issue too thus i posted it
