### ISSUE TITLE
feat: remove buttons from action bar (Dislike, Create, Clip)

### ISSUE THREAD

**Issue by philklc** [revanced/revanced-patches#411] opened 2022-08-31 09:24 UTC
### Type

Other

### Issue

YouTube crammed so much buttons into the action bar that it can be scrolled. A button might be accidentally tapped on when the user just wanted to scroll for the correct button to press.

### Feature

A settings page to enable/disable the display of the following buttons: Dislike, Create, Clip

### Motivation

This is especially useful for the Dislike button, which might send the wrong signal to the video uploader and/or the RYD API if accidentally tapped on.

**Comment by TheGoldenSun** [comment] 2022-08-31 09:33
To be honest the number of likes works but dislikes numbers stays the name it doesn't change unlike the "likes" that changes daily. Message ID: ***@***.***>

**Comment by oSumAtrIX** [comment] 2022-08-31 16:00
Dupe of https://github.com/orgs/revanced/discussions/110.

**Closed by oSumAtrIX** 2022-08-31 16:00 UTC
Labels: feature-request
