### ISSUE TITLE
Downloads for YouTube-Music as well

### ISSUE THREAD

**Issue by Curve** [revanced/revanced-patches#375] opened 2022-08-22 11:28 UTC
### Type

Functionality

### Issue

The current `downloads` patch does not work for YouTube Music.

### Feature

A yt-dlp integration for YouTube Music would be extremely useful.

Also regarding the current implementation, please consider replacing `PowerTube` with another alternative, maybe [NewPipe](https://github.com/TeamNewPipe/NewPipe) or a library for yt-dlp: https://github.com/yausername/youtubedl-android

### Motivation

The current implementation uses `PowerTube` which is closed source and contains ads, also it still uses youtube-dl which is no longer being updated, it would be really beneficial if we could switch to something that uses yt-dlp instead since it is being updated more frequently and also has way better download speeds than yt-dl.

**Comment by oSumAtrIX** [comment] 2022-08-22 12:41
Wrong place to suggest patches. Also dupe of another suggestion.

**Closed by oSumAtrIX** 2022-08-22 12:41 UTC
Labels: feature-request

**Comment by Curve** [comment] 2022-08-22 14:54
> Wrong place to suggest patches. Also dupe of another suggestion.

Should I move this to the GitHub Discussions?

Also, out if curiosity, what's the duplicate issue? So that I can follow progress there

**Comment by oSumAtrIX** [comment] 2022-08-22 14:57
> Also, out if curiosity, what's the duplicate issue? So that I can follow progress there

https://github.com/orgs/revanced/discussions/290
