### ISSUE TITLE
Dark mode for TikTok

### ISSUE THREAD

**Issue by LostCat123** [revanced/revanced-patches#506] opened 2022-09-16 15:52 UTC
### Application

TikTok

### Issue

Idk

### Patch

Dark mode for TikTok 

### Motivation

Reduce eye damage

**Comment by oSumAtrIX** [comment] 2022-09-16 17:24
Dupe of #421.

**Closed by oSumAtrIX** 2022-09-16 17:24 UTC
Labels: patch-request

**Comment by MCHAMSTERYT2** [comment] 2023-04-30 21:03
It has the patch request label

**Comment by oSumAtrIX** [comment] 2023-04-30 21:10
#1061
