### ISSUE TITLE
feat: Universal patch that allows you to change the icon

### ISSUE THREAD

**Issue by xahem** [ReVanced/revanced-patches#2763] opened 2024-02-22 12:36 UTC
### Feature description

Since you can change the icon of YouTube to a custom icon, I would like a universal patch that would let me change the icon of any app.

### Motivation

Android has a material you icon theme for any apps with specific icon images, however some developers do not provide that icon, so they do not get material you icon themed. I'm hoping to be able to change the icon of those apps so that they can be material you themed.
![Screenshot_20240222-133551~2](https://github.com/ReVanced/revanced-patches/assets/97387346/65aa67ec-fc8f-4416-a74d-89beb3de5bbb)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment] 2024-02-22 15:05
#362

**Comment by oSumAtrIX** [comment] 2024-02-22 15:26
ReVanced is not an icon editor. If you want to edit icons there's plenty of apps you can use. Dupe of #362

**Closed by oSumAtrIX** 2024-02-22 15:26 UTC
Labels: Feature request
