### ISSUE TITLE
bug: Enable pull-down referesh

### ISSUE THREAD

**Issue by johnconner122** [revanced/revanced-patches#610] opened 2022-09-24 13:54 UTC
### Type

Other

### Bug description

Can't refresh youtube homepage by pulling-down

### Steps to reproduce

Open youtube revanced app and swipe down on home to reload but can't refresh

### Relevant log output

```shell
null
```

### Solution

General ads patch might hiding more than it should.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by GravlLift** [comment] 2022-11-02 16:03
@oSumAtrIX, doesn't seem like this issue should be closed. Yes, it's a dupe of #550, which is a dupe of #529, which is a dupe of #348, which is a dupe of [a discussion](https://github.com/orgs/revanced/discussions/264), but the reason these issues keep popping up is because there is no fix for this problem, only an [unsatisfactory workaround](https://github.com/orgs/revanced/discussions/264#discussioncomment-3030870).

The issue should be re-opened until an actual fix exists.

**Comment by Julienraptor01** [comment] 2022-11-16 15:54
actually if you click on a category button, you can reload, so what i do is just click on the 1st actegory and reload and since reloading take back to the all category but reloaded, it's a great workaround i found

**Comment by johnconner122** [comment] 2022-11-16 17:14
> Actually if you click on a category button, you can reload, so what i do is just click on the 1st category and reload and since reloading take back to the all category but reloaded, it's a great workaround i found The category bar appear on top of the flow or appear if you slide down if you're not at the top of the flow

I am using the same workaround.

**Comment by GravlLift** [comment] 2022-11-16 20:28
> > Actually if you click on a category button, you can reload, so what i do is just click on the 1st category and reload and since reloading take back to the all category but reloaded, it's a great workaround i found The category bar appear on top of the flow or appear if you slide down if you're not at the top of the flow
> 
> I am using the same workaround.

Works great except when the categories also don't load. Then we're out of luck and need to restart the app.

**Comment by Julienraptor01** [comment] 2022-11-16 20:37
> > > Actually if you click on a category button, you can reload, so what i do is just click on the 1st category and reload and since reloading take back to the all category but reloaded, it's a great workaround i found The category bar appear on top of the flow or appear if you slide down if you're not at the top of the flow
> > 
> > I am using the same workaround.
> 
> Works great except when the categories also don't load. Then we're out of luck and need to restart the app.

Click onto shorts or subscriptions and go back to main menu to see the categories come back

**Comment by GravlLift** [comment] 2022-11-17 03:50
> > > > Actually if you click on a category button, you can reload, so what i do is just click on the 1st category and reload and since reloading take back to the all category but reloaded, it's a great workaround i found The category bar appear on top of the flow or appear if you slide down if you're not at the top of the flow
> > > 
> > > I am using the same workaround.
> > 
> > Works great except when the categories also don't load. Then we're out of luck and need to restart the app.
> 
> Click onto shorts or subscriptions and go back to main menu to see the categories come back

No dice. Categories remain absent, even after navigation to subscriptions and back (shorts intentionally disabled):

![Screenshot_20221116-224808~2.jpg](https://user-images.githubusercontent.com/27774026/202350663-0bad4ad4-8ba5-4a37-8c41-f42fadd035c7.jpg)

**Comment by Julienraptor01** [comment] 2022-11-17 09:05
> > > > > Actually if you click on a category button, you can reload, so what i do is just click on the 1st category and reload and since reloading take back to the all category but reloaded, it's a great workaround i found The category bar appear on top of the flow or appear if you slide down if you're not at the top of the flow
> > > > 
> > > > 
> > > > I am using the same workaround.
> > > 
> > > 
> > > Works great except when the categories also don't load. Then we're out of luck and need to restart the app.
> > 
> > 
> > Click onto shorts or subscriptions and go back to main menu to see the categories come back
> 
> No dice. Categories remain absent, even after navigation to subscriptions and back (shorts intentionally disabled):
> 
> ![Screenshot_20221116-224808~2.jpg](https://user-images.githubusercontent.com/27774026/202350663-0bad4ad4-8ba5-4a37-8c41-f42fadd035c7.jpg)

sorry, you're out of luck then, you'll need to wait for a patch
(btw good choice tom scott, he's a great YTbr)

**Comment by nikhilbadyal** [comment] 2022-11-26 19:06
I once read somewhere that [this](https://github.com/facebook/litho/issues/788) is the cause.

**Comment by oSumAtrIX** [comment] 2022-12-09 01:28
test

**Closed** 2022-12-09 01:29 UTC
Labels: bug, released, released on @dev
