### ISSUE TITLE
Could not resolve all files for configuration ':compileClasspath' error  after $ gradle build

### ISSUE THREAD

**Issue by rajeshrvds** [revanced/revanced-patches#36] opened 2022-06-19 15:26 UTC
$ gradle build
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
   > Could not resolve all files for configuration ':compileClasspath'.
      > Could not find org.apktool:apktool-lib:2.6.2-SNAPSHOT.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/org/apktool/apktool-lib/2.6.2-SNAPSHOT/maven-metadata.xml
          - https://repo.maven.apache.org/maven2/org/apktool/apktool-lib/2.6.2-SNAPSHOT/apktool-lib-2.6.2-SNAPSHOT.pom
          - https://maven.pkg.github.com/revanced/revanced-patcher/org/apktool/apktool-lib/2.6.2-SNAPSHOT/maven-metadata.xml
          - https://maven.pkg.github.com/revanced/revanced-patcher/org/apktool/apktool-lib/2.6.2-SNAPSHOT/apktool-lib-2.6.2-SNAPSHOT.pom
        Required by:
            project : > app.revanced:revanced-patcher:1.1.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Sculas** [comment] 2022-06-19 15:27
Duplicate of #34

**Closed by Sculas** 2022-06-19 15:27 UTC
