### ISSUE TITLE
bug: patching twitch fails after decoding resources

### ISSUE THREAD

**Issue by ZeroOne010101** [ReVanced/revanced-patches#3568] opened 2024-08-20 16:07 UTC
### Bug description

When attempting to patch (v4.13.3) twitch using the revanced manager (v1.21.2) the attached error occurs.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: Pixel 8a
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: tv.twitch.android.app v16.9.1 (Suggested: 16.9.1)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 280 byte allocation with 3378352 free bytes and 3299KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:51)
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:47)
	at java.nio.CharBuffer.allocate(CharBuffer.java:177)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:843)
	at brut.androlib.res.decoder.StringBlock.decodeString(Unknown Source:18)
	at brut.androlib.res.decoder.StringBlock.getString(Unknown Source:41)
	at brut.androlib.res.decoder.StringBlock.getHTML(Unknown Source:0)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(Unknown Source:41)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(Unknown Source:72)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(Unknown Source:438)
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(Unknown Source:150)
	at brut.androlib.res.decoder.ARSCDecoder.decode(Unknown Source:5)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(Unknown Source:16)
	at brut.androlib.res.data.ResTable.loadFrameworkPkg(Unknown Source:43)
	at brut.androlib.res.data.ResTable.getPackage(Unknown Source:15)
	at brut.androlib.res.data.ResTable.getResSpec(SourceFile:0)
	at brut.androlib.res.data.ResTable.getResSpec(SourceFile:0)
	at brut.androlib.res.decoder.AXmlResourceParser.decodeFromResourceId(Unknown Source:4)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeName(Unknown Source:26)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeName(Unknown Source:2)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(Unknown Source:64)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Unknown Source:82)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(Unknown Source:86)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(Unknown Source:39)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(Unknown Source:4)
	at brut.androlib.res.decoder.ResFileDecoder.decode(SourceFile:0)
	at brut.androlib.res.decoder.ResFileDecoder.decode(SourceFile:0)
	at brut.androlib.res.ResourcesDecoder.decodeResources(Unknown Source:160)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(Unknown Source:44)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:214)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:437)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MBMBEZ/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Additional context

I believe this to be a distinct from #2647 as the error is different and seems to stem from either file access or heap allocation issues.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment] 2024-08-20 16:07
Dupe of all the other OOM errors.

**Closed by oSumAtrIX** 2024-08-20 16:07 UTC
Labels: Bug report
