### ISSUE TITLE
feat: (YouTube) pause before downloading and resume after

### ISSUE THREAD

**Issue by bremaya** [ReVanced/revanced-patches#2870] opened 2024-03-12 17:53 UTC
### Feature description

I would like a function in the patches that would give the possibility that when clicking the download button in the player, the video would be paused before and resumed immediately after, so that PiP mode is not activated and we lose the logic of the subject of the video we are watching it before downloading it (other than that it's a huge time saver).

### Motivation

I would like a function in the patches that would give the possibility that when clicking the download button in the player, the video would be paused before and resumed immediately after, so that PiP mode is not activated and we lose the logic of the subject of the video we are watching it before downloading it (other than that it's a huge time saver).

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by Bceez** [comment] 2024-03-12 17:58
Duplicate of https://github.com/ReVanced/revanced-patches/issues/467

**Closed** 2024-03-12 18:11 UTC
Labels: Feature request
